
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Node: 'Node',
  Edge: 'Edge',
  Asset: 'Asset',
  Agent: 'Agent',
  McpServer: 'McpServer',
  Tool: 'Tool',
  AgentTool: 'AgentTool',
  AgentAction: 'AgentAction',
  checkpoints: 'checkpoints',
  writes: 'writes',
  ThreadMetadata: 'ThreadMetadata'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const NodeScalarFieldEnum = {
  node_id: 'node_id',
  type: 'type',
  properties: 'properties',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type NodeScalarFieldEnum = (typeof NodeScalarFieldEnum)[keyof typeof NodeScalarFieldEnum]


export const EdgeScalarFieldEnum = {
  node_id: 'node_id',
  source_id: 'source_id',
  target_id: 'target_id',
  type: 'type',
  properties: 'properties',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type EdgeScalarFieldEnum = (typeof EdgeScalarFieldEnum)[keyof typeof EdgeScalarFieldEnum]


export const AssetScalarFieldEnum = {
  asset_id: 'asset_id',
  node_id: 'node_id',
  url: 'url',
  mime_type: 'mime_type',
  name: 'name',
  description: 'description',
  nsfw: 'nsfw',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type AssetScalarFieldEnum = (typeof AssetScalarFieldEnum)[keyof typeof AssetScalarFieldEnum]


export const AgentScalarFieldEnum = {
  agent_id: 'agent_id',
  name: 'name',
  description: 'description',
  version: 'version',
  system_prompt: 'system_prompt',
  auto_start: 'auto_start',
  created_at: 'created_at',
  updated_at: 'updated_at',
  engine: 'engine',
  model: 'model'
} as const

export type AgentScalarFieldEnum = (typeof AgentScalarFieldEnum)[keyof typeof AgentScalarFieldEnum]


export const McpServerScalarFieldEnum = {
  server_id: 'server_id',
  config_id: 'config_id'
} as const

export type McpServerScalarFieldEnum = (typeof McpServerScalarFieldEnum)[keyof typeof McpServerScalarFieldEnum]


export const ToolScalarFieldEnum = {
  tool_id: 'tool_id',
  id: 'id',
  name: 'name',
  description: 'description',
  source: 'source',
  mcp_server_id: 'mcp_server_id',
  locked_tier: 'locked_tier',
  input_schema: 'input_schema',
  output_schema: 'output_schema',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ToolScalarFieldEnum = (typeof ToolScalarFieldEnum)[keyof typeof ToolScalarFieldEnum]


export const AgentToolScalarFieldEnum = {
  id: 'id',
  agent_id: 'agent_id',
  tool_id: 'tool_id',
  tier: 'tier',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type AgentToolScalarFieldEnum = (typeof AgentToolScalarFieldEnum)[keyof typeof AgentToolScalarFieldEnum]


export const AgentActionScalarFieldEnum = {
  action_id: 'action_id',
  id: 'id',
  agent_id: 'agent_id',
  thread_id: 'thread_id',
  user_turn_checkpoint_id: 'user_turn_checkpoint_id',
  description: 'description',
  action: 'action',
  action_hash: 'action_hash',
  status: 'status',
  justification: 'justification',
  auto_approved: 'auto_approved',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type AgentActionScalarFieldEnum = (typeof AgentActionScalarFieldEnum)[keyof typeof AgentActionScalarFieldEnum]


export const CheckpointsScalarFieldEnum = {
  thread_id: 'thread_id',
  checkpoint_ns: 'checkpoint_ns',
  checkpoint_id: 'checkpoint_id',
  parent_checkpoint_id: 'parent_checkpoint_id',
  type: 'type',
  checkpoint: 'checkpoint',
  metadata: 'metadata'
} as const

export type CheckpointsScalarFieldEnum = (typeof CheckpointsScalarFieldEnum)[keyof typeof CheckpointsScalarFieldEnum]


export const WritesScalarFieldEnum = {
  thread_id: 'thread_id',
  checkpoint_ns: 'checkpoint_ns',
  checkpoint_id: 'checkpoint_id',
  task_id: 'task_id',
  idx: 'idx',
  channel: 'channel',
  type: 'type',
  value: 'value'
} as const

export type WritesScalarFieldEnum = (typeof WritesScalarFieldEnum)[keyof typeof WritesScalarFieldEnum]


export const ThreadMetadataScalarFieldEnum = {
  thread_id: 'thread_id',
  agent_id: 'agent_id',
  type: 'type',
  title: 'title',
  archived: 'archived',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ThreadMetadataScalarFieldEnum = (typeof ThreadMetadataScalarFieldEnum)[keyof typeof ThreadMetadataScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

