
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Agent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Agent
 * 
 */
export type AgentModel = runtime.Types.Result.DefaultSelection<Prisma.$AgentPayload>

export type AggregateAgent = {
  _count: AgentCountAggregateOutputType | null
  _avg: AgentAvgAggregateOutputType | null
  _sum: AgentSumAggregateOutputType | null
  _min: AgentMinAggregateOutputType | null
  _max: AgentMaxAggregateOutputType | null
}

export type AgentAvgAggregateOutputType = {
  agent_id: number | null
  version: number | null
}

export type AgentSumAggregateOutputType = {
  agent_id: number | null
  version: number | null
}

export type AgentMinAggregateOutputType = {
  agent_id: number | null
  name: string | null
  description: string | null
  version: number | null
  system_prompt: string | null
  auto_start: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type AgentMaxAggregateOutputType = {
  agent_id: number | null
  name: string | null
  description: string | null
  version: number | null
  system_prompt: string | null
  auto_start: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type AgentCountAggregateOutputType = {
  agent_id: number
  name: number
  description: number
  version: number
  system_prompt: number
  auto_start: number
  created_at: number
  updated_at: number
  _all: number
}


export type AgentAvgAggregateInputType = {
  agent_id?: true
  version?: true
}

export type AgentSumAggregateInputType = {
  agent_id?: true
  version?: true
}

export type AgentMinAggregateInputType = {
  agent_id?: true
  name?: true
  description?: true
  version?: true
  system_prompt?: true
  auto_start?: true
  created_at?: true
  updated_at?: true
}

export type AgentMaxAggregateInputType = {
  agent_id?: true
  name?: true
  description?: true
  version?: true
  system_prompt?: true
  auto_start?: true
  created_at?: true
  updated_at?: true
}

export type AgentCountAggregateInputType = {
  agent_id?: true
  name?: true
  description?: true
  version?: true
  system_prompt?: true
  auto_start?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type AgentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Agent to aggregate.
   */
  where?: Prisma.AgentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agents to fetch.
   */
  orderBy?: Prisma.AgentOrderByWithRelationInput | Prisma.AgentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Agents
  **/
  _count?: true | AgentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AgentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AgentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgentMaxAggregateInputType
}

export type GetAgentAggregateType<T extends AgentAggregateArgs> = {
      [P in keyof T & keyof AggregateAgent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgent[P]>
    : Prisma.GetScalarType<T[P], AggregateAgent[P]>
}




export type AgentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentWhereInput
  orderBy?: Prisma.AgentOrderByWithAggregationInput | Prisma.AgentOrderByWithAggregationInput[]
  by: Prisma.AgentScalarFieldEnum[] | Prisma.AgentScalarFieldEnum
  having?: Prisma.AgentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgentCountAggregateInputType | true
  _avg?: AgentAvgAggregateInputType
  _sum?: AgentSumAggregateInputType
  _min?: AgentMinAggregateInputType
  _max?: AgentMaxAggregateInputType
}

export type AgentGroupByOutputType = {
  agent_id: number
  name: string
  description: string | null
  version: number
  system_prompt: string
  auto_start: boolean
  created_at: Date
  updated_at: Date
  _count: AgentCountAggregateOutputType | null
  _avg: AgentAvgAggregateOutputType | null
  _sum: AgentSumAggregateOutputType | null
  _min: AgentMinAggregateOutputType | null
  _max: AgentMaxAggregateOutputType | null
}

type GetAgentGroupByPayload<T extends AgentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgentGroupByOutputType[P]>
      }
    >
  >



export type AgentWhereInput = {
  AND?: Prisma.AgentWhereInput | Prisma.AgentWhereInput[]
  OR?: Prisma.AgentWhereInput[]
  NOT?: Prisma.AgentWhereInput | Prisma.AgentWhereInput[]
  agent_id?: Prisma.IntFilter<"Agent"> | number
  name?: Prisma.StringFilter<"Agent"> | string
  description?: Prisma.StringNullableFilter<"Agent"> | string | null
  version?: Prisma.IntFilter<"Agent"> | number
  system_prompt?: Prisma.StringFilter<"Agent"> | string
  auto_start?: Prisma.BoolFilter<"Agent"> | boolean
  created_at?: Prisma.DateTimeFilter<"Agent"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Agent"> | Date | string
}

export type AgentOrderByWithRelationInput = {
  agent_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrder
  system_prompt?: Prisma.SortOrder
  auto_start?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type AgentWhereUniqueInput = Prisma.AtLeast<{
  agent_id?: number
  name_version?: Prisma.AgentNameVersionCompoundUniqueInput
  AND?: Prisma.AgentWhereInput | Prisma.AgentWhereInput[]
  OR?: Prisma.AgentWhereInput[]
  NOT?: Prisma.AgentWhereInput | Prisma.AgentWhereInput[]
  name?: Prisma.StringFilter<"Agent"> | string
  description?: Prisma.StringNullableFilter<"Agent"> | string | null
  version?: Prisma.IntFilter<"Agent"> | number
  system_prompt?: Prisma.StringFilter<"Agent"> | string
  auto_start?: Prisma.BoolFilter<"Agent"> | boolean
  created_at?: Prisma.DateTimeFilter<"Agent"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Agent"> | Date | string
}, "agent_id" | "name_version">

export type AgentOrderByWithAggregationInput = {
  agent_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrder
  system_prompt?: Prisma.SortOrder
  auto_start?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.AgentCountOrderByAggregateInput
  _avg?: Prisma.AgentAvgOrderByAggregateInput
  _max?: Prisma.AgentMaxOrderByAggregateInput
  _min?: Prisma.AgentMinOrderByAggregateInput
  _sum?: Prisma.AgentSumOrderByAggregateInput
}

export type AgentScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgentScalarWhereWithAggregatesInput | Prisma.AgentScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgentScalarWhereWithAggregatesInput | Prisma.AgentScalarWhereWithAggregatesInput[]
  agent_id?: Prisma.IntWithAggregatesFilter<"Agent"> | number
  name?: Prisma.StringWithAggregatesFilter<"Agent"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Agent"> | string | null
  version?: Prisma.IntWithAggregatesFilter<"Agent"> | number
  system_prompt?: Prisma.StringWithAggregatesFilter<"Agent"> | string
  auto_start?: Prisma.BoolWithAggregatesFilter<"Agent"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Agent"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Agent"> | Date | string
}

export type AgentCreateInput = {
  name: string
  description?: string | null
  version?: number
  system_prompt: string
  auto_start?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type AgentUncheckedCreateInput = {
  agent_id?: number
  name: string
  description?: string | null
  version?: number
  system_prompt: string
  auto_start?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type AgentUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.IntFieldUpdateOperationsInput | number
  system_prompt?: Prisma.StringFieldUpdateOperationsInput | string
  auto_start?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentUncheckedUpdateInput = {
  agent_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.IntFieldUpdateOperationsInput | number
  system_prompt?: Prisma.StringFieldUpdateOperationsInput | string
  auto_start?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentCreateManyInput = {
  agent_id?: number
  name: string
  description?: string | null
  version?: number
  system_prompt: string
  auto_start?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type AgentUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.IntFieldUpdateOperationsInput | number
  system_prompt?: Prisma.StringFieldUpdateOperationsInput | string
  auto_start?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentUncheckedUpdateManyInput = {
  agent_id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.IntFieldUpdateOperationsInput | number
  system_prompt?: Prisma.StringFieldUpdateOperationsInput | string
  auto_start?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentNameVersionCompoundUniqueInput = {
  name: string
  version: number
}

export type AgentCountOrderByAggregateInput = {
  agent_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  version?: Prisma.SortOrder
  system_prompt?: Prisma.SortOrder
  auto_start?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type AgentAvgOrderByAggregateInput = {
  agent_id?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type AgentMaxOrderByAggregateInput = {
  agent_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  version?: Prisma.SortOrder
  system_prompt?: Prisma.SortOrder
  auto_start?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type AgentMinOrderByAggregateInput = {
  agent_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  version?: Prisma.SortOrder
  system_prompt?: Prisma.SortOrder
  auto_start?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type AgentSumOrderByAggregateInput = {
  agent_id?: Prisma.SortOrder
  version?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type AgentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  agent_id?: boolean
  name?: boolean
  description?: boolean
  version?: boolean
  system_prompt?: boolean
  auto_start?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["agent"]>

export type AgentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  agent_id?: boolean
  name?: boolean
  description?: boolean
  version?: boolean
  system_prompt?: boolean
  auto_start?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["agent"]>

export type AgentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  agent_id?: boolean
  name?: boolean
  description?: boolean
  version?: boolean
  system_prompt?: boolean
  auto_start?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["agent"]>

export type AgentSelectScalar = {
  agent_id?: boolean
  name?: boolean
  description?: boolean
  version?: boolean
  system_prompt?: boolean
  auto_start?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type AgentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"agent_id" | "name" | "description" | "version" | "system_prompt" | "auto_start" | "created_at" | "updated_at", ExtArgs["result"]["agent"]>

export type $AgentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Agent"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    agent_id: number
    name: string
    description: string | null
    version: number
    system_prompt: string
    auto_start: boolean
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["agent"]>
  composites: {}
}

export type AgentGetPayload<S extends boolean | null | undefined | AgentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgentPayload, S>

export type AgentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgentCountAggregateInputType | true
  }

export interface AgentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Agent'], meta: { name: 'Agent' } }
  /**
   * Find zero or one Agent that matches the filter.
   * @param {AgentFindUniqueArgs} args - Arguments to find a Agent
   * @example
   * // Get one Agent
   * const agent = await prisma.agent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgentFindUniqueArgs>(args: Prisma.SelectSubset<T, AgentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Agent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgentFindUniqueOrThrowArgs} args - Arguments to find a Agent
   * @example
   * // Get one Agent
   * const agent = await prisma.agent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentFindFirstArgs} args - Arguments to find a Agent
   * @example
   * // Get one Agent
   * const agent = await prisma.agent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgentFindFirstArgs>(args?: Prisma.SelectSubset<T, AgentFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentFindFirstOrThrowArgs} args - Arguments to find a Agent
   * @example
   * // Get one Agent
   * const agent = await prisma.agent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Agents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Agents
   * const agents = await prisma.agent.findMany()
   * 
   * // Get first 10 Agents
   * const agents = await prisma.agent.findMany({ take: 10 })
   * 
   * // Only select the `agent_id`
   * const agentWithAgent_idOnly = await prisma.agent.findMany({ select: { agent_id: true } })
   * 
   */
  findMany<T extends AgentFindManyArgs>(args?: Prisma.SelectSubset<T, AgentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Agent.
   * @param {AgentCreateArgs} args - Arguments to create a Agent.
   * @example
   * // Create one Agent
   * const Agent = await prisma.agent.create({
   *   data: {
   *     // ... data to create a Agent
   *   }
   * })
   * 
   */
  create<T extends AgentCreateArgs>(args: Prisma.SelectSubset<T, AgentCreateArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Agents.
   * @param {AgentCreateManyArgs} args - Arguments to create many Agents.
   * @example
   * // Create many Agents
   * const agent = await prisma.agent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgentCreateManyArgs>(args?: Prisma.SelectSubset<T, AgentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Agents and returns the data saved in the database.
   * @param {AgentCreateManyAndReturnArgs} args - Arguments to create many Agents.
   * @example
   * // Create many Agents
   * const agent = await prisma.agent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Agents and only return the `agent_id`
   * const agentWithAgent_idOnly = await prisma.agent.createManyAndReturn({
   *   select: { agent_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Agent.
   * @param {AgentDeleteArgs} args - Arguments to delete one Agent.
   * @example
   * // Delete one Agent
   * const Agent = await prisma.agent.delete({
   *   where: {
   *     // ... filter to delete one Agent
   *   }
   * })
   * 
   */
  delete<T extends AgentDeleteArgs>(args: Prisma.SelectSubset<T, AgentDeleteArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Agent.
   * @param {AgentUpdateArgs} args - Arguments to update one Agent.
   * @example
   * // Update one Agent
   * const agent = await prisma.agent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgentUpdateArgs>(args: Prisma.SelectSubset<T, AgentUpdateArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Agents.
   * @param {AgentDeleteManyArgs} args - Arguments to filter Agents to delete.
   * @example
   * // Delete a few Agents
   * const { count } = await prisma.agent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgentDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Agents
   * const agent = await prisma.agent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgentUpdateManyArgs>(args: Prisma.SelectSubset<T, AgentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agents and returns the data updated in the database.
   * @param {AgentUpdateManyAndReturnArgs} args - Arguments to update many Agents.
   * @example
   * // Update many Agents
   * const agent = await prisma.agent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Agents and only return the `agent_id`
   * const agentWithAgent_idOnly = await prisma.agent.updateManyAndReturn({
   *   select: { agent_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Agent.
   * @param {AgentUpsertArgs} args - Arguments to update or create a Agent.
   * @example
   * // Update or create a Agent
   * const agent = await prisma.agent.upsert({
   *   create: {
   *     // ... data to create a Agent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Agent we want to update
   *   }
   * })
   */
  upsert<T extends AgentUpsertArgs>(args: Prisma.SelectSubset<T, AgentUpsertArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Agents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentCountArgs} args - Arguments to filter Agents to count.
   * @example
   * // Count the number of Agents
   * const count = await prisma.agent.count({
   *   where: {
   *     // ... the filter for the Agents we want to count
   *   }
   * })
  **/
  count<T extends AgentCountArgs>(
    args?: Prisma.Subset<T, AgentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Agent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgentAggregateArgs>(args: Prisma.Subset<T, AgentAggregateArgs>): Prisma.PrismaPromise<GetAgentAggregateType<T>>

  /**
   * Group by Agent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgentGroupByArgs['orderBy'] }
      : { orderBy?: AgentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Agent model
 */
readonly fields: AgentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Agent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Agent model
 */
export interface AgentFieldRefs {
  readonly agent_id: Prisma.FieldRef<"Agent", 'Int'>
  readonly name: Prisma.FieldRef<"Agent", 'String'>
  readonly description: Prisma.FieldRef<"Agent", 'String'>
  readonly version: Prisma.FieldRef<"Agent", 'Int'>
  readonly system_prompt: Prisma.FieldRef<"Agent", 'String'>
  readonly auto_start: Prisma.FieldRef<"Agent", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"Agent", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Agent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Agent findUnique
 */
export type AgentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * Filter, which Agent to fetch.
   */
  where: Prisma.AgentWhereUniqueInput
}

/**
 * Agent findUniqueOrThrow
 */
export type AgentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * Filter, which Agent to fetch.
   */
  where: Prisma.AgentWhereUniqueInput
}

/**
 * Agent findFirst
 */
export type AgentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * Filter, which Agent to fetch.
   */
  where?: Prisma.AgentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agents to fetch.
   */
  orderBy?: Prisma.AgentOrderByWithRelationInput | Prisma.AgentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Agents.
   */
  cursor?: Prisma.AgentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agents.
   */
  distinct?: Prisma.AgentScalarFieldEnum | Prisma.AgentScalarFieldEnum[]
}

/**
 * Agent findFirstOrThrow
 */
export type AgentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * Filter, which Agent to fetch.
   */
  where?: Prisma.AgentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agents to fetch.
   */
  orderBy?: Prisma.AgentOrderByWithRelationInput | Prisma.AgentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Agents.
   */
  cursor?: Prisma.AgentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Agents.
   */
  distinct?: Prisma.AgentScalarFieldEnum | Prisma.AgentScalarFieldEnum[]
}

/**
 * Agent findMany
 */
export type AgentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * Filter, which Agents to fetch.
   */
  where?: Prisma.AgentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Agents to fetch.
   */
  orderBy?: Prisma.AgentOrderByWithRelationInput | Prisma.AgentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Agents.
   */
  cursor?: Prisma.AgentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Agents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Agents.
   */
  skip?: number
  distinct?: Prisma.AgentScalarFieldEnum | Prisma.AgentScalarFieldEnum[]
}

/**
 * Agent create
 */
export type AgentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * The data needed to create a Agent.
   */
  data: Prisma.XOR<Prisma.AgentCreateInput, Prisma.AgentUncheckedCreateInput>
}

/**
 * Agent createMany
 */
export type AgentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Agents.
   */
  data: Prisma.AgentCreateManyInput | Prisma.AgentCreateManyInput[]
}

/**
 * Agent createManyAndReturn
 */
export type AgentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * The data used to create many Agents.
   */
  data: Prisma.AgentCreateManyInput | Prisma.AgentCreateManyInput[]
}

/**
 * Agent update
 */
export type AgentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * The data needed to update a Agent.
   */
  data: Prisma.XOR<Prisma.AgentUpdateInput, Prisma.AgentUncheckedUpdateInput>
  /**
   * Choose, which Agent to update.
   */
  where: Prisma.AgentWhereUniqueInput
}

/**
 * Agent updateMany
 */
export type AgentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Agents.
   */
  data: Prisma.XOR<Prisma.AgentUpdateManyMutationInput, Prisma.AgentUncheckedUpdateManyInput>
  /**
   * Filter which Agents to update
   */
  where?: Prisma.AgentWhereInput
  /**
   * Limit how many Agents to update.
   */
  limit?: number
}

/**
 * Agent updateManyAndReturn
 */
export type AgentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * The data used to update Agents.
   */
  data: Prisma.XOR<Prisma.AgentUpdateManyMutationInput, Prisma.AgentUncheckedUpdateManyInput>
  /**
   * Filter which Agents to update
   */
  where?: Prisma.AgentWhereInput
  /**
   * Limit how many Agents to update.
   */
  limit?: number
}

/**
 * Agent upsert
 */
export type AgentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * The filter to search for the Agent to update in case it exists.
   */
  where: Prisma.AgentWhereUniqueInput
  /**
   * In case the Agent found by the `where` argument doesn't exist, create a new Agent with this data.
   */
  create: Prisma.XOR<Prisma.AgentCreateInput, Prisma.AgentUncheckedCreateInput>
  /**
   * In case the Agent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgentUpdateInput, Prisma.AgentUncheckedUpdateInput>
}

/**
 * Agent delete
 */
export type AgentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * Filter which Agent to delete.
   */
  where: Prisma.AgentWhereUniqueInput
}

/**
 * Agent deleteMany
 */
export type AgentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Agents to delete
   */
  where?: Prisma.AgentWhereInput
  /**
   * Limit how many Agents to delete.
   */
  limit?: number
}

/**
 * Agent without action
 */
export type AgentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
}
