
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Asset` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Asset
 * 
 */
export type AssetModel = runtime.Types.Result.DefaultSelection<Prisma.$AssetPayload>

export type AggregateAsset = {
  _count: AssetCountAggregateOutputType | null
  _avg: AssetAvgAggregateOutputType | null
  _sum: AssetSumAggregateOutputType | null
  _min: AssetMinAggregateOutputType | null
  _max: AssetMaxAggregateOutputType | null
}

export type AssetAvgAggregateOutputType = {
  asset_id: number | null
  node_id: number | null
}

export type AssetSumAggregateOutputType = {
  asset_id: number | null
  node_id: number | null
}

export type AssetMinAggregateOutputType = {
  asset_id: number | null
  node_id: number | null
  url: string | null
  mime_type: string | null
  name: string | null
  description: string | null
  nsfw: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type AssetMaxAggregateOutputType = {
  asset_id: number | null
  node_id: number | null
  url: string | null
  mime_type: string | null
  name: string | null
  description: string | null
  nsfw: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type AssetCountAggregateOutputType = {
  asset_id: number
  node_id: number
  url: number
  mime_type: number
  name: number
  description: number
  nsfw: number
  created_at: number
  updated_at: number
  _all: number
}


export type AssetAvgAggregateInputType = {
  asset_id?: true
  node_id?: true
}

export type AssetSumAggregateInputType = {
  asset_id?: true
  node_id?: true
}

export type AssetMinAggregateInputType = {
  asset_id?: true
  node_id?: true
  url?: true
  mime_type?: true
  name?: true
  description?: true
  nsfw?: true
  created_at?: true
  updated_at?: true
}

export type AssetMaxAggregateInputType = {
  asset_id?: true
  node_id?: true
  url?: true
  mime_type?: true
  name?: true
  description?: true
  nsfw?: true
  created_at?: true
  updated_at?: true
}

export type AssetCountAggregateInputType = {
  asset_id?: true
  node_id?: true
  url?: true
  mime_type?: true
  name?: true
  description?: true
  nsfw?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type AssetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Asset to aggregate.
   */
  where?: Prisma.AssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assets to fetch.
   */
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Assets
  **/
  _count?: true | AssetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AssetAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AssetSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssetMaxAggregateInputType
}

export type GetAssetAggregateType<T extends AssetAggregateArgs> = {
      [P in keyof T & keyof AggregateAsset]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAsset[P]>
    : Prisma.GetScalarType<T[P], AggregateAsset[P]>
}




export type AssetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetWhereInput
  orderBy?: Prisma.AssetOrderByWithAggregationInput | Prisma.AssetOrderByWithAggregationInput[]
  by: Prisma.AssetScalarFieldEnum[] | Prisma.AssetScalarFieldEnum
  having?: Prisma.AssetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssetCountAggregateInputType | true
  _avg?: AssetAvgAggregateInputType
  _sum?: AssetSumAggregateInputType
  _min?: AssetMinAggregateInputType
  _max?: AssetMaxAggregateInputType
}

export type AssetGroupByOutputType = {
  asset_id: number
  node_id: number
  url: string
  mime_type: string | null
  name: string | null
  description: string | null
  nsfw: boolean | null
  created_at: Date
  updated_at: Date
  _count: AssetCountAggregateOutputType | null
  _avg: AssetAvgAggregateOutputType | null
  _sum: AssetSumAggregateOutputType | null
  _min: AssetMinAggregateOutputType | null
  _max: AssetMaxAggregateOutputType | null
}

type GetAssetGroupByPayload<T extends AssetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssetGroupByOutputType[P]>
      }
    >
  >



export type AssetWhereInput = {
  AND?: Prisma.AssetWhereInput | Prisma.AssetWhereInput[]
  OR?: Prisma.AssetWhereInput[]
  NOT?: Prisma.AssetWhereInput | Prisma.AssetWhereInput[]
  asset_id?: Prisma.IntFilter<"Asset"> | number
  node_id?: Prisma.IntFilter<"Asset"> | number
  url?: Prisma.StringFilter<"Asset"> | string
  mime_type?: Prisma.StringNullableFilter<"Asset"> | string | null
  name?: Prisma.StringNullableFilter<"Asset"> | string | null
  description?: Prisma.StringNullableFilter<"Asset"> | string | null
  nsfw?: Prisma.BoolNullableFilter<"Asset"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"Asset"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Asset"> | Date | string
  node?: Prisma.XOR<Prisma.NodeScalarRelationFilter, Prisma.NodeWhereInput>
}

export type AssetOrderByWithRelationInput = {
  asset_id?: Prisma.SortOrder
  node_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mime_type?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  nsfw?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  node?: Prisma.NodeOrderByWithRelationInput
}

export type AssetWhereUniqueInput = Prisma.AtLeast<{
  asset_id?: number
  AND?: Prisma.AssetWhereInput | Prisma.AssetWhereInput[]
  OR?: Prisma.AssetWhereInput[]
  NOT?: Prisma.AssetWhereInput | Prisma.AssetWhereInput[]
  node_id?: Prisma.IntFilter<"Asset"> | number
  url?: Prisma.StringFilter<"Asset"> | string
  mime_type?: Prisma.StringNullableFilter<"Asset"> | string | null
  name?: Prisma.StringNullableFilter<"Asset"> | string | null
  description?: Prisma.StringNullableFilter<"Asset"> | string | null
  nsfw?: Prisma.BoolNullableFilter<"Asset"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"Asset"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Asset"> | Date | string
  node?: Prisma.XOR<Prisma.NodeScalarRelationFilter, Prisma.NodeWhereInput>
}, "asset_id">

export type AssetOrderByWithAggregationInput = {
  asset_id?: Prisma.SortOrder
  node_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mime_type?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  nsfw?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.AssetCountOrderByAggregateInput
  _avg?: Prisma.AssetAvgOrderByAggregateInput
  _max?: Prisma.AssetMaxOrderByAggregateInput
  _min?: Prisma.AssetMinOrderByAggregateInput
  _sum?: Prisma.AssetSumOrderByAggregateInput
}

export type AssetScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssetScalarWhereWithAggregatesInput | Prisma.AssetScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssetScalarWhereWithAggregatesInput | Prisma.AssetScalarWhereWithAggregatesInput[]
  asset_id?: Prisma.IntWithAggregatesFilter<"Asset"> | number
  node_id?: Prisma.IntWithAggregatesFilter<"Asset"> | number
  url?: Prisma.StringWithAggregatesFilter<"Asset"> | string
  mime_type?: Prisma.StringNullableWithAggregatesFilter<"Asset"> | string | null
  name?: Prisma.StringNullableWithAggregatesFilter<"Asset"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Asset"> | string | null
  nsfw?: Prisma.BoolNullableWithAggregatesFilter<"Asset"> | boolean | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Asset"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Asset"> | Date | string
}

export type AssetCreateInput = {
  url: string
  mime_type?: string | null
  name?: string | null
  description?: string | null
  nsfw?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
  node: Prisma.NodeCreateNestedOneWithoutAssetsInput
}

export type AssetUncheckedCreateInput = {
  asset_id?: number
  node_id: number
  url: string
  mime_type?: string | null
  name?: string | null
  description?: string | null
  nsfw?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type AssetUpdateInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nsfw?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  node?: Prisma.NodeUpdateOneRequiredWithoutAssetsNestedInput
}

export type AssetUncheckedUpdateInput = {
  asset_id?: Prisma.IntFieldUpdateOperationsInput | number
  node_id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nsfw?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetCreateManyInput = {
  asset_id?: number
  node_id: number
  url: string
  mime_type?: string | null
  name?: string | null
  description?: string | null
  nsfw?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type AssetUpdateManyMutationInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nsfw?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetUncheckedUpdateManyInput = {
  asset_id?: Prisma.IntFieldUpdateOperationsInput | number
  node_id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nsfw?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetListRelationFilter = {
  every?: Prisma.AssetWhereInput
  some?: Prisma.AssetWhereInput
  none?: Prisma.AssetWhereInput
}

export type AssetOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssetCountOrderByAggregateInput = {
  asset_id?: Prisma.SortOrder
  node_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mime_type?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  nsfw?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type AssetAvgOrderByAggregateInput = {
  asset_id?: Prisma.SortOrder
  node_id?: Prisma.SortOrder
}

export type AssetMaxOrderByAggregateInput = {
  asset_id?: Prisma.SortOrder
  node_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mime_type?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  nsfw?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type AssetMinOrderByAggregateInput = {
  asset_id?: Prisma.SortOrder
  node_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  mime_type?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  nsfw?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type AssetSumOrderByAggregateInput = {
  asset_id?: Prisma.SortOrder
  node_id?: Prisma.SortOrder
}

export type AssetCreateNestedManyWithoutNodeInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutNodeInput, Prisma.AssetUncheckedCreateWithoutNodeInput> | Prisma.AssetCreateWithoutNodeInput[] | Prisma.AssetUncheckedCreateWithoutNodeInput[]
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutNodeInput | Prisma.AssetCreateOrConnectWithoutNodeInput[]
  createMany?: Prisma.AssetCreateManyNodeInputEnvelope
  connect?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
}

export type AssetUncheckedCreateNestedManyWithoutNodeInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutNodeInput, Prisma.AssetUncheckedCreateWithoutNodeInput> | Prisma.AssetCreateWithoutNodeInput[] | Prisma.AssetUncheckedCreateWithoutNodeInput[]
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutNodeInput | Prisma.AssetCreateOrConnectWithoutNodeInput[]
  createMany?: Prisma.AssetCreateManyNodeInputEnvelope
  connect?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
}

export type AssetUpdateManyWithoutNodeNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutNodeInput, Prisma.AssetUncheckedCreateWithoutNodeInput> | Prisma.AssetCreateWithoutNodeInput[] | Prisma.AssetUncheckedCreateWithoutNodeInput[]
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutNodeInput | Prisma.AssetCreateOrConnectWithoutNodeInput[]
  upsert?: Prisma.AssetUpsertWithWhereUniqueWithoutNodeInput | Prisma.AssetUpsertWithWhereUniqueWithoutNodeInput[]
  createMany?: Prisma.AssetCreateManyNodeInputEnvelope
  set?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
  disconnect?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
  delete?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
  connect?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
  update?: Prisma.AssetUpdateWithWhereUniqueWithoutNodeInput | Prisma.AssetUpdateWithWhereUniqueWithoutNodeInput[]
  updateMany?: Prisma.AssetUpdateManyWithWhereWithoutNodeInput | Prisma.AssetUpdateManyWithWhereWithoutNodeInput[]
  deleteMany?: Prisma.AssetScalarWhereInput | Prisma.AssetScalarWhereInput[]
}

export type AssetUncheckedUpdateManyWithoutNodeNestedInput = {
  create?: Prisma.XOR<Prisma.AssetCreateWithoutNodeInput, Prisma.AssetUncheckedCreateWithoutNodeInput> | Prisma.AssetCreateWithoutNodeInput[] | Prisma.AssetUncheckedCreateWithoutNodeInput[]
  connectOrCreate?: Prisma.AssetCreateOrConnectWithoutNodeInput | Prisma.AssetCreateOrConnectWithoutNodeInput[]
  upsert?: Prisma.AssetUpsertWithWhereUniqueWithoutNodeInput | Prisma.AssetUpsertWithWhereUniqueWithoutNodeInput[]
  createMany?: Prisma.AssetCreateManyNodeInputEnvelope
  set?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
  disconnect?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
  delete?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
  connect?: Prisma.AssetWhereUniqueInput | Prisma.AssetWhereUniqueInput[]
  update?: Prisma.AssetUpdateWithWhereUniqueWithoutNodeInput | Prisma.AssetUpdateWithWhereUniqueWithoutNodeInput[]
  updateMany?: Prisma.AssetUpdateManyWithWhereWithoutNodeInput | Prisma.AssetUpdateManyWithWhereWithoutNodeInput[]
  deleteMany?: Prisma.AssetScalarWhereInput | Prisma.AssetScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type AssetCreateWithoutNodeInput = {
  url: string
  mime_type?: string | null
  name?: string | null
  description?: string | null
  nsfw?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type AssetUncheckedCreateWithoutNodeInput = {
  asset_id?: number
  url: string
  mime_type?: string | null
  name?: string | null
  description?: string | null
  nsfw?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type AssetCreateOrConnectWithoutNodeInput = {
  where: Prisma.AssetWhereUniqueInput
  create: Prisma.XOR<Prisma.AssetCreateWithoutNodeInput, Prisma.AssetUncheckedCreateWithoutNodeInput>
}

export type AssetCreateManyNodeInputEnvelope = {
  data: Prisma.AssetCreateManyNodeInput | Prisma.AssetCreateManyNodeInput[]
}

export type AssetUpsertWithWhereUniqueWithoutNodeInput = {
  where: Prisma.AssetWhereUniqueInput
  update: Prisma.XOR<Prisma.AssetUpdateWithoutNodeInput, Prisma.AssetUncheckedUpdateWithoutNodeInput>
  create: Prisma.XOR<Prisma.AssetCreateWithoutNodeInput, Prisma.AssetUncheckedCreateWithoutNodeInput>
}

export type AssetUpdateWithWhereUniqueWithoutNodeInput = {
  where: Prisma.AssetWhereUniqueInput
  data: Prisma.XOR<Prisma.AssetUpdateWithoutNodeInput, Prisma.AssetUncheckedUpdateWithoutNodeInput>
}

export type AssetUpdateManyWithWhereWithoutNodeInput = {
  where: Prisma.AssetScalarWhereInput
  data: Prisma.XOR<Prisma.AssetUpdateManyMutationInput, Prisma.AssetUncheckedUpdateManyWithoutNodeInput>
}

export type AssetScalarWhereInput = {
  AND?: Prisma.AssetScalarWhereInput | Prisma.AssetScalarWhereInput[]
  OR?: Prisma.AssetScalarWhereInput[]
  NOT?: Prisma.AssetScalarWhereInput | Prisma.AssetScalarWhereInput[]
  asset_id?: Prisma.IntFilter<"Asset"> | number
  node_id?: Prisma.IntFilter<"Asset"> | number
  url?: Prisma.StringFilter<"Asset"> | string
  mime_type?: Prisma.StringNullableFilter<"Asset"> | string | null
  name?: Prisma.StringNullableFilter<"Asset"> | string | null
  description?: Prisma.StringNullableFilter<"Asset"> | string | null
  nsfw?: Prisma.BoolNullableFilter<"Asset"> | boolean | null
  created_at?: Prisma.DateTimeFilter<"Asset"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Asset"> | Date | string
}

export type AssetCreateManyNodeInput = {
  asset_id?: number
  url: string
  mime_type?: string | null
  name?: string | null
  description?: string | null
  nsfw?: boolean | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type AssetUpdateWithoutNodeInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nsfw?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetUncheckedUpdateWithoutNodeInput = {
  asset_id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nsfw?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssetUncheckedUpdateManyWithoutNodeInput = {
  asset_id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  mime_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  nsfw?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AssetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  asset_id?: boolean
  node_id?: boolean
  url?: boolean
  mime_type?: boolean
  name?: boolean
  description?: boolean
  nsfw?: boolean
  created_at?: boolean
  updated_at?: boolean
  node?: boolean | Prisma.NodeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["asset"]>

export type AssetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  asset_id?: boolean
  node_id?: boolean
  url?: boolean
  mime_type?: boolean
  name?: boolean
  description?: boolean
  nsfw?: boolean
  created_at?: boolean
  updated_at?: boolean
  node?: boolean | Prisma.NodeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["asset"]>

export type AssetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  asset_id?: boolean
  node_id?: boolean
  url?: boolean
  mime_type?: boolean
  name?: boolean
  description?: boolean
  nsfw?: boolean
  created_at?: boolean
  updated_at?: boolean
  node?: boolean | Prisma.NodeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["asset"]>

export type AssetSelectScalar = {
  asset_id?: boolean
  node_id?: boolean
  url?: boolean
  mime_type?: boolean
  name?: boolean
  description?: boolean
  nsfw?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type AssetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"asset_id" | "node_id" | "url" | "mime_type" | "name" | "description" | "nsfw" | "created_at" | "updated_at", ExtArgs["result"]["asset"]>
export type AssetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  node?: boolean | Prisma.NodeDefaultArgs<ExtArgs>
}
export type AssetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  node?: boolean | Prisma.NodeDefaultArgs<ExtArgs>
}
export type AssetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  node?: boolean | Prisma.NodeDefaultArgs<ExtArgs>
}

export type $AssetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Asset"
  objects: {
    node: Prisma.$NodePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    asset_id: number
    node_id: number
    url: string
    mime_type: string | null
    name: string | null
    description: string | null
    nsfw: boolean | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["asset"]>
  composites: {}
}

export type AssetGetPayload<S extends boolean | null | undefined | AssetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssetPayload, S>

export type AssetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssetCountAggregateInputType | true
  }

export interface AssetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Asset'], meta: { name: 'Asset' } }
  /**
   * Find zero or one Asset that matches the filter.
   * @param {AssetFindUniqueArgs} args - Arguments to find a Asset
   * @example
   * // Get one Asset
   * const asset = await prisma.asset.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssetFindUniqueArgs>(args: Prisma.SelectSubset<T, AssetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Asset that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssetFindUniqueOrThrowArgs} args - Arguments to find a Asset
   * @example
   * // Get one Asset
   * const asset = await prisma.asset.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Asset that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetFindFirstArgs} args - Arguments to find a Asset
   * @example
   * // Get one Asset
   * const asset = await prisma.asset.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssetFindFirstArgs>(args?: Prisma.SelectSubset<T, AssetFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Asset that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetFindFirstOrThrowArgs} args - Arguments to find a Asset
   * @example
   * // Get one Asset
   * const asset = await prisma.asset.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Assets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Assets
   * const assets = await prisma.asset.findMany()
   * 
   * // Get first 10 Assets
   * const assets = await prisma.asset.findMany({ take: 10 })
   * 
   * // Only select the `asset_id`
   * const assetWithAsset_idOnly = await prisma.asset.findMany({ select: { asset_id: true } })
   * 
   */
  findMany<T extends AssetFindManyArgs>(args?: Prisma.SelectSubset<T, AssetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Asset.
   * @param {AssetCreateArgs} args - Arguments to create a Asset.
   * @example
   * // Create one Asset
   * const Asset = await prisma.asset.create({
   *   data: {
   *     // ... data to create a Asset
   *   }
   * })
   * 
   */
  create<T extends AssetCreateArgs>(args: Prisma.SelectSubset<T, AssetCreateArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Assets.
   * @param {AssetCreateManyArgs} args - Arguments to create many Assets.
   * @example
   * // Create many Assets
   * const asset = await prisma.asset.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssetCreateManyArgs>(args?: Prisma.SelectSubset<T, AssetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Assets and returns the data saved in the database.
   * @param {AssetCreateManyAndReturnArgs} args - Arguments to create many Assets.
   * @example
   * // Create many Assets
   * const asset = await prisma.asset.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Assets and only return the `asset_id`
   * const assetWithAsset_idOnly = await prisma.asset.createManyAndReturn({
   *   select: { asset_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Asset.
   * @param {AssetDeleteArgs} args - Arguments to delete one Asset.
   * @example
   * // Delete one Asset
   * const Asset = await prisma.asset.delete({
   *   where: {
   *     // ... filter to delete one Asset
   *   }
   * })
   * 
   */
  delete<T extends AssetDeleteArgs>(args: Prisma.SelectSubset<T, AssetDeleteArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Asset.
   * @param {AssetUpdateArgs} args - Arguments to update one Asset.
   * @example
   * // Update one Asset
   * const asset = await prisma.asset.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssetUpdateArgs>(args: Prisma.SelectSubset<T, AssetUpdateArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Assets.
   * @param {AssetDeleteManyArgs} args - Arguments to filter Assets to delete.
   * @example
   * // Delete a few Assets
   * const { count } = await prisma.asset.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssetDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Assets
   * const asset = await prisma.asset.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssetUpdateManyArgs>(args: Prisma.SelectSubset<T, AssetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assets and returns the data updated in the database.
   * @param {AssetUpdateManyAndReturnArgs} args - Arguments to update many Assets.
   * @example
   * // Update many Assets
   * const asset = await prisma.asset.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Assets and only return the `asset_id`
   * const assetWithAsset_idOnly = await prisma.asset.updateManyAndReturn({
   *   select: { asset_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Asset.
   * @param {AssetUpsertArgs} args - Arguments to update or create a Asset.
   * @example
   * // Update or create a Asset
   * const asset = await prisma.asset.upsert({
   *   create: {
   *     // ... data to create a Asset
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Asset we want to update
   *   }
   * })
   */
  upsert<T extends AssetUpsertArgs>(args: Prisma.SelectSubset<T, AssetUpsertArgs<ExtArgs>>): Prisma.Prisma__AssetClient<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Assets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetCountArgs} args - Arguments to filter Assets to count.
   * @example
   * // Count the number of Assets
   * const count = await prisma.asset.count({
   *   where: {
   *     // ... the filter for the Assets we want to count
   *   }
   * })
  **/
  count<T extends AssetCountArgs>(
    args?: Prisma.Subset<T, AssetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Asset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssetAggregateArgs>(args: Prisma.Subset<T, AssetAggregateArgs>): Prisma.PrismaPromise<GetAssetAggregateType<T>>

  /**
   * Group by Asset.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssetGroupByArgs['orderBy'] }
      : { orderBy?: AssetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Asset model
 */
readonly fields: AssetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Asset.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  node<T extends Prisma.NodeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NodeDefaultArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Asset model
 */
export interface AssetFieldRefs {
  readonly asset_id: Prisma.FieldRef<"Asset", 'Int'>
  readonly node_id: Prisma.FieldRef<"Asset", 'Int'>
  readonly url: Prisma.FieldRef<"Asset", 'String'>
  readonly mime_type: Prisma.FieldRef<"Asset", 'String'>
  readonly name: Prisma.FieldRef<"Asset", 'String'>
  readonly description: Prisma.FieldRef<"Asset", 'String'>
  readonly nsfw: Prisma.FieldRef<"Asset", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"Asset", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Asset", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Asset findUnique
 */
export type AssetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Asset to fetch.
   */
  where: Prisma.AssetWhereUniqueInput
}

/**
 * Asset findUniqueOrThrow
 */
export type AssetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Asset to fetch.
   */
  where: Prisma.AssetWhereUniqueInput
}

/**
 * Asset findFirst
 */
export type AssetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Asset to fetch.
   */
  where?: Prisma.AssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assets to fetch.
   */
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assets.
   */
  cursor?: Prisma.AssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assets.
   */
  distinct?: Prisma.AssetScalarFieldEnum | Prisma.AssetScalarFieldEnum[]
}

/**
 * Asset findFirstOrThrow
 */
export type AssetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Asset to fetch.
   */
  where?: Prisma.AssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assets to fetch.
   */
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assets.
   */
  cursor?: Prisma.AssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assets.
   */
  distinct?: Prisma.AssetScalarFieldEnum | Prisma.AssetScalarFieldEnum[]
}

/**
 * Asset findMany
 */
export type AssetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter, which Assets to fetch.
   */
  where?: Prisma.AssetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assets to fetch.
   */
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Assets.
   */
  cursor?: Prisma.AssetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assets.
   */
  skip?: number
  distinct?: Prisma.AssetScalarFieldEnum | Prisma.AssetScalarFieldEnum[]
}

/**
 * Asset create
 */
export type AssetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * The data needed to create a Asset.
   */
  data: Prisma.XOR<Prisma.AssetCreateInput, Prisma.AssetUncheckedCreateInput>
}

/**
 * Asset createMany
 */
export type AssetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Assets.
   */
  data: Prisma.AssetCreateManyInput | Prisma.AssetCreateManyInput[]
}

/**
 * Asset createManyAndReturn
 */
export type AssetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * The data used to create many Assets.
   */
  data: Prisma.AssetCreateManyInput | Prisma.AssetCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Asset update
 */
export type AssetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * The data needed to update a Asset.
   */
  data: Prisma.XOR<Prisma.AssetUpdateInput, Prisma.AssetUncheckedUpdateInput>
  /**
   * Choose, which Asset to update.
   */
  where: Prisma.AssetWhereUniqueInput
}

/**
 * Asset updateMany
 */
export type AssetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Assets.
   */
  data: Prisma.XOR<Prisma.AssetUpdateManyMutationInput, Prisma.AssetUncheckedUpdateManyInput>
  /**
   * Filter which Assets to update
   */
  where?: Prisma.AssetWhereInput
  /**
   * Limit how many Assets to update.
   */
  limit?: number
}

/**
 * Asset updateManyAndReturn
 */
export type AssetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * The data used to update Assets.
   */
  data: Prisma.XOR<Prisma.AssetUpdateManyMutationInput, Prisma.AssetUncheckedUpdateManyInput>
  /**
   * Filter which Assets to update
   */
  where?: Prisma.AssetWhereInput
  /**
   * Limit how many Assets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Asset upsert
 */
export type AssetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * The filter to search for the Asset to update in case it exists.
   */
  where: Prisma.AssetWhereUniqueInput
  /**
   * In case the Asset found by the `where` argument doesn't exist, create a new Asset with this data.
   */
  create: Prisma.XOR<Prisma.AssetCreateInput, Prisma.AssetUncheckedCreateInput>
  /**
   * In case the Asset was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssetUpdateInput, Prisma.AssetUncheckedUpdateInput>
}

/**
 * Asset delete
 */
export type AssetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  /**
   * Filter which Asset to delete.
   */
  where: Prisma.AssetWhereUniqueInput
}

/**
 * Asset deleteMany
 */
export type AssetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Assets to delete
   */
  where?: Prisma.AssetWhereInput
  /**
   * Limit how many Assets to delete.
   */
  limit?: number
}

/**
 * Asset without action
 */
export type AssetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
}
