
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EvaluationResults` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EvaluationResults
 * 
 */
export type EvaluationResultsModel = runtime.Types.Result.DefaultSelection<Prisma.$EvaluationResultsPayload>

export type AggregateEvaluationResults = {
  _count: EvaluationResultsCountAggregateOutputType | null
  _avg: EvaluationResultsAvgAggregateOutputType | null
  _sum: EvaluationResultsSumAggregateOutputType | null
  _min: EvaluationResultsMinAggregateOutputType | null
  _max: EvaluationResultsMaxAggregateOutputType | null
}

export type EvaluationResultsAvgAggregateOutputType = {
  evaluation_result_id: number | null
  evaluation_id: number | null
}

export type EvaluationResultsSumAggregateOutputType = {
  evaluation_result_id: number | null
  evaluation_id: number | null
}

export type EvaluationResultsMinAggregateOutputType = {
  evaluation_result_id: number | null
  evaluation_id: number | null
  status: string | null
  created_at: Date | null
  updated_at: Date | null
  completed_at: Date | null
}

export type EvaluationResultsMaxAggregateOutputType = {
  evaluation_result_id: number | null
  evaluation_id: number | null
  status: string | null
  created_at: Date | null
  updated_at: Date | null
  completed_at: Date | null
}

export type EvaluationResultsCountAggregateOutputType = {
  evaluation_result_id: number
  evaluation_id: number
  status: number
  results: number
  created_at: number
  updated_at: number
  completed_at: number
  _all: number
}


export type EvaluationResultsAvgAggregateInputType = {
  evaluation_result_id?: true
  evaluation_id?: true
}

export type EvaluationResultsSumAggregateInputType = {
  evaluation_result_id?: true
  evaluation_id?: true
}

export type EvaluationResultsMinAggregateInputType = {
  evaluation_result_id?: true
  evaluation_id?: true
  status?: true
  created_at?: true
  updated_at?: true
  completed_at?: true
}

export type EvaluationResultsMaxAggregateInputType = {
  evaluation_result_id?: true
  evaluation_id?: true
  status?: true
  created_at?: true
  updated_at?: true
  completed_at?: true
}

export type EvaluationResultsCountAggregateInputType = {
  evaluation_result_id?: true
  evaluation_id?: true
  status?: true
  results?: true
  created_at?: true
  updated_at?: true
  completed_at?: true
  _all?: true
}

export type EvaluationResultsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EvaluationResults to aggregate.
   */
  where?: Prisma.EvaluationResultsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EvaluationResults to fetch.
   */
  orderBy?: Prisma.EvaluationResultsOrderByWithRelationInput | Prisma.EvaluationResultsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EvaluationResultsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EvaluationResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EvaluationResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EvaluationResults
  **/
  _count?: true | EvaluationResultsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EvaluationResultsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EvaluationResultsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EvaluationResultsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EvaluationResultsMaxAggregateInputType
}

export type GetEvaluationResultsAggregateType<T extends EvaluationResultsAggregateArgs> = {
      [P in keyof T & keyof AggregateEvaluationResults]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEvaluationResults[P]>
    : Prisma.GetScalarType<T[P], AggregateEvaluationResults[P]>
}




export type EvaluationResultsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EvaluationResultsWhereInput
  orderBy?: Prisma.EvaluationResultsOrderByWithAggregationInput | Prisma.EvaluationResultsOrderByWithAggregationInput[]
  by: Prisma.EvaluationResultsScalarFieldEnum[] | Prisma.EvaluationResultsScalarFieldEnum
  having?: Prisma.EvaluationResultsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EvaluationResultsCountAggregateInputType | true
  _avg?: EvaluationResultsAvgAggregateInputType
  _sum?: EvaluationResultsSumAggregateInputType
  _min?: EvaluationResultsMinAggregateInputType
  _max?: EvaluationResultsMaxAggregateInputType
}

export type EvaluationResultsGroupByOutputType = {
  evaluation_result_id: number
  evaluation_id: number
  status: string
  results: runtime.JsonValue
  created_at: Date
  updated_at: Date
  completed_at: Date | null
  _count: EvaluationResultsCountAggregateOutputType | null
  _avg: EvaluationResultsAvgAggregateOutputType | null
  _sum: EvaluationResultsSumAggregateOutputType | null
  _min: EvaluationResultsMinAggregateOutputType | null
  _max: EvaluationResultsMaxAggregateOutputType | null
}

type GetEvaluationResultsGroupByPayload<T extends EvaluationResultsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EvaluationResultsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EvaluationResultsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EvaluationResultsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EvaluationResultsGroupByOutputType[P]>
      }
    >
  >



export type EvaluationResultsWhereInput = {
  AND?: Prisma.EvaluationResultsWhereInput | Prisma.EvaluationResultsWhereInput[]
  OR?: Prisma.EvaluationResultsWhereInput[]
  NOT?: Prisma.EvaluationResultsWhereInput | Prisma.EvaluationResultsWhereInput[]
  evaluation_result_id?: Prisma.IntFilter<"EvaluationResults"> | number
  evaluation_id?: Prisma.IntFilter<"EvaluationResults"> | number
  status?: Prisma.StringFilter<"EvaluationResults"> | string
  results?: Prisma.JsonFilter<"EvaluationResults">
  created_at?: Prisma.DateTimeFilter<"EvaluationResults"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"EvaluationResults"> | Date | string
  completed_at?: Prisma.DateTimeNullableFilter<"EvaluationResults"> | Date | string | null
  evaluation?: Prisma.XOR<Prisma.EvaluationScalarRelationFilter, Prisma.EvaluationWhereInput>
}

export type EvaluationResultsOrderByWithRelationInput = {
  evaluation_result_id?: Prisma.SortOrder
  evaluation_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  results?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  completed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  evaluation?: Prisma.EvaluationOrderByWithRelationInput
}

export type EvaluationResultsWhereUniqueInput = Prisma.AtLeast<{
  evaluation_result_id?: number
  AND?: Prisma.EvaluationResultsWhereInput | Prisma.EvaluationResultsWhereInput[]
  OR?: Prisma.EvaluationResultsWhereInput[]
  NOT?: Prisma.EvaluationResultsWhereInput | Prisma.EvaluationResultsWhereInput[]
  evaluation_id?: Prisma.IntFilter<"EvaluationResults"> | number
  status?: Prisma.StringFilter<"EvaluationResults"> | string
  results?: Prisma.JsonFilter<"EvaluationResults">
  created_at?: Prisma.DateTimeFilter<"EvaluationResults"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"EvaluationResults"> | Date | string
  completed_at?: Prisma.DateTimeNullableFilter<"EvaluationResults"> | Date | string | null
  evaluation?: Prisma.XOR<Prisma.EvaluationScalarRelationFilter, Prisma.EvaluationWhereInput>
}, "evaluation_result_id">

export type EvaluationResultsOrderByWithAggregationInput = {
  evaluation_result_id?: Prisma.SortOrder
  evaluation_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  results?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  completed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EvaluationResultsCountOrderByAggregateInput
  _avg?: Prisma.EvaluationResultsAvgOrderByAggregateInput
  _max?: Prisma.EvaluationResultsMaxOrderByAggregateInput
  _min?: Prisma.EvaluationResultsMinOrderByAggregateInput
  _sum?: Prisma.EvaluationResultsSumOrderByAggregateInput
}

export type EvaluationResultsScalarWhereWithAggregatesInput = {
  AND?: Prisma.EvaluationResultsScalarWhereWithAggregatesInput | Prisma.EvaluationResultsScalarWhereWithAggregatesInput[]
  OR?: Prisma.EvaluationResultsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EvaluationResultsScalarWhereWithAggregatesInput | Prisma.EvaluationResultsScalarWhereWithAggregatesInput[]
  evaluation_result_id?: Prisma.IntWithAggregatesFilter<"EvaluationResults"> | number
  evaluation_id?: Prisma.IntWithAggregatesFilter<"EvaluationResults"> | number
  status?: Prisma.StringWithAggregatesFilter<"EvaluationResults"> | string
  results?: Prisma.JsonWithAggregatesFilter<"EvaluationResults">
  created_at?: Prisma.DateTimeWithAggregatesFilter<"EvaluationResults"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"EvaluationResults"> | Date | string
  completed_at?: Prisma.DateTimeNullableWithAggregatesFilter<"EvaluationResults"> | Date | string | null
}

export type EvaluationResultsCreateInput = {
  status?: string
  results: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  completed_at?: Date | string | null
  evaluation: Prisma.EvaluationCreateNestedOneWithoutResultsInput
}

export type EvaluationResultsUncheckedCreateInput = {
  evaluation_result_id?: number
  evaluation_id: number
  status?: string
  results: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  completed_at?: Date | string | null
}

export type EvaluationResultsUpdateInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  results?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  evaluation?: Prisma.EvaluationUpdateOneRequiredWithoutResultsNestedInput
}

export type EvaluationResultsUncheckedUpdateInput = {
  evaluation_result_id?: Prisma.IntFieldUpdateOperationsInput | number
  evaluation_id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  results?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EvaluationResultsCreateManyInput = {
  evaluation_result_id?: number
  evaluation_id: number
  status?: string
  results: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  completed_at?: Date | string | null
}

export type EvaluationResultsUpdateManyMutationInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  results?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EvaluationResultsUncheckedUpdateManyInput = {
  evaluation_result_id?: Prisma.IntFieldUpdateOperationsInput | number
  evaluation_id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  results?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EvaluationResultsListRelationFilter = {
  every?: Prisma.EvaluationResultsWhereInput
  some?: Prisma.EvaluationResultsWhereInput
  none?: Prisma.EvaluationResultsWhereInput
}

export type EvaluationResultsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EvaluationResultsCountOrderByAggregateInput = {
  evaluation_result_id?: Prisma.SortOrder
  evaluation_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  results?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
}

export type EvaluationResultsAvgOrderByAggregateInput = {
  evaluation_result_id?: Prisma.SortOrder
  evaluation_id?: Prisma.SortOrder
}

export type EvaluationResultsMaxOrderByAggregateInput = {
  evaluation_result_id?: Prisma.SortOrder
  evaluation_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
}

export type EvaluationResultsMinOrderByAggregateInput = {
  evaluation_result_id?: Prisma.SortOrder
  evaluation_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
}

export type EvaluationResultsSumOrderByAggregateInput = {
  evaluation_result_id?: Prisma.SortOrder
  evaluation_id?: Prisma.SortOrder
}

export type EvaluationResultsCreateNestedManyWithoutEvaluationInput = {
  create?: Prisma.XOR<Prisma.EvaluationResultsCreateWithoutEvaluationInput, Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput> | Prisma.EvaluationResultsCreateWithoutEvaluationInput[] | Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput[]
  connectOrCreate?: Prisma.EvaluationResultsCreateOrConnectWithoutEvaluationInput | Prisma.EvaluationResultsCreateOrConnectWithoutEvaluationInput[]
  createMany?: Prisma.EvaluationResultsCreateManyEvaluationInputEnvelope
  connect?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
}

export type EvaluationResultsUncheckedCreateNestedManyWithoutEvaluationInput = {
  create?: Prisma.XOR<Prisma.EvaluationResultsCreateWithoutEvaluationInput, Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput> | Prisma.EvaluationResultsCreateWithoutEvaluationInput[] | Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput[]
  connectOrCreate?: Prisma.EvaluationResultsCreateOrConnectWithoutEvaluationInput | Prisma.EvaluationResultsCreateOrConnectWithoutEvaluationInput[]
  createMany?: Prisma.EvaluationResultsCreateManyEvaluationInputEnvelope
  connect?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
}

export type EvaluationResultsUpdateManyWithoutEvaluationNestedInput = {
  create?: Prisma.XOR<Prisma.EvaluationResultsCreateWithoutEvaluationInput, Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput> | Prisma.EvaluationResultsCreateWithoutEvaluationInput[] | Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput[]
  connectOrCreate?: Prisma.EvaluationResultsCreateOrConnectWithoutEvaluationInput | Prisma.EvaluationResultsCreateOrConnectWithoutEvaluationInput[]
  upsert?: Prisma.EvaluationResultsUpsertWithWhereUniqueWithoutEvaluationInput | Prisma.EvaluationResultsUpsertWithWhereUniqueWithoutEvaluationInput[]
  createMany?: Prisma.EvaluationResultsCreateManyEvaluationInputEnvelope
  set?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
  disconnect?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
  delete?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
  connect?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
  update?: Prisma.EvaluationResultsUpdateWithWhereUniqueWithoutEvaluationInput | Prisma.EvaluationResultsUpdateWithWhereUniqueWithoutEvaluationInput[]
  updateMany?: Prisma.EvaluationResultsUpdateManyWithWhereWithoutEvaluationInput | Prisma.EvaluationResultsUpdateManyWithWhereWithoutEvaluationInput[]
  deleteMany?: Prisma.EvaluationResultsScalarWhereInput | Prisma.EvaluationResultsScalarWhereInput[]
}

export type EvaluationResultsUncheckedUpdateManyWithoutEvaluationNestedInput = {
  create?: Prisma.XOR<Prisma.EvaluationResultsCreateWithoutEvaluationInput, Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput> | Prisma.EvaluationResultsCreateWithoutEvaluationInput[] | Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput[]
  connectOrCreate?: Prisma.EvaluationResultsCreateOrConnectWithoutEvaluationInput | Prisma.EvaluationResultsCreateOrConnectWithoutEvaluationInput[]
  upsert?: Prisma.EvaluationResultsUpsertWithWhereUniqueWithoutEvaluationInput | Prisma.EvaluationResultsUpsertWithWhereUniqueWithoutEvaluationInput[]
  createMany?: Prisma.EvaluationResultsCreateManyEvaluationInputEnvelope
  set?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
  disconnect?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
  delete?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
  connect?: Prisma.EvaluationResultsWhereUniqueInput | Prisma.EvaluationResultsWhereUniqueInput[]
  update?: Prisma.EvaluationResultsUpdateWithWhereUniqueWithoutEvaluationInput | Prisma.EvaluationResultsUpdateWithWhereUniqueWithoutEvaluationInput[]
  updateMany?: Prisma.EvaluationResultsUpdateManyWithWhereWithoutEvaluationInput | Prisma.EvaluationResultsUpdateManyWithWhereWithoutEvaluationInput[]
  deleteMany?: Prisma.EvaluationResultsScalarWhereInput | Prisma.EvaluationResultsScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EvaluationResultsCreateWithoutEvaluationInput = {
  status?: string
  results: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  completed_at?: Date | string | null
}

export type EvaluationResultsUncheckedCreateWithoutEvaluationInput = {
  evaluation_result_id?: number
  status?: string
  results: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  completed_at?: Date | string | null
}

export type EvaluationResultsCreateOrConnectWithoutEvaluationInput = {
  where: Prisma.EvaluationResultsWhereUniqueInput
  create: Prisma.XOR<Prisma.EvaluationResultsCreateWithoutEvaluationInput, Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput>
}

export type EvaluationResultsCreateManyEvaluationInputEnvelope = {
  data: Prisma.EvaluationResultsCreateManyEvaluationInput | Prisma.EvaluationResultsCreateManyEvaluationInput[]
}

export type EvaluationResultsUpsertWithWhereUniqueWithoutEvaluationInput = {
  where: Prisma.EvaluationResultsWhereUniqueInput
  update: Prisma.XOR<Prisma.EvaluationResultsUpdateWithoutEvaluationInput, Prisma.EvaluationResultsUncheckedUpdateWithoutEvaluationInput>
  create: Prisma.XOR<Prisma.EvaluationResultsCreateWithoutEvaluationInput, Prisma.EvaluationResultsUncheckedCreateWithoutEvaluationInput>
}

export type EvaluationResultsUpdateWithWhereUniqueWithoutEvaluationInput = {
  where: Prisma.EvaluationResultsWhereUniqueInput
  data: Prisma.XOR<Prisma.EvaluationResultsUpdateWithoutEvaluationInput, Prisma.EvaluationResultsUncheckedUpdateWithoutEvaluationInput>
}

export type EvaluationResultsUpdateManyWithWhereWithoutEvaluationInput = {
  where: Prisma.EvaluationResultsScalarWhereInput
  data: Prisma.XOR<Prisma.EvaluationResultsUpdateManyMutationInput, Prisma.EvaluationResultsUncheckedUpdateManyWithoutEvaluationInput>
}

export type EvaluationResultsScalarWhereInput = {
  AND?: Prisma.EvaluationResultsScalarWhereInput | Prisma.EvaluationResultsScalarWhereInput[]
  OR?: Prisma.EvaluationResultsScalarWhereInput[]
  NOT?: Prisma.EvaluationResultsScalarWhereInput | Prisma.EvaluationResultsScalarWhereInput[]
  evaluation_result_id?: Prisma.IntFilter<"EvaluationResults"> | number
  evaluation_id?: Prisma.IntFilter<"EvaluationResults"> | number
  status?: Prisma.StringFilter<"EvaluationResults"> | string
  results?: Prisma.JsonFilter<"EvaluationResults">
  created_at?: Prisma.DateTimeFilter<"EvaluationResults"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"EvaluationResults"> | Date | string
  completed_at?: Prisma.DateTimeNullableFilter<"EvaluationResults"> | Date | string | null
}

export type EvaluationResultsCreateManyEvaluationInput = {
  evaluation_result_id?: number
  status?: string
  results: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  completed_at?: Date | string | null
}

export type EvaluationResultsUpdateWithoutEvaluationInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  results?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EvaluationResultsUncheckedUpdateWithoutEvaluationInput = {
  evaluation_result_id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  results?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EvaluationResultsUncheckedUpdateManyWithoutEvaluationInput = {
  evaluation_result_id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  results?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type EvaluationResultsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  evaluation_result_id?: boolean
  evaluation_id?: boolean
  status?: boolean
  results?: boolean
  created_at?: boolean
  updated_at?: boolean
  completed_at?: boolean
  evaluation?: boolean | Prisma.EvaluationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["evaluationResults"]>

export type EvaluationResultsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  evaluation_result_id?: boolean
  evaluation_id?: boolean
  status?: boolean
  results?: boolean
  created_at?: boolean
  updated_at?: boolean
  completed_at?: boolean
  evaluation?: boolean | Prisma.EvaluationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["evaluationResults"]>

export type EvaluationResultsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  evaluation_result_id?: boolean
  evaluation_id?: boolean
  status?: boolean
  results?: boolean
  created_at?: boolean
  updated_at?: boolean
  completed_at?: boolean
  evaluation?: boolean | Prisma.EvaluationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["evaluationResults"]>

export type EvaluationResultsSelectScalar = {
  evaluation_result_id?: boolean
  evaluation_id?: boolean
  status?: boolean
  results?: boolean
  created_at?: boolean
  updated_at?: boolean
  completed_at?: boolean
}

export type EvaluationResultsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"evaluation_result_id" | "evaluation_id" | "status" | "results" | "created_at" | "updated_at" | "completed_at", ExtArgs["result"]["evaluationResults"]>
export type EvaluationResultsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  evaluation?: boolean | Prisma.EvaluationDefaultArgs<ExtArgs>
}
export type EvaluationResultsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  evaluation?: boolean | Prisma.EvaluationDefaultArgs<ExtArgs>
}
export type EvaluationResultsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  evaluation?: boolean | Prisma.EvaluationDefaultArgs<ExtArgs>
}

export type $EvaluationResultsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EvaluationResults"
  objects: {
    evaluation: Prisma.$EvaluationPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    evaluation_result_id: number
    evaluation_id: number
    status: string
    results: runtime.JsonValue
    created_at: Date
    updated_at: Date
    completed_at: Date | null
  }, ExtArgs["result"]["evaluationResults"]>
  composites: {}
}

export type EvaluationResultsGetPayload<S extends boolean | null | undefined | EvaluationResultsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload, S>

export type EvaluationResultsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EvaluationResultsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EvaluationResultsCountAggregateInputType | true
  }

export interface EvaluationResultsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EvaluationResults'], meta: { name: 'EvaluationResults' } }
  /**
   * Find zero or one EvaluationResults that matches the filter.
   * @param {EvaluationResultsFindUniqueArgs} args - Arguments to find a EvaluationResults
   * @example
   * // Get one EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EvaluationResultsFindUniqueArgs>(args: Prisma.SelectSubset<T, EvaluationResultsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EvaluationResultsClient<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EvaluationResults that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EvaluationResultsFindUniqueOrThrowArgs} args - Arguments to find a EvaluationResults
   * @example
   * // Get one EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EvaluationResultsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EvaluationResultsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EvaluationResultsClient<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EvaluationResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvaluationResultsFindFirstArgs} args - Arguments to find a EvaluationResults
   * @example
   * // Get one EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EvaluationResultsFindFirstArgs>(args?: Prisma.SelectSubset<T, EvaluationResultsFindFirstArgs<ExtArgs>>): Prisma.Prisma__EvaluationResultsClient<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EvaluationResults that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvaluationResultsFindFirstOrThrowArgs} args - Arguments to find a EvaluationResults
   * @example
   * // Get one EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EvaluationResultsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EvaluationResultsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EvaluationResultsClient<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EvaluationResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvaluationResultsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.findMany()
   * 
   * // Get first 10 EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.findMany({ take: 10 })
   * 
   * // Only select the `evaluation_result_id`
   * const evaluationResultsWithEvaluation_result_idOnly = await prisma.evaluationResults.findMany({ select: { evaluation_result_id: true } })
   * 
   */
  findMany<T extends EvaluationResultsFindManyArgs>(args?: Prisma.SelectSubset<T, EvaluationResultsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EvaluationResults.
   * @param {EvaluationResultsCreateArgs} args - Arguments to create a EvaluationResults.
   * @example
   * // Create one EvaluationResults
   * const EvaluationResults = await prisma.evaluationResults.create({
   *   data: {
   *     // ... data to create a EvaluationResults
   *   }
   * })
   * 
   */
  create<T extends EvaluationResultsCreateArgs>(args: Prisma.SelectSubset<T, EvaluationResultsCreateArgs<ExtArgs>>): Prisma.Prisma__EvaluationResultsClient<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EvaluationResults.
   * @param {EvaluationResultsCreateManyArgs} args - Arguments to create many EvaluationResults.
   * @example
   * // Create many EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EvaluationResultsCreateManyArgs>(args?: Prisma.SelectSubset<T, EvaluationResultsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EvaluationResults and returns the data saved in the database.
   * @param {EvaluationResultsCreateManyAndReturnArgs} args - Arguments to create many EvaluationResults.
   * @example
   * // Create many EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EvaluationResults and only return the `evaluation_result_id`
   * const evaluationResultsWithEvaluation_result_idOnly = await prisma.evaluationResults.createManyAndReturn({
   *   select: { evaluation_result_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EvaluationResultsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EvaluationResultsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EvaluationResults.
   * @param {EvaluationResultsDeleteArgs} args - Arguments to delete one EvaluationResults.
   * @example
   * // Delete one EvaluationResults
   * const EvaluationResults = await prisma.evaluationResults.delete({
   *   where: {
   *     // ... filter to delete one EvaluationResults
   *   }
   * })
   * 
   */
  delete<T extends EvaluationResultsDeleteArgs>(args: Prisma.SelectSubset<T, EvaluationResultsDeleteArgs<ExtArgs>>): Prisma.Prisma__EvaluationResultsClient<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EvaluationResults.
   * @param {EvaluationResultsUpdateArgs} args - Arguments to update one EvaluationResults.
   * @example
   * // Update one EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EvaluationResultsUpdateArgs>(args: Prisma.SelectSubset<T, EvaluationResultsUpdateArgs<ExtArgs>>): Prisma.Prisma__EvaluationResultsClient<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EvaluationResults.
   * @param {EvaluationResultsDeleteManyArgs} args - Arguments to filter EvaluationResults to delete.
   * @example
   * // Delete a few EvaluationResults
   * const { count } = await prisma.evaluationResults.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EvaluationResultsDeleteManyArgs>(args?: Prisma.SelectSubset<T, EvaluationResultsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EvaluationResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvaluationResultsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EvaluationResultsUpdateManyArgs>(args: Prisma.SelectSubset<T, EvaluationResultsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EvaluationResults and returns the data updated in the database.
   * @param {EvaluationResultsUpdateManyAndReturnArgs} args - Arguments to update many EvaluationResults.
   * @example
   * // Update many EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EvaluationResults and only return the `evaluation_result_id`
   * const evaluationResultsWithEvaluation_result_idOnly = await prisma.evaluationResults.updateManyAndReturn({
   *   select: { evaluation_result_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EvaluationResultsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EvaluationResultsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EvaluationResults.
   * @param {EvaluationResultsUpsertArgs} args - Arguments to update or create a EvaluationResults.
   * @example
   * // Update or create a EvaluationResults
   * const evaluationResults = await prisma.evaluationResults.upsert({
   *   create: {
   *     // ... data to create a EvaluationResults
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EvaluationResults we want to update
   *   }
   * })
   */
  upsert<T extends EvaluationResultsUpsertArgs>(args: Prisma.SelectSubset<T, EvaluationResultsUpsertArgs<ExtArgs>>): Prisma.Prisma__EvaluationResultsClient<runtime.Types.Result.GetResult<Prisma.$EvaluationResultsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EvaluationResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvaluationResultsCountArgs} args - Arguments to filter EvaluationResults to count.
   * @example
   * // Count the number of EvaluationResults
   * const count = await prisma.evaluationResults.count({
   *   where: {
   *     // ... the filter for the EvaluationResults we want to count
   *   }
   * })
  **/
  count<T extends EvaluationResultsCountArgs>(
    args?: Prisma.Subset<T, EvaluationResultsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EvaluationResultsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EvaluationResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvaluationResultsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EvaluationResultsAggregateArgs>(args: Prisma.Subset<T, EvaluationResultsAggregateArgs>): Prisma.PrismaPromise<GetEvaluationResultsAggregateType<T>>

  /**
   * Group by EvaluationResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvaluationResultsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EvaluationResultsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EvaluationResultsGroupByArgs['orderBy'] }
      : { orderBy?: EvaluationResultsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EvaluationResultsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEvaluationResultsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EvaluationResults model
 */
readonly fields: EvaluationResultsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EvaluationResults.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EvaluationResultsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  evaluation<T extends Prisma.EvaluationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EvaluationDefaultArgs<ExtArgs>>): Prisma.Prisma__EvaluationClient<runtime.Types.Result.GetResult<Prisma.$EvaluationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EvaluationResults model
 */
export interface EvaluationResultsFieldRefs {
  readonly evaluation_result_id: Prisma.FieldRef<"EvaluationResults", 'Int'>
  readonly evaluation_id: Prisma.FieldRef<"EvaluationResults", 'Int'>
  readonly status: Prisma.FieldRef<"EvaluationResults", 'String'>
  readonly results: Prisma.FieldRef<"EvaluationResults", 'Json'>
  readonly created_at: Prisma.FieldRef<"EvaluationResults", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"EvaluationResults", 'DateTime'>
  readonly completed_at: Prisma.FieldRef<"EvaluationResults", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EvaluationResults findUnique
 */
export type EvaluationResultsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * Filter, which EvaluationResults to fetch.
   */
  where: Prisma.EvaluationResultsWhereUniqueInput
}

/**
 * EvaluationResults findUniqueOrThrow
 */
export type EvaluationResultsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * Filter, which EvaluationResults to fetch.
   */
  where: Prisma.EvaluationResultsWhereUniqueInput
}

/**
 * EvaluationResults findFirst
 */
export type EvaluationResultsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * Filter, which EvaluationResults to fetch.
   */
  where?: Prisma.EvaluationResultsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EvaluationResults to fetch.
   */
  orderBy?: Prisma.EvaluationResultsOrderByWithRelationInput | Prisma.EvaluationResultsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EvaluationResults.
   */
  cursor?: Prisma.EvaluationResultsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EvaluationResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EvaluationResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EvaluationResults.
   */
  distinct?: Prisma.EvaluationResultsScalarFieldEnum | Prisma.EvaluationResultsScalarFieldEnum[]
}

/**
 * EvaluationResults findFirstOrThrow
 */
export type EvaluationResultsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * Filter, which EvaluationResults to fetch.
   */
  where?: Prisma.EvaluationResultsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EvaluationResults to fetch.
   */
  orderBy?: Prisma.EvaluationResultsOrderByWithRelationInput | Prisma.EvaluationResultsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EvaluationResults.
   */
  cursor?: Prisma.EvaluationResultsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EvaluationResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EvaluationResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EvaluationResults.
   */
  distinct?: Prisma.EvaluationResultsScalarFieldEnum | Prisma.EvaluationResultsScalarFieldEnum[]
}

/**
 * EvaluationResults findMany
 */
export type EvaluationResultsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * Filter, which EvaluationResults to fetch.
   */
  where?: Prisma.EvaluationResultsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EvaluationResults to fetch.
   */
  orderBy?: Prisma.EvaluationResultsOrderByWithRelationInput | Prisma.EvaluationResultsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EvaluationResults.
   */
  cursor?: Prisma.EvaluationResultsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EvaluationResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EvaluationResults.
   */
  skip?: number
  distinct?: Prisma.EvaluationResultsScalarFieldEnum | Prisma.EvaluationResultsScalarFieldEnum[]
}

/**
 * EvaluationResults create
 */
export type EvaluationResultsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * The data needed to create a EvaluationResults.
   */
  data: Prisma.XOR<Prisma.EvaluationResultsCreateInput, Prisma.EvaluationResultsUncheckedCreateInput>
}

/**
 * EvaluationResults createMany
 */
export type EvaluationResultsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EvaluationResults.
   */
  data: Prisma.EvaluationResultsCreateManyInput | Prisma.EvaluationResultsCreateManyInput[]
}

/**
 * EvaluationResults createManyAndReturn
 */
export type EvaluationResultsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * The data used to create many EvaluationResults.
   */
  data: Prisma.EvaluationResultsCreateManyInput | Prisma.EvaluationResultsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EvaluationResults update
 */
export type EvaluationResultsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * The data needed to update a EvaluationResults.
   */
  data: Prisma.XOR<Prisma.EvaluationResultsUpdateInput, Prisma.EvaluationResultsUncheckedUpdateInput>
  /**
   * Choose, which EvaluationResults to update.
   */
  where: Prisma.EvaluationResultsWhereUniqueInput
}

/**
 * EvaluationResults updateMany
 */
export type EvaluationResultsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EvaluationResults.
   */
  data: Prisma.XOR<Prisma.EvaluationResultsUpdateManyMutationInput, Prisma.EvaluationResultsUncheckedUpdateManyInput>
  /**
   * Filter which EvaluationResults to update
   */
  where?: Prisma.EvaluationResultsWhereInput
  /**
   * Limit how many EvaluationResults to update.
   */
  limit?: number
}

/**
 * EvaluationResults updateManyAndReturn
 */
export type EvaluationResultsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * The data used to update EvaluationResults.
   */
  data: Prisma.XOR<Prisma.EvaluationResultsUpdateManyMutationInput, Prisma.EvaluationResultsUncheckedUpdateManyInput>
  /**
   * Filter which EvaluationResults to update
   */
  where?: Prisma.EvaluationResultsWhereInput
  /**
   * Limit how many EvaluationResults to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EvaluationResults upsert
 */
export type EvaluationResultsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * The filter to search for the EvaluationResults to update in case it exists.
   */
  where: Prisma.EvaluationResultsWhereUniqueInput
  /**
   * In case the EvaluationResults found by the `where` argument doesn't exist, create a new EvaluationResults with this data.
   */
  create: Prisma.XOR<Prisma.EvaluationResultsCreateInput, Prisma.EvaluationResultsUncheckedCreateInput>
  /**
   * In case the EvaluationResults was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EvaluationResultsUpdateInput, Prisma.EvaluationResultsUncheckedUpdateInput>
}

/**
 * EvaluationResults delete
 */
export type EvaluationResultsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
  /**
   * Filter which EvaluationResults to delete.
   */
  where: Prisma.EvaluationResultsWhereUniqueInput
}

/**
 * EvaluationResults deleteMany
 */
export type EvaluationResultsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EvaluationResults to delete
   */
  where?: Prisma.EvaluationResultsWhereInput
  /**
   * Limit how many EvaluationResults to delete.
   */
  limit?: number
}

/**
 * EvaluationResults without action
 */
export type EvaluationResultsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationResults
   */
  select?: Prisma.EvaluationResultsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationResults
   */
  omit?: Prisma.EvaluationResultsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationResultsInclude<ExtArgs> | null
}
