
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `McpServer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model McpServer
 * 
 */
export type McpServerModel = runtime.Types.Result.DefaultSelection<Prisma.$McpServerPayload>

export type AggregateMcpServer = {
  _count: McpServerCountAggregateOutputType | null
  _avg: McpServerAvgAggregateOutputType | null
  _sum: McpServerSumAggregateOutputType | null
  _min: McpServerMinAggregateOutputType | null
  _max: McpServerMaxAggregateOutputType | null
}

export type McpServerAvgAggregateOutputType = {
  server_id: number | null
}

export type McpServerSumAggregateOutputType = {
  server_id: number | null
}

export type McpServerMinAggregateOutputType = {
  server_id: number | null
  config_id: string | null
}

export type McpServerMaxAggregateOutputType = {
  server_id: number | null
  config_id: string | null
}

export type McpServerCountAggregateOutputType = {
  server_id: number
  config_id: number
  _all: number
}


export type McpServerAvgAggregateInputType = {
  server_id?: true
}

export type McpServerSumAggregateInputType = {
  server_id?: true
}

export type McpServerMinAggregateInputType = {
  server_id?: true
  config_id?: true
}

export type McpServerMaxAggregateInputType = {
  server_id?: true
  config_id?: true
}

export type McpServerCountAggregateInputType = {
  server_id?: true
  config_id?: true
  _all?: true
}

export type McpServerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which McpServer to aggregate.
   */
  where?: Prisma.McpServerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpServers to fetch.
   */
  orderBy?: Prisma.McpServerOrderByWithRelationInput | Prisma.McpServerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.McpServerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpServers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpServers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned McpServers
  **/
  _count?: true | McpServerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: McpServerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: McpServerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: McpServerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: McpServerMaxAggregateInputType
}

export type GetMcpServerAggregateType<T extends McpServerAggregateArgs> = {
      [P in keyof T & keyof AggregateMcpServer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMcpServer[P]>
    : Prisma.GetScalarType<T[P], AggregateMcpServer[P]>
}




export type McpServerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.McpServerWhereInput
  orderBy?: Prisma.McpServerOrderByWithAggregationInput | Prisma.McpServerOrderByWithAggregationInput[]
  by: Prisma.McpServerScalarFieldEnum[] | Prisma.McpServerScalarFieldEnum
  having?: Prisma.McpServerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: McpServerCountAggregateInputType | true
  _avg?: McpServerAvgAggregateInputType
  _sum?: McpServerSumAggregateInputType
  _min?: McpServerMinAggregateInputType
  _max?: McpServerMaxAggregateInputType
}

export type McpServerGroupByOutputType = {
  server_id: number
  config_id: string
  _count: McpServerCountAggregateOutputType | null
  _avg: McpServerAvgAggregateOutputType | null
  _sum: McpServerSumAggregateOutputType | null
  _min: McpServerMinAggregateOutputType | null
  _max: McpServerMaxAggregateOutputType | null
}

type GetMcpServerGroupByPayload<T extends McpServerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<McpServerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof McpServerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], McpServerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], McpServerGroupByOutputType[P]>
      }
    >
  >



export type McpServerWhereInput = {
  AND?: Prisma.McpServerWhereInput | Prisma.McpServerWhereInput[]
  OR?: Prisma.McpServerWhereInput[]
  NOT?: Prisma.McpServerWhereInput | Prisma.McpServerWhereInput[]
  server_id?: Prisma.IntFilter<"McpServer"> | number
  config_id?: Prisma.StringFilter<"McpServer"> | string
  tools?: Prisma.ToolListRelationFilter
}

export type McpServerOrderByWithRelationInput = {
  server_id?: Prisma.SortOrder
  config_id?: Prisma.SortOrder
  tools?: Prisma.ToolOrderByRelationAggregateInput
}

export type McpServerWhereUniqueInput = Prisma.AtLeast<{
  server_id?: number
  config_id?: string
  AND?: Prisma.McpServerWhereInput | Prisma.McpServerWhereInput[]
  OR?: Prisma.McpServerWhereInput[]
  NOT?: Prisma.McpServerWhereInput | Prisma.McpServerWhereInput[]
  tools?: Prisma.ToolListRelationFilter
}, "server_id" | "config_id">

export type McpServerOrderByWithAggregationInput = {
  server_id?: Prisma.SortOrder
  config_id?: Prisma.SortOrder
  _count?: Prisma.McpServerCountOrderByAggregateInput
  _avg?: Prisma.McpServerAvgOrderByAggregateInput
  _max?: Prisma.McpServerMaxOrderByAggregateInput
  _min?: Prisma.McpServerMinOrderByAggregateInput
  _sum?: Prisma.McpServerSumOrderByAggregateInput
}

export type McpServerScalarWhereWithAggregatesInput = {
  AND?: Prisma.McpServerScalarWhereWithAggregatesInput | Prisma.McpServerScalarWhereWithAggregatesInput[]
  OR?: Prisma.McpServerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.McpServerScalarWhereWithAggregatesInput | Prisma.McpServerScalarWhereWithAggregatesInput[]
  server_id?: Prisma.IntWithAggregatesFilter<"McpServer"> | number
  config_id?: Prisma.StringWithAggregatesFilter<"McpServer"> | string
}

export type McpServerCreateInput = {
  config_id: string
  tools?: Prisma.ToolCreateNestedManyWithoutMcp_serverInput
}

export type McpServerUncheckedCreateInput = {
  server_id?: number
  config_id: string
  tools?: Prisma.ToolUncheckedCreateNestedManyWithoutMcp_serverInput
}

export type McpServerUpdateInput = {
  config_id?: Prisma.StringFieldUpdateOperationsInput | string
  tools?: Prisma.ToolUpdateManyWithoutMcp_serverNestedInput
}

export type McpServerUncheckedUpdateInput = {
  server_id?: Prisma.IntFieldUpdateOperationsInput | number
  config_id?: Prisma.StringFieldUpdateOperationsInput | string
  tools?: Prisma.ToolUncheckedUpdateManyWithoutMcp_serverNestedInput
}

export type McpServerCreateManyInput = {
  server_id?: number
  config_id: string
}

export type McpServerUpdateManyMutationInput = {
  config_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type McpServerUncheckedUpdateManyInput = {
  server_id?: Prisma.IntFieldUpdateOperationsInput | number
  config_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type McpServerCountOrderByAggregateInput = {
  server_id?: Prisma.SortOrder
  config_id?: Prisma.SortOrder
}

export type McpServerAvgOrderByAggregateInput = {
  server_id?: Prisma.SortOrder
}

export type McpServerMaxOrderByAggregateInput = {
  server_id?: Prisma.SortOrder
  config_id?: Prisma.SortOrder
}

export type McpServerMinOrderByAggregateInput = {
  server_id?: Prisma.SortOrder
  config_id?: Prisma.SortOrder
}

export type McpServerSumOrderByAggregateInput = {
  server_id?: Prisma.SortOrder
}

export type McpServerNullableScalarRelationFilter = {
  is?: Prisma.McpServerWhereInput | null
  isNot?: Prisma.McpServerWhereInput | null
}

export type McpServerCreateNestedOneWithoutToolsInput = {
  create?: Prisma.XOR<Prisma.McpServerCreateWithoutToolsInput, Prisma.McpServerUncheckedCreateWithoutToolsInput>
  connectOrCreate?: Prisma.McpServerCreateOrConnectWithoutToolsInput
  connect?: Prisma.McpServerWhereUniqueInput
}

export type McpServerUpdateOneWithoutToolsNestedInput = {
  create?: Prisma.XOR<Prisma.McpServerCreateWithoutToolsInput, Prisma.McpServerUncheckedCreateWithoutToolsInput>
  connectOrCreate?: Prisma.McpServerCreateOrConnectWithoutToolsInput
  upsert?: Prisma.McpServerUpsertWithoutToolsInput
  disconnect?: Prisma.McpServerWhereInput | boolean
  delete?: Prisma.McpServerWhereInput | boolean
  connect?: Prisma.McpServerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.McpServerUpdateToOneWithWhereWithoutToolsInput, Prisma.McpServerUpdateWithoutToolsInput>, Prisma.McpServerUncheckedUpdateWithoutToolsInput>
}

export type McpServerCreateWithoutToolsInput = {
  config_id: string
}

export type McpServerUncheckedCreateWithoutToolsInput = {
  server_id?: number
  config_id: string
}

export type McpServerCreateOrConnectWithoutToolsInput = {
  where: Prisma.McpServerWhereUniqueInput
  create: Prisma.XOR<Prisma.McpServerCreateWithoutToolsInput, Prisma.McpServerUncheckedCreateWithoutToolsInput>
}

export type McpServerUpsertWithoutToolsInput = {
  update: Prisma.XOR<Prisma.McpServerUpdateWithoutToolsInput, Prisma.McpServerUncheckedUpdateWithoutToolsInput>
  create: Prisma.XOR<Prisma.McpServerCreateWithoutToolsInput, Prisma.McpServerUncheckedCreateWithoutToolsInput>
  where?: Prisma.McpServerWhereInput
}

export type McpServerUpdateToOneWithWhereWithoutToolsInput = {
  where?: Prisma.McpServerWhereInput
  data: Prisma.XOR<Prisma.McpServerUpdateWithoutToolsInput, Prisma.McpServerUncheckedUpdateWithoutToolsInput>
}

export type McpServerUpdateWithoutToolsInput = {
  config_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type McpServerUncheckedUpdateWithoutToolsInput = {
  server_id?: Prisma.IntFieldUpdateOperationsInput | number
  config_id?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type McpServerCountOutputType
 */

export type McpServerCountOutputType = {
  tools: number
}

export type McpServerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tools?: boolean | McpServerCountOutputTypeCountToolsArgs
}

/**
 * McpServerCountOutputType without action
 */
export type McpServerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServerCountOutputType
   */
  select?: Prisma.McpServerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * McpServerCountOutputType without action
 */
export type McpServerCountOutputTypeCountToolsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ToolWhereInput
}


export type McpServerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  server_id?: boolean
  config_id?: boolean
  tools?: boolean | Prisma.McpServer$toolsArgs<ExtArgs>
  _count?: boolean | Prisma.McpServerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["mcpServer"]>

export type McpServerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  server_id?: boolean
  config_id?: boolean
}, ExtArgs["result"]["mcpServer"]>

export type McpServerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  server_id?: boolean
  config_id?: boolean
}, ExtArgs["result"]["mcpServer"]>

export type McpServerSelectScalar = {
  server_id?: boolean
  config_id?: boolean
}

export type McpServerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"server_id" | "config_id", ExtArgs["result"]["mcpServer"]>
export type McpServerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tools?: boolean | Prisma.McpServer$toolsArgs<ExtArgs>
  _count?: boolean | Prisma.McpServerCountOutputTypeDefaultArgs<ExtArgs>
}
export type McpServerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type McpServerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $McpServerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "McpServer"
  objects: {
    tools: Prisma.$ToolPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    server_id: number
    config_id: string
  }, ExtArgs["result"]["mcpServer"]>
  composites: {}
}

export type McpServerGetPayload<S extends boolean | null | undefined | McpServerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$McpServerPayload, S>

export type McpServerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<McpServerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: McpServerCountAggregateInputType | true
  }

export interface McpServerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['McpServer'], meta: { name: 'McpServer' } }
  /**
   * Find zero or one McpServer that matches the filter.
   * @param {McpServerFindUniqueArgs} args - Arguments to find a McpServer
   * @example
   * // Get one McpServer
   * const mcpServer = await prisma.mcpServer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends McpServerFindUniqueArgs>(args: Prisma.SelectSubset<T, McpServerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one McpServer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {McpServerFindUniqueOrThrowArgs} args - Arguments to find a McpServer
   * @example
   * // Get one McpServer
   * const mcpServer = await prisma.mcpServer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends McpServerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, McpServerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first McpServer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpServerFindFirstArgs} args - Arguments to find a McpServer
   * @example
   * // Get one McpServer
   * const mcpServer = await prisma.mcpServer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends McpServerFindFirstArgs>(args?: Prisma.SelectSubset<T, McpServerFindFirstArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first McpServer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpServerFindFirstOrThrowArgs} args - Arguments to find a McpServer
   * @example
   * // Get one McpServer
   * const mcpServer = await prisma.mcpServer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends McpServerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, McpServerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more McpServers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpServerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all McpServers
   * const mcpServers = await prisma.mcpServer.findMany()
   * 
   * // Get first 10 McpServers
   * const mcpServers = await prisma.mcpServer.findMany({ take: 10 })
   * 
   * // Only select the `server_id`
   * const mcpServerWithServer_idOnly = await prisma.mcpServer.findMany({ select: { server_id: true } })
   * 
   */
  findMany<T extends McpServerFindManyArgs>(args?: Prisma.SelectSubset<T, McpServerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a McpServer.
   * @param {McpServerCreateArgs} args - Arguments to create a McpServer.
   * @example
   * // Create one McpServer
   * const McpServer = await prisma.mcpServer.create({
   *   data: {
   *     // ... data to create a McpServer
   *   }
   * })
   * 
   */
  create<T extends McpServerCreateArgs>(args: Prisma.SelectSubset<T, McpServerCreateArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many McpServers.
   * @param {McpServerCreateManyArgs} args - Arguments to create many McpServers.
   * @example
   * // Create many McpServers
   * const mcpServer = await prisma.mcpServer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends McpServerCreateManyArgs>(args?: Prisma.SelectSubset<T, McpServerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many McpServers and returns the data saved in the database.
   * @param {McpServerCreateManyAndReturnArgs} args - Arguments to create many McpServers.
   * @example
   * // Create many McpServers
   * const mcpServer = await prisma.mcpServer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many McpServers and only return the `server_id`
   * const mcpServerWithServer_idOnly = await prisma.mcpServer.createManyAndReturn({
   *   select: { server_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends McpServerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, McpServerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a McpServer.
   * @param {McpServerDeleteArgs} args - Arguments to delete one McpServer.
   * @example
   * // Delete one McpServer
   * const McpServer = await prisma.mcpServer.delete({
   *   where: {
   *     // ... filter to delete one McpServer
   *   }
   * })
   * 
   */
  delete<T extends McpServerDeleteArgs>(args: Prisma.SelectSubset<T, McpServerDeleteArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one McpServer.
   * @param {McpServerUpdateArgs} args - Arguments to update one McpServer.
   * @example
   * // Update one McpServer
   * const mcpServer = await prisma.mcpServer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends McpServerUpdateArgs>(args: Prisma.SelectSubset<T, McpServerUpdateArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more McpServers.
   * @param {McpServerDeleteManyArgs} args - Arguments to filter McpServers to delete.
   * @example
   * // Delete a few McpServers
   * const { count } = await prisma.mcpServer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends McpServerDeleteManyArgs>(args?: Prisma.SelectSubset<T, McpServerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more McpServers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpServerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many McpServers
   * const mcpServer = await prisma.mcpServer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends McpServerUpdateManyArgs>(args: Prisma.SelectSubset<T, McpServerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more McpServers and returns the data updated in the database.
   * @param {McpServerUpdateManyAndReturnArgs} args - Arguments to update many McpServers.
   * @example
   * // Update many McpServers
   * const mcpServer = await prisma.mcpServer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more McpServers and only return the `server_id`
   * const mcpServerWithServer_idOnly = await prisma.mcpServer.updateManyAndReturn({
   *   select: { server_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends McpServerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, McpServerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one McpServer.
   * @param {McpServerUpsertArgs} args - Arguments to update or create a McpServer.
   * @example
   * // Update or create a McpServer
   * const mcpServer = await prisma.mcpServer.upsert({
   *   create: {
   *     // ... data to create a McpServer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the McpServer we want to update
   *   }
   * })
   */
  upsert<T extends McpServerUpsertArgs>(args: Prisma.SelectSubset<T, McpServerUpsertArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of McpServers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpServerCountArgs} args - Arguments to filter McpServers to count.
   * @example
   * // Count the number of McpServers
   * const count = await prisma.mcpServer.count({
   *   where: {
   *     // ... the filter for the McpServers we want to count
   *   }
   * })
  **/
  count<T extends McpServerCountArgs>(
    args?: Prisma.Subset<T, McpServerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], McpServerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a McpServer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpServerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends McpServerAggregateArgs>(args: Prisma.Subset<T, McpServerAggregateArgs>): Prisma.PrismaPromise<GetMcpServerAggregateType<T>>

  /**
   * Group by McpServer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {McpServerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends McpServerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: McpServerGroupByArgs['orderBy'] }
      : { orderBy?: McpServerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, McpServerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMcpServerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the McpServer model
 */
readonly fields: McpServerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for McpServer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__McpServerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tools<T extends Prisma.McpServer$toolsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.McpServer$toolsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the McpServer model
 */
export interface McpServerFieldRefs {
  readonly server_id: Prisma.FieldRef<"McpServer", 'Int'>
  readonly config_id: Prisma.FieldRef<"McpServer", 'String'>
}
    

// Custom InputTypes
/**
 * McpServer findUnique
 */
export type McpServerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * Filter, which McpServer to fetch.
   */
  where: Prisma.McpServerWhereUniqueInput
}

/**
 * McpServer findUniqueOrThrow
 */
export type McpServerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * Filter, which McpServer to fetch.
   */
  where: Prisma.McpServerWhereUniqueInput
}

/**
 * McpServer findFirst
 */
export type McpServerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * Filter, which McpServer to fetch.
   */
  where?: Prisma.McpServerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpServers to fetch.
   */
  orderBy?: Prisma.McpServerOrderByWithRelationInput | Prisma.McpServerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for McpServers.
   */
  cursor?: Prisma.McpServerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpServers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpServers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McpServers.
   */
  distinct?: Prisma.McpServerScalarFieldEnum | Prisma.McpServerScalarFieldEnum[]
}

/**
 * McpServer findFirstOrThrow
 */
export type McpServerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * Filter, which McpServer to fetch.
   */
  where?: Prisma.McpServerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpServers to fetch.
   */
  orderBy?: Prisma.McpServerOrderByWithRelationInput | Prisma.McpServerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for McpServers.
   */
  cursor?: Prisma.McpServerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpServers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpServers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of McpServers.
   */
  distinct?: Prisma.McpServerScalarFieldEnum | Prisma.McpServerScalarFieldEnum[]
}

/**
 * McpServer findMany
 */
export type McpServerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * Filter, which McpServers to fetch.
   */
  where?: Prisma.McpServerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of McpServers to fetch.
   */
  orderBy?: Prisma.McpServerOrderByWithRelationInput | Prisma.McpServerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing McpServers.
   */
  cursor?: Prisma.McpServerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` McpServers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` McpServers.
   */
  skip?: number
  distinct?: Prisma.McpServerScalarFieldEnum | Prisma.McpServerScalarFieldEnum[]
}

/**
 * McpServer create
 */
export type McpServerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * The data needed to create a McpServer.
   */
  data: Prisma.XOR<Prisma.McpServerCreateInput, Prisma.McpServerUncheckedCreateInput>
}

/**
 * McpServer createMany
 */
export type McpServerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many McpServers.
   */
  data: Prisma.McpServerCreateManyInput | Prisma.McpServerCreateManyInput[]
}

/**
 * McpServer createManyAndReturn
 */
export type McpServerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * The data used to create many McpServers.
   */
  data: Prisma.McpServerCreateManyInput | Prisma.McpServerCreateManyInput[]
}

/**
 * McpServer update
 */
export type McpServerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * The data needed to update a McpServer.
   */
  data: Prisma.XOR<Prisma.McpServerUpdateInput, Prisma.McpServerUncheckedUpdateInput>
  /**
   * Choose, which McpServer to update.
   */
  where: Prisma.McpServerWhereUniqueInput
}

/**
 * McpServer updateMany
 */
export type McpServerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update McpServers.
   */
  data: Prisma.XOR<Prisma.McpServerUpdateManyMutationInput, Prisma.McpServerUncheckedUpdateManyInput>
  /**
   * Filter which McpServers to update
   */
  where?: Prisma.McpServerWhereInput
  /**
   * Limit how many McpServers to update.
   */
  limit?: number
}

/**
 * McpServer updateManyAndReturn
 */
export type McpServerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * The data used to update McpServers.
   */
  data: Prisma.XOR<Prisma.McpServerUpdateManyMutationInput, Prisma.McpServerUncheckedUpdateManyInput>
  /**
   * Filter which McpServers to update
   */
  where?: Prisma.McpServerWhereInput
  /**
   * Limit how many McpServers to update.
   */
  limit?: number
}

/**
 * McpServer upsert
 */
export type McpServerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * The filter to search for the McpServer to update in case it exists.
   */
  where: Prisma.McpServerWhereUniqueInput
  /**
   * In case the McpServer found by the `where` argument doesn't exist, create a new McpServer with this data.
   */
  create: Prisma.XOR<Prisma.McpServerCreateInput, Prisma.McpServerUncheckedCreateInput>
  /**
   * In case the McpServer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.McpServerUpdateInput, Prisma.McpServerUncheckedUpdateInput>
}

/**
 * McpServer delete
 */
export type McpServerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  /**
   * Filter which McpServer to delete.
   */
  where: Prisma.McpServerWhereUniqueInput
}

/**
 * McpServer deleteMany
 */
export type McpServerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which McpServers to delete
   */
  where?: Prisma.McpServerWhereInput
  /**
   * Limit how many McpServers to delete.
   */
  limit?: number
}

/**
 * McpServer.tools
 */
export type McpServer$toolsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  where?: Prisma.ToolWhereInput
  orderBy?: Prisma.ToolOrderByWithRelationInput | Prisma.ToolOrderByWithRelationInput[]
  cursor?: Prisma.ToolWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ToolScalarFieldEnum | Prisma.ToolScalarFieldEnum[]
}

/**
 * McpServer without action
 */
export type McpServerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
}
