
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Node` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Node
 * 
 */
export type NodeModel = runtime.Types.Result.DefaultSelection<Prisma.$NodePayload>

export type AggregateNode = {
  _count: NodeCountAggregateOutputType | null
  _avg: NodeAvgAggregateOutputType | null
  _sum: NodeSumAggregateOutputType | null
  _min: NodeMinAggregateOutputType | null
  _max: NodeMaxAggregateOutputType | null
}

export type NodeAvgAggregateOutputType = {
  node_id: number | null
}

export type NodeSumAggregateOutputType = {
  node_id: number | null
}

export type NodeMinAggregateOutputType = {
  node_id: number | null
  type: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type NodeMaxAggregateOutputType = {
  node_id: number | null
  type: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type NodeCountAggregateOutputType = {
  node_id: number
  type: number
  properties: number
  created_at: number
  updated_at: number
  _all: number
}


export type NodeAvgAggregateInputType = {
  node_id?: true
}

export type NodeSumAggregateInputType = {
  node_id?: true
}

export type NodeMinAggregateInputType = {
  node_id?: true
  type?: true
  created_at?: true
  updated_at?: true
}

export type NodeMaxAggregateInputType = {
  node_id?: true
  type?: true
  created_at?: true
  updated_at?: true
}

export type NodeCountAggregateInputType = {
  node_id?: true
  type?: true
  properties?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type NodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Node to aggregate.
   */
  where?: Prisma.NodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nodes to fetch.
   */
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Nodes
  **/
  _count?: true | NodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NodeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NodeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NodeMaxAggregateInputType
}

export type GetNodeAggregateType<T extends NodeAggregateArgs> = {
      [P in keyof T & keyof AggregateNode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNode[P]>
    : Prisma.GetScalarType<T[P], AggregateNode[P]>
}




export type NodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NodeWhereInput
  orderBy?: Prisma.NodeOrderByWithAggregationInput | Prisma.NodeOrderByWithAggregationInput[]
  by: Prisma.NodeScalarFieldEnum[] | Prisma.NodeScalarFieldEnum
  having?: Prisma.NodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NodeCountAggregateInputType | true
  _avg?: NodeAvgAggregateInputType
  _sum?: NodeSumAggregateInputType
  _min?: NodeMinAggregateInputType
  _max?: NodeMaxAggregateInputType
}

export type NodeGroupByOutputType = {
  node_id: number
  type: string
  properties: runtime.JsonValue
  created_at: Date
  updated_at: Date
  _count: NodeCountAggregateOutputType | null
  _avg: NodeAvgAggregateOutputType | null
  _sum: NodeSumAggregateOutputType | null
  _min: NodeMinAggregateOutputType | null
  _max: NodeMaxAggregateOutputType | null
}

type GetNodeGroupByPayload<T extends NodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NodeGroupByOutputType[P]>
      }
    >
  >



export type NodeWhereInput = {
  AND?: Prisma.NodeWhereInput | Prisma.NodeWhereInput[]
  OR?: Prisma.NodeWhereInput[]
  NOT?: Prisma.NodeWhereInput | Prisma.NodeWhereInput[]
  node_id?: Prisma.IntFilter<"Node"> | number
  type?: Prisma.StringFilter<"Node"> | string
  properties?: Prisma.JsonFilter<"Node">
  created_at?: Prisma.DateTimeFilter<"Node"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Node"> | Date | string
  assets?: Prisma.AssetListRelationFilter
  incoming_edges?: Prisma.EdgeListRelationFilter
  outgoing_edges?: Prisma.EdgeListRelationFilter
}

export type NodeOrderByWithRelationInput = {
  node_id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  properties?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  assets?: Prisma.AssetOrderByRelationAggregateInput
  incoming_edges?: Prisma.EdgeOrderByRelationAggregateInput
  outgoing_edges?: Prisma.EdgeOrderByRelationAggregateInput
}

export type NodeWhereUniqueInput = Prisma.AtLeast<{
  node_id?: number
  AND?: Prisma.NodeWhereInput | Prisma.NodeWhereInput[]
  OR?: Prisma.NodeWhereInput[]
  NOT?: Prisma.NodeWhereInput | Prisma.NodeWhereInput[]
  type?: Prisma.StringFilter<"Node"> | string
  properties?: Prisma.JsonFilter<"Node">
  created_at?: Prisma.DateTimeFilter<"Node"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Node"> | Date | string
  assets?: Prisma.AssetListRelationFilter
  incoming_edges?: Prisma.EdgeListRelationFilter
  outgoing_edges?: Prisma.EdgeListRelationFilter
}, "node_id">

export type NodeOrderByWithAggregationInput = {
  node_id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  properties?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.NodeCountOrderByAggregateInput
  _avg?: Prisma.NodeAvgOrderByAggregateInput
  _max?: Prisma.NodeMaxOrderByAggregateInput
  _min?: Prisma.NodeMinOrderByAggregateInput
  _sum?: Prisma.NodeSumOrderByAggregateInput
}

export type NodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.NodeScalarWhereWithAggregatesInput | Prisma.NodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.NodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NodeScalarWhereWithAggregatesInput | Prisma.NodeScalarWhereWithAggregatesInput[]
  node_id?: Prisma.IntWithAggregatesFilter<"Node"> | number
  type?: Prisma.StringWithAggregatesFilter<"Node"> | string
  properties?: Prisma.JsonWithAggregatesFilter<"Node">
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Node"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Node"> | Date | string
}

export type NodeCreateInput = {
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  assets?: Prisma.AssetCreateNestedManyWithoutNodeInput
  incoming_edges?: Prisma.EdgeCreateNestedManyWithoutTargetInput
  outgoing_edges?: Prisma.EdgeCreateNestedManyWithoutSourceInput
}

export type NodeUncheckedCreateInput = {
  node_id?: number
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  assets?: Prisma.AssetUncheckedCreateNestedManyWithoutNodeInput
  incoming_edges?: Prisma.EdgeUncheckedCreateNestedManyWithoutTargetInput
  outgoing_edges?: Prisma.EdgeUncheckedCreateNestedManyWithoutSourceInput
}

export type NodeUpdateInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUpdateManyWithoutNodeNestedInput
  incoming_edges?: Prisma.EdgeUpdateManyWithoutTargetNestedInput
  outgoing_edges?: Prisma.EdgeUpdateManyWithoutSourceNestedInput
}

export type NodeUncheckedUpdateInput = {
  node_id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUncheckedUpdateManyWithoutNodeNestedInput
  incoming_edges?: Prisma.EdgeUncheckedUpdateManyWithoutTargetNestedInput
  outgoing_edges?: Prisma.EdgeUncheckedUpdateManyWithoutSourceNestedInput
}

export type NodeCreateManyInput = {
  node_id?: number
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
}

export type NodeUpdateManyMutationInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NodeUncheckedUpdateManyInput = {
  node_id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NodeCountOrderByAggregateInput = {
  node_id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  properties?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type NodeAvgOrderByAggregateInput = {
  node_id?: Prisma.SortOrder
}

export type NodeMaxOrderByAggregateInput = {
  node_id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type NodeMinOrderByAggregateInput = {
  node_id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type NodeSumOrderByAggregateInput = {
  node_id?: Prisma.SortOrder
}

export type NodeScalarRelationFilter = {
  is?: Prisma.NodeWhereInput
  isNot?: Prisma.NodeWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NodeCreateNestedOneWithoutIncoming_edgesInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutIncoming_edgesInput, Prisma.NodeUncheckedCreateWithoutIncoming_edgesInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutIncoming_edgesInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeCreateNestedOneWithoutOutgoing_edgesInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutOutgoing_edgesInput, Prisma.NodeUncheckedCreateWithoutOutgoing_edgesInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutOutgoing_edgesInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeUpdateOneRequiredWithoutIncoming_edgesNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutIncoming_edgesInput, Prisma.NodeUncheckedCreateWithoutIncoming_edgesInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutIncoming_edgesInput
  upsert?: Prisma.NodeUpsertWithoutIncoming_edgesInput
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutIncoming_edgesInput, Prisma.NodeUpdateWithoutIncoming_edgesInput>, Prisma.NodeUncheckedUpdateWithoutIncoming_edgesInput>
}

export type NodeUpdateOneRequiredWithoutOutgoing_edgesNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutOutgoing_edgesInput, Prisma.NodeUncheckedCreateWithoutOutgoing_edgesInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutOutgoing_edgesInput
  upsert?: Prisma.NodeUpsertWithoutOutgoing_edgesInput
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutOutgoing_edgesInput, Prisma.NodeUpdateWithoutOutgoing_edgesInput>, Prisma.NodeUncheckedUpdateWithoutOutgoing_edgesInput>
}

export type NodeCreateNestedOneWithoutAssetsInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutAssetsInput, Prisma.NodeUncheckedCreateWithoutAssetsInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutAssetsInput
  connect?: Prisma.NodeWhereUniqueInput
}

export type NodeUpdateOneRequiredWithoutAssetsNestedInput = {
  create?: Prisma.XOR<Prisma.NodeCreateWithoutAssetsInput, Prisma.NodeUncheckedCreateWithoutAssetsInput>
  connectOrCreate?: Prisma.NodeCreateOrConnectWithoutAssetsInput
  upsert?: Prisma.NodeUpsertWithoutAssetsInput
  connect?: Prisma.NodeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NodeUpdateToOneWithWhereWithoutAssetsInput, Prisma.NodeUpdateWithoutAssetsInput>, Prisma.NodeUncheckedUpdateWithoutAssetsInput>
}

export type NodeCreateWithoutIncoming_edgesInput = {
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  assets?: Prisma.AssetCreateNestedManyWithoutNodeInput
  outgoing_edges?: Prisma.EdgeCreateNestedManyWithoutSourceInput
}

export type NodeUncheckedCreateWithoutIncoming_edgesInput = {
  node_id?: number
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  assets?: Prisma.AssetUncheckedCreateNestedManyWithoutNodeInput
  outgoing_edges?: Prisma.EdgeUncheckedCreateNestedManyWithoutSourceInput
}

export type NodeCreateOrConnectWithoutIncoming_edgesInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutIncoming_edgesInput, Prisma.NodeUncheckedCreateWithoutIncoming_edgesInput>
}

export type NodeCreateWithoutOutgoing_edgesInput = {
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  assets?: Prisma.AssetCreateNestedManyWithoutNodeInput
  incoming_edges?: Prisma.EdgeCreateNestedManyWithoutTargetInput
}

export type NodeUncheckedCreateWithoutOutgoing_edgesInput = {
  node_id?: number
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  assets?: Prisma.AssetUncheckedCreateNestedManyWithoutNodeInput
  incoming_edges?: Prisma.EdgeUncheckedCreateNestedManyWithoutTargetInput
}

export type NodeCreateOrConnectWithoutOutgoing_edgesInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutOutgoing_edgesInput, Prisma.NodeUncheckedCreateWithoutOutgoing_edgesInput>
}

export type NodeUpsertWithoutIncoming_edgesInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutIncoming_edgesInput, Prisma.NodeUncheckedUpdateWithoutIncoming_edgesInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutIncoming_edgesInput, Prisma.NodeUncheckedCreateWithoutIncoming_edgesInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutIncoming_edgesInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutIncoming_edgesInput, Prisma.NodeUncheckedUpdateWithoutIncoming_edgesInput>
}

export type NodeUpdateWithoutIncoming_edgesInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUpdateManyWithoutNodeNestedInput
  outgoing_edges?: Prisma.EdgeUpdateManyWithoutSourceNestedInput
}

export type NodeUncheckedUpdateWithoutIncoming_edgesInput = {
  node_id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUncheckedUpdateManyWithoutNodeNestedInput
  outgoing_edges?: Prisma.EdgeUncheckedUpdateManyWithoutSourceNestedInput
}

export type NodeUpsertWithoutOutgoing_edgesInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutOutgoing_edgesInput, Prisma.NodeUncheckedUpdateWithoutOutgoing_edgesInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutOutgoing_edgesInput, Prisma.NodeUncheckedCreateWithoutOutgoing_edgesInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutOutgoing_edgesInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutOutgoing_edgesInput, Prisma.NodeUncheckedUpdateWithoutOutgoing_edgesInput>
}

export type NodeUpdateWithoutOutgoing_edgesInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUpdateManyWithoutNodeNestedInput
  incoming_edges?: Prisma.EdgeUpdateManyWithoutTargetNestedInput
}

export type NodeUncheckedUpdateWithoutOutgoing_edgesInput = {
  node_id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assets?: Prisma.AssetUncheckedUpdateManyWithoutNodeNestedInput
  incoming_edges?: Prisma.EdgeUncheckedUpdateManyWithoutTargetNestedInput
}

export type NodeCreateWithoutAssetsInput = {
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  incoming_edges?: Prisma.EdgeCreateNestedManyWithoutTargetInput
  outgoing_edges?: Prisma.EdgeCreateNestedManyWithoutSourceInput
}

export type NodeUncheckedCreateWithoutAssetsInput = {
  node_id?: number
  type: string
  properties: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  incoming_edges?: Prisma.EdgeUncheckedCreateNestedManyWithoutTargetInput
  outgoing_edges?: Prisma.EdgeUncheckedCreateNestedManyWithoutSourceInput
}

export type NodeCreateOrConnectWithoutAssetsInput = {
  where: Prisma.NodeWhereUniqueInput
  create: Prisma.XOR<Prisma.NodeCreateWithoutAssetsInput, Prisma.NodeUncheckedCreateWithoutAssetsInput>
}

export type NodeUpsertWithoutAssetsInput = {
  update: Prisma.XOR<Prisma.NodeUpdateWithoutAssetsInput, Prisma.NodeUncheckedUpdateWithoutAssetsInput>
  create: Prisma.XOR<Prisma.NodeCreateWithoutAssetsInput, Prisma.NodeUncheckedCreateWithoutAssetsInput>
  where?: Prisma.NodeWhereInput
}

export type NodeUpdateToOneWithWhereWithoutAssetsInput = {
  where?: Prisma.NodeWhereInput
  data: Prisma.XOR<Prisma.NodeUpdateWithoutAssetsInput, Prisma.NodeUncheckedUpdateWithoutAssetsInput>
}

export type NodeUpdateWithoutAssetsInput = {
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  incoming_edges?: Prisma.EdgeUpdateManyWithoutTargetNestedInput
  outgoing_edges?: Prisma.EdgeUpdateManyWithoutSourceNestedInput
}

export type NodeUncheckedUpdateWithoutAssetsInput = {
  node_id?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  incoming_edges?: Prisma.EdgeUncheckedUpdateManyWithoutTargetNestedInput
  outgoing_edges?: Prisma.EdgeUncheckedUpdateManyWithoutSourceNestedInput
}


/**
 * Count Type NodeCountOutputType
 */

export type NodeCountOutputType = {
  assets: number
  incoming_edges: number
  outgoing_edges: number
}

export type NodeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assets?: boolean | NodeCountOutputTypeCountAssetsArgs
  incoming_edges?: boolean | NodeCountOutputTypeCountIncoming_edgesArgs
  outgoing_edges?: boolean | NodeCountOutputTypeCountOutgoing_edgesArgs
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NodeCountOutputType
   */
  select?: Prisma.NodeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountAssetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssetWhereInput
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountIncoming_edgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EdgeWhereInput
}

/**
 * NodeCountOutputType without action
 */
export type NodeCountOutputTypeCountOutgoing_edgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EdgeWhereInput
}


export type NodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  node_id?: boolean
  type?: boolean
  properties?: boolean
  created_at?: boolean
  updated_at?: boolean
  assets?: boolean | Prisma.Node$assetsArgs<ExtArgs>
  incoming_edges?: boolean | Prisma.Node$incoming_edgesArgs<ExtArgs>
  outgoing_edges?: boolean | Prisma.Node$outgoing_edgesArgs<ExtArgs>
  _count?: boolean | Prisma.NodeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["node"]>

export type NodeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  node_id?: boolean
  type?: boolean
  properties?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["node"]>

export type NodeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  node_id?: boolean
  type?: boolean
  properties?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["node"]>

export type NodeSelectScalar = {
  node_id?: boolean
  type?: boolean
  properties?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type NodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"node_id" | "type" | "properties" | "created_at" | "updated_at", ExtArgs["result"]["node"]>
export type NodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assets?: boolean | Prisma.Node$assetsArgs<ExtArgs>
  incoming_edges?: boolean | Prisma.Node$incoming_edgesArgs<ExtArgs>
  outgoing_edges?: boolean | Prisma.Node$outgoing_edgesArgs<ExtArgs>
  _count?: boolean | Prisma.NodeCountOutputTypeDefaultArgs<ExtArgs>
}
export type NodeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type NodeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $NodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Node"
  objects: {
    assets: Prisma.$AssetPayload<ExtArgs>[]
    incoming_edges: Prisma.$EdgePayload<ExtArgs>[]
    outgoing_edges: Prisma.$EdgePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    node_id: number
    type: string
    properties: runtime.JsonValue
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["node"]>
  composites: {}
}

export type NodeGetPayload<S extends boolean | null | undefined | NodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NodePayload, S>

export type NodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NodeCountAggregateInputType | true
  }

export interface NodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Node'], meta: { name: 'Node' } }
  /**
   * Find zero or one Node that matches the filter.
   * @param {NodeFindUniqueArgs} args - Arguments to find a Node
   * @example
   * // Get one Node
   * const node = await prisma.node.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NodeFindUniqueArgs>(args: Prisma.SelectSubset<T, NodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Node that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NodeFindUniqueOrThrowArgs} args - Arguments to find a Node
   * @example
   * // Get one Node
   * const node = await prisma.node.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Node that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeFindFirstArgs} args - Arguments to find a Node
   * @example
   * // Get one Node
   * const node = await prisma.node.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NodeFindFirstArgs>(args?: Prisma.SelectSubset<T, NodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Node that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeFindFirstOrThrowArgs} args - Arguments to find a Node
   * @example
   * // Get one Node
   * const node = await prisma.node.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Nodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Nodes
   * const nodes = await prisma.node.findMany()
   * 
   * // Get first 10 Nodes
   * const nodes = await prisma.node.findMany({ take: 10 })
   * 
   * // Only select the `node_id`
   * const nodeWithNode_idOnly = await prisma.node.findMany({ select: { node_id: true } })
   * 
   */
  findMany<T extends NodeFindManyArgs>(args?: Prisma.SelectSubset<T, NodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Node.
   * @param {NodeCreateArgs} args - Arguments to create a Node.
   * @example
   * // Create one Node
   * const Node = await prisma.node.create({
   *   data: {
   *     // ... data to create a Node
   *   }
   * })
   * 
   */
  create<T extends NodeCreateArgs>(args: Prisma.SelectSubset<T, NodeCreateArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Nodes.
   * @param {NodeCreateManyArgs} args - Arguments to create many Nodes.
   * @example
   * // Create many Nodes
   * const node = await prisma.node.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NodeCreateManyArgs>(args?: Prisma.SelectSubset<T, NodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Nodes and returns the data saved in the database.
   * @param {NodeCreateManyAndReturnArgs} args - Arguments to create many Nodes.
   * @example
   * // Create many Nodes
   * const node = await prisma.node.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Nodes and only return the `node_id`
   * const nodeWithNode_idOnly = await prisma.node.createManyAndReturn({
   *   select: { node_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NodeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NodeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Node.
   * @param {NodeDeleteArgs} args - Arguments to delete one Node.
   * @example
   * // Delete one Node
   * const Node = await prisma.node.delete({
   *   where: {
   *     // ... filter to delete one Node
   *   }
   * })
   * 
   */
  delete<T extends NodeDeleteArgs>(args: Prisma.SelectSubset<T, NodeDeleteArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Node.
   * @param {NodeUpdateArgs} args - Arguments to update one Node.
   * @example
   * // Update one Node
   * const node = await prisma.node.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NodeUpdateArgs>(args: Prisma.SelectSubset<T, NodeUpdateArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Nodes.
   * @param {NodeDeleteManyArgs} args - Arguments to filter Nodes to delete.
   * @example
   * // Delete a few Nodes
   * const { count } = await prisma.node.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, NodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Nodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Nodes
   * const node = await prisma.node.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NodeUpdateManyArgs>(args: Prisma.SelectSubset<T, NodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Nodes and returns the data updated in the database.
   * @param {NodeUpdateManyAndReturnArgs} args - Arguments to update many Nodes.
   * @example
   * // Update many Nodes
   * const node = await prisma.node.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Nodes and only return the `node_id`
   * const nodeWithNode_idOnly = await prisma.node.updateManyAndReturn({
   *   select: { node_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NodeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NodeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Node.
   * @param {NodeUpsertArgs} args - Arguments to update or create a Node.
   * @example
   * // Update or create a Node
   * const node = await prisma.node.upsert({
   *   create: {
   *     // ... data to create a Node
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Node we want to update
   *   }
   * })
   */
  upsert<T extends NodeUpsertArgs>(args: Prisma.SelectSubset<T, NodeUpsertArgs<ExtArgs>>): Prisma.Prisma__NodeClient<runtime.Types.Result.GetResult<Prisma.$NodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Nodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeCountArgs} args - Arguments to filter Nodes to count.
   * @example
   * // Count the number of Nodes
   * const count = await prisma.node.count({
   *   where: {
   *     // ... the filter for the Nodes we want to count
   *   }
   * })
  **/
  count<T extends NodeCountArgs>(
    args?: Prisma.Subset<T, NodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Node.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NodeAggregateArgs>(args: Prisma.Subset<T, NodeAggregateArgs>): Prisma.PrismaPromise<GetNodeAggregateType<T>>

  /**
   * Group by Node.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NodeGroupByArgs['orderBy'] }
      : { orderBy?: NodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Node model
 */
readonly fields: NodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Node.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  assets<T extends Prisma.Node$assetsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$assetsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  incoming_edges<T extends Prisma.Node$incoming_edgesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$incoming_edgesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EdgePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  outgoing_edges<T extends Prisma.Node$outgoing_edgesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Node$outgoing_edgesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EdgePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Node model
 */
export interface NodeFieldRefs {
  readonly node_id: Prisma.FieldRef<"Node", 'Int'>
  readonly type: Prisma.FieldRef<"Node", 'String'>
  readonly properties: Prisma.FieldRef<"Node", 'Json'>
  readonly created_at: Prisma.FieldRef<"Node", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Node", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Node findUnique
 */
export type NodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Node to fetch.
   */
  where: Prisma.NodeWhereUniqueInput
}

/**
 * Node findUniqueOrThrow
 */
export type NodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Node to fetch.
   */
  where: Prisma.NodeWhereUniqueInput
}

/**
 * Node findFirst
 */
export type NodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Node to fetch.
   */
  where?: Prisma.NodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nodes to fetch.
   */
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Nodes.
   */
  cursor?: Prisma.NodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Nodes.
   */
  distinct?: Prisma.NodeScalarFieldEnum | Prisma.NodeScalarFieldEnum[]
}

/**
 * Node findFirstOrThrow
 */
export type NodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Node to fetch.
   */
  where?: Prisma.NodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nodes to fetch.
   */
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Nodes.
   */
  cursor?: Prisma.NodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Nodes.
   */
  distinct?: Prisma.NodeScalarFieldEnum | Prisma.NodeScalarFieldEnum[]
}

/**
 * Node findMany
 */
export type NodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter, which Nodes to fetch.
   */
  where?: Prisma.NodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nodes to fetch.
   */
  orderBy?: Prisma.NodeOrderByWithRelationInput | Prisma.NodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Nodes.
   */
  cursor?: Prisma.NodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nodes.
   */
  skip?: number
  distinct?: Prisma.NodeScalarFieldEnum | Prisma.NodeScalarFieldEnum[]
}

/**
 * Node create
 */
export type NodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * The data needed to create a Node.
   */
  data: Prisma.XOR<Prisma.NodeCreateInput, Prisma.NodeUncheckedCreateInput>
}

/**
 * Node createMany
 */
export type NodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Nodes.
   */
  data: Prisma.NodeCreateManyInput | Prisma.NodeCreateManyInput[]
}

/**
 * Node createManyAndReturn
 */
export type NodeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * The data used to create many Nodes.
   */
  data: Prisma.NodeCreateManyInput | Prisma.NodeCreateManyInput[]
}

/**
 * Node update
 */
export type NodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * The data needed to update a Node.
   */
  data: Prisma.XOR<Prisma.NodeUpdateInput, Prisma.NodeUncheckedUpdateInput>
  /**
   * Choose, which Node to update.
   */
  where: Prisma.NodeWhereUniqueInput
}

/**
 * Node updateMany
 */
export type NodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Nodes.
   */
  data: Prisma.XOR<Prisma.NodeUpdateManyMutationInput, Prisma.NodeUncheckedUpdateManyInput>
  /**
   * Filter which Nodes to update
   */
  where?: Prisma.NodeWhereInput
  /**
   * Limit how many Nodes to update.
   */
  limit?: number
}

/**
 * Node updateManyAndReturn
 */
export type NodeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * The data used to update Nodes.
   */
  data: Prisma.XOR<Prisma.NodeUpdateManyMutationInput, Prisma.NodeUncheckedUpdateManyInput>
  /**
   * Filter which Nodes to update
   */
  where?: Prisma.NodeWhereInput
  /**
   * Limit how many Nodes to update.
   */
  limit?: number
}

/**
 * Node upsert
 */
export type NodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * The filter to search for the Node to update in case it exists.
   */
  where: Prisma.NodeWhereUniqueInput
  /**
   * In case the Node found by the `where` argument doesn't exist, create a new Node with this data.
   */
  create: Prisma.XOR<Prisma.NodeCreateInput, Prisma.NodeUncheckedCreateInput>
  /**
   * In case the Node was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NodeUpdateInput, Prisma.NodeUncheckedUpdateInput>
}

/**
 * Node delete
 */
export type NodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
  /**
   * Filter which Node to delete.
   */
  where: Prisma.NodeWhereUniqueInput
}

/**
 * Node deleteMany
 */
export type NodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Nodes to delete
   */
  where?: Prisma.NodeWhereInput
  /**
   * Limit how many Nodes to delete.
   */
  limit?: number
}

/**
 * Node.assets
 */
export type Node$assetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asset
   */
  select?: Prisma.AssetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asset
   */
  omit?: Prisma.AssetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssetInclude<ExtArgs> | null
  where?: Prisma.AssetWhereInput
  orderBy?: Prisma.AssetOrderByWithRelationInput | Prisma.AssetOrderByWithRelationInput[]
  cursor?: Prisma.AssetWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AssetScalarFieldEnum | Prisma.AssetScalarFieldEnum[]
}

/**
 * Node.incoming_edges
 */
export type Node$incoming_edgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Edge
   */
  select?: Prisma.EdgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Edge
   */
  omit?: Prisma.EdgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EdgeInclude<ExtArgs> | null
  where?: Prisma.EdgeWhereInput
  orderBy?: Prisma.EdgeOrderByWithRelationInput | Prisma.EdgeOrderByWithRelationInput[]
  cursor?: Prisma.EdgeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EdgeScalarFieldEnum | Prisma.EdgeScalarFieldEnum[]
}

/**
 * Node.outgoing_edges
 */
export type Node$outgoing_edgesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Edge
   */
  select?: Prisma.EdgeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Edge
   */
  omit?: Prisma.EdgeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EdgeInclude<ExtArgs> | null
  where?: Prisma.EdgeWhereInput
  orderBy?: Prisma.EdgeOrderByWithRelationInput | Prisma.EdgeOrderByWithRelationInput[]
  cursor?: Prisma.EdgeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EdgeScalarFieldEnum | Prisma.EdgeScalarFieldEnum[]
}

/**
 * Node without action
 */
export type NodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Node
   */
  select?: Prisma.NodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Node
   */
  omit?: Prisma.NodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NodeInclude<ExtArgs> | null
}
