
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ThreadMetadata` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ThreadMetadata
 * 
 */
export type ThreadMetadataModel = runtime.Types.Result.DefaultSelection<Prisma.$ThreadMetadataPayload>

export type AggregateThreadMetadata = {
  _count: ThreadMetadataCountAggregateOutputType | null
  _avg: ThreadMetadataAvgAggregateOutputType | null
  _sum: ThreadMetadataSumAggregateOutputType | null
  _min: ThreadMetadataMinAggregateOutputType | null
  _max: ThreadMetadataMaxAggregateOutputType | null
}

export type ThreadMetadataAvgAggregateOutputType = {
  agent_id: number | null
}

export type ThreadMetadataSumAggregateOutputType = {
  agent_id: number | null
}

export type ThreadMetadataMinAggregateOutputType = {
  thread_id: string | null
  agent_id: number | null
  type: string | null
  title: string | null
  archived: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type ThreadMetadataMaxAggregateOutputType = {
  thread_id: string | null
  agent_id: number | null
  type: string | null
  title: string | null
  archived: boolean | null
  created_at: Date | null
  updated_at: Date | null
}

export type ThreadMetadataCountAggregateOutputType = {
  thread_id: number
  agent_id: number
  type: number
  title: number
  archived: number
  created_at: number
  updated_at: number
  _all: number
}


export type ThreadMetadataAvgAggregateInputType = {
  agent_id?: true
}

export type ThreadMetadataSumAggregateInputType = {
  agent_id?: true
}

export type ThreadMetadataMinAggregateInputType = {
  thread_id?: true
  agent_id?: true
  type?: true
  title?: true
  archived?: true
  created_at?: true
  updated_at?: true
}

export type ThreadMetadataMaxAggregateInputType = {
  thread_id?: true
  agent_id?: true
  type?: true
  title?: true
  archived?: true
  created_at?: true
  updated_at?: true
}

export type ThreadMetadataCountAggregateInputType = {
  thread_id?: true
  agent_id?: true
  type?: true
  title?: true
  archived?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type ThreadMetadataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ThreadMetadata to aggregate.
   */
  where?: Prisma.ThreadMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ThreadMetadata to fetch.
   */
  orderBy?: Prisma.ThreadMetadataOrderByWithRelationInput | Prisma.ThreadMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ThreadMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ThreadMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ThreadMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ThreadMetadata
  **/
  _count?: true | ThreadMetadataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ThreadMetadataAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ThreadMetadataSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ThreadMetadataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ThreadMetadataMaxAggregateInputType
}

export type GetThreadMetadataAggregateType<T extends ThreadMetadataAggregateArgs> = {
      [P in keyof T & keyof AggregateThreadMetadata]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateThreadMetadata[P]>
    : Prisma.GetScalarType<T[P], AggregateThreadMetadata[P]>
}




export type ThreadMetadataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ThreadMetadataWhereInput
  orderBy?: Prisma.ThreadMetadataOrderByWithAggregationInput | Prisma.ThreadMetadataOrderByWithAggregationInput[]
  by: Prisma.ThreadMetadataScalarFieldEnum[] | Prisma.ThreadMetadataScalarFieldEnum
  having?: Prisma.ThreadMetadataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ThreadMetadataCountAggregateInputType | true
  _avg?: ThreadMetadataAvgAggregateInputType
  _sum?: ThreadMetadataSumAggregateInputType
  _min?: ThreadMetadataMinAggregateInputType
  _max?: ThreadMetadataMaxAggregateInputType
}

export type ThreadMetadataGroupByOutputType = {
  thread_id: string
  agent_id: number | null
  type: string
  title: string | null
  archived: boolean
  created_at: Date
  updated_at: Date
  _count: ThreadMetadataCountAggregateOutputType | null
  _avg: ThreadMetadataAvgAggregateOutputType | null
  _sum: ThreadMetadataSumAggregateOutputType | null
  _min: ThreadMetadataMinAggregateOutputType | null
  _max: ThreadMetadataMaxAggregateOutputType | null
}

type GetThreadMetadataGroupByPayload<T extends ThreadMetadataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ThreadMetadataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ThreadMetadataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ThreadMetadataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ThreadMetadataGroupByOutputType[P]>
      }
    >
  >



export type ThreadMetadataWhereInput = {
  AND?: Prisma.ThreadMetadataWhereInput | Prisma.ThreadMetadataWhereInput[]
  OR?: Prisma.ThreadMetadataWhereInput[]
  NOT?: Prisma.ThreadMetadataWhereInput | Prisma.ThreadMetadataWhereInput[]
  thread_id?: Prisma.StringFilter<"ThreadMetadata"> | string
  agent_id?: Prisma.IntNullableFilter<"ThreadMetadata"> | number | null
  type?: Prisma.StringFilter<"ThreadMetadata"> | string
  title?: Prisma.StringNullableFilter<"ThreadMetadata"> | string | null
  archived?: Prisma.BoolFilter<"ThreadMetadata"> | boolean
  created_at?: Prisma.DateTimeFilter<"ThreadMetadata"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ThreadMetadata"> | Date | string
  agent?: Prisma.XOR<Prisma.AgentNullableScalarRelationFilter, Prisma.AgentWhereInput> | null
}

export type ThreadMetadataOrderByWithRelationInput = {
  thread_id?: Prisma.SortOrder
  agent_id?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  archived?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  agent?: Prisma.AgentOrderByWithRelationInput
}

export type ThreadMetadataWhereUniqueInput = Prisma.AtLeast<{
  thread_id?: string
  AND?: Prisma.ThreadMetadataWhereInput | Prisma.ThreadMetadataWhereInput[]
  OR?: Prisma.ThreadMetadataWhereInput[]
  NOT?: Prisma.ThreadMetadataWhereInput | Prisma.ThreadMetadataWhereInput[]
  agent_id?: Prisma.IntNullableFilter<"ThreadMetadata"> | number | null
  type?: Prisma.StringFilter<"ThreadMetadata"> | string
  title?: Prisma.StringNullableFilter<"ThreadMetadata"> | string | null
  archived?: Prisma.BoolFilter<"ThreadMetadata"> | boolean
  created_at?: Prisma.DateTimeFilter<"ThreadMetadata"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ThreadMetadata"> | Date | string
  agent?: Prisma.XOR<Prisma.AgentNullableScalarRelationFilter, Prisma.AgentWhereInput> | null
}, "thread_id">

export type ThreadMetadataOrderByWithAggregationInput = {
  thread_id?: Prisma.SortOrder
  agent_id?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  archived?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.ThreadMetadataCountOrderByAggregateInput
  _avg?: Prisma.ThreadMetadataAvgOrderByAggregateInput
  _max?: Prisma.ThreadMetadataMaxOrderByAggregateInput
  _min?: Prisma.ThreadMetadataMinOrderByAggregateInput
  _sum?: Prisma.ThreadMetadataSumOrderByAggregateInput
}

export type ThreadMetadataScalarWhereWithAggregatesInput = {
  AND?: Prisma.ThreadMetadataScalarWhereWithAggregatesInput | Prisma.ThreadMetadataScalarWhereWithAggregatesInput[]
  OR?: Prisma.ThreadMetadataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ThreadMetadataScalarWhereWithAggregatesInput | Prisma.ThreadMetadataScalarWhereWithAggregatesInput[]
  thread_id?: Prisma.StringWithAggregatesFilter<"ThreadMetadata"> | string
  agent_id?: Prisma.IntNullableWithAggregatesFilter<"ThreadMetadata"> | number | null
  type?: Prisma.StringWithAggregatesFilter<"ThreadMetadata"> | string
  title?: Prisma.StringNullableWithAggregatesFilter<"ThreadMetadata"> | string | null
  archived?: Prisma.BoolWithAggregatesFilter<"ThreadMetadata"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"ThreadMetadata"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"ThreadMetadata"> | Date | string
}

export type ThreadMetadataCreateInput = {
  thread_id: string
  type?: string
  title?: string | null
  archived?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  agent?: Prisma.AgentCreateNestedOneWithoutThread_metadataInput
}

export type ThreadMetadataUncheckedCreateInput = {
  thread_id: string
  agent_id?: number | null
  type?: string
  title?: string | null
  archived?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type ThreadMetadataUpdateInput = {
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agent?: Prisma.AgentUpdateOneWithoutThread_metadataNestedInput
}

export type ThreadMetadataUncheckedUpdateInput = {
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  agent_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ThreadMetadataCreateManyInput = {
  thread_id: string
  agent_id?: number | null
  type?: string
  title?: string | null
  archived?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type ThreadMetadataUpdateManyMutationInput = {
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ThreadMetadataUncheckedUpdateManyInput = {
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  agent_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ThreadMetadataListRelationFilter = {
  every?: Prisma.ThreadMetadataWhereInput
  some?: Prisma.ThreadMetadataWhereInput
  none?: Prisma.ThreadMetadataWhereInput
}

export type ThreadMetadataOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ThreadMetadataCountOrderByAggregateInput = {
  thread_id?: Prisma.SortOrder
  agent_id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ThreadMetadataAvgOrderByAggregateInput = {
  agent_id?: Prisma.SortOrder
}

export type ThreadMetadataMaxOrderByAggregateInput = {
  thread_id?: Prisma.SortOrder
  agent_id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ThreadMetadataMinOrderByAggregateInput = {
  thread_id?: Prisma.SortOrder
  agent_id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ThreadMetadataSumOrderByAggregateInput = {
  agent_id?: Prisma.SortOrder
}

export type ThreadMetadataCreateNestedManyWithoutAgentInput = {
  create?: Prisma.XOR<Prisma.ThreadMetadataCreateWithoutAgentInput, Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput> | Prisma.ThreadMetadataCreateWithoutAgentInput[] | Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.ThreadMetadataCreateOrConnectWithoutAgentInput | Prisma.ThreadMetadataCreateOrConnectWithoutAgentInput[]
  createMany?: Prisma.ThreadMetadataCreateManyAgentInputEnvelope
  connect?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
}

export type ThreadMetadataUncheckedCreateNestedManyWithoutAgentInput = {
  create?: Prisma.XOR<Prisma.ThreadMetadataCreateWithoutAgentInput, Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput> | Prisma.ThreadMetadataCreateWithoutAgentInput[] | Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.ThreadMetadataCreateOrConnectWithoutAgentInput | Prisma.ThreadMetadataCreateOrConnectWithoutAgentInput[]
  createMany?: Prisma.ThreadMetadataCreateManyAgentInputEnvelope
  connect?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
}

export type ThreadMetadataUpdateManyWithoutAgentNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadMetadataCreateWithoutAgentInput, Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput> | Prisma.ThreadMetadataCreateWithoutAgentInput[] | Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.ThreadMetadataCreateOrConnectWithoutAgentInput | Prisma.ThreadMetadataCreateOrConnectWithoutAgentInput[]
  upsert?: Prisma.ThreadMetadataUpsertWithWhereUniqueWithoutAgentInput | Prisma.ThreadMetadataUpsertWithWhereUniqueWithoutAgentInput[]
  createMany?: Prisma.ThreadMetadataCreateManyAgentInputEnvelope
  set?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
  disconnect?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
  delete?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
  connect?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
  update?: Prisma.ThreadMetadataUpdateWithWhereUniqueWithoutAgentInput | Prisma.ThreadMetadataUpdateWithWhereUniqueWithoutAgentInput[]
  updateMany?: Prisma.ThreadMetadataUpdateManyWithWhereWithoutAgentInput | Prisma.ThreadMetadataUpdateManyWithWhereWithoutAgentInput[]
  deleteMany?: Prisma.ThreadMetadataScalarWhereInput | Prisma.ThreadMetadataScalarWhereInput[]
}

export type ThreadMetadataUncheckedUpdateManyWithoutAgentNestedInput = {
  create?: Prisma.XOR<Prisma.ThreadMetadataCreateWithoutAgentInput, Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput> | Prisma.ThreadMetadataCreateWithoutAgentInput[] | Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.ThreadMetadataCreateOrConnectWithoutAgentInput | Prisma.ThreadMetadataCreateOrConnectWithoutAgentInput[]
  upsert?: Prisma.ThreadMetadataUpsertWithWhereUniqueWithoutAgentInput | Prisma.ThreadMetadataUpsertWithWhereUniqueWithoutAgentInput[]
  createMany?: Prisma.ThreadMetadataCreateManyAgentInputEnvelope
  set?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
  disconnect?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
  delete?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
  connect?: Prisma.ThreadMetadataWhereUniqueInput | Prisma.ThreadMetadataWhereUniqueInput[]
  update?: Prisma.ThreadMetadataUpdateWithWhereUniqueWithoutAgentInput | Prisma.ThreadMetadataUpdateWithWhereUniqueWithoutAgentInput[]
  updateMany?: Prisma.ThreadMetadataUpdateManyWithWhereWithoutAgentInput | Prisma.ThreadMetadataUpdateManyWithWhereWithoutAgentInput[]
  deleteMany?: Prisma.ThreadMetadataScalarWhereInput | Prisma.ThreadMetadataScalarWhereInput[]
}

export type ThreadMetadataCreateWithoutAgentInput = {
  thread_id: string
  type?: string
  title?: string | null
  archived?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type ThreadMetadataUncheckedCreateWithoutAgentInput = {
  thread_id: string
  type?: string
  title?: string | null
  archived?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type ThreadMetadataCreateOrConnectWithoutAgentInput = {
  where: Prisma.ThreadMetadataWhereUniqueInput
  create: Prisma.XOR<Prisma.ThreadMetadataCreateWithoutAgentInput, Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput>
}

export type ThreadMetadataCreateManyAgentInputEnvelope = {
  data: Prisma.ThreadMetadataCreateManyAgentInput | Prisma.ThreadMetadataCreateManyAgentInput[]
}

export type ThreadMetadataUpsertWithWhereUniqueWithoutAgentInput = {
  where: Prisma.ThreadMetadataWhereUniqueInput
  update: Prisma.XOR<Prisma.ThreadMetadataUpdateWithoutAgentInput, Prisma.ThreadMetadataUncheckedUpdateWithoutAgentInput>
  create: Prisma.XOR<Prisma.ThreadMetadataCreateWithoutAgentInput, Prisma.ThreadMetadataUncheckedCreateWithoutAgentInput>
}

export type ThreadMetadataUpdateWithWhereUniqueWithoutAgentInput = {
  where: Prisma.ThreadMetadataWhereUniqueInput
  data: Prisma.XOR<Prisma.ThreadMetadataUpdateWithoutAgentInput, Prisma.ThreadMetadataUncheckedUpdateWithoutAgentInput>
}

export type ThreadMetadataUpdateManyWithWhereWithoutAgentInput = {
  where: Prisma.ThreadMetadataScalarWhereInput
  data: Prisma.XOR<Prisma.ThreadMetadataUpdateManyMutationInput, Prisma.ThreadMetadataUncheckedUpdateManyWithoutAgentInput>
}

export type ThreadMetadataScalarWhereInput = {
  AND?: Prisma.ThreadMetadataScalarWhereInput | Prisma.ThreadMetadataScalarWhereInput[]
  OR?: Prisma.ThreadMetadataScalarWhereInput[]
  NOT?: Prisma.ThreadMetadataScalarWhereInput | Prisma.ThreadMetadataScalarWhereInput[]
  thread_id?: Prisma.StringFilter<"ThreadMetadata"> | string
  agent_id?: Prisma.IntNullableFilter<"ThreadMetadata"> | number | null
  type?: Prisma.StringFilter<"ThreadMetadata"> | string
  title?: Prisma.StringNullableFilter<"ThreadMetadata"> | string | null
  archived?: Prisma.BoolFilter<"ThreadMetadata"> | boolean
  created_at?: Prisma.DateTimeFilter<"ThreadMetadata"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ThreadMetadata"> | Date | string
}

export type ThreadMetadataCreateManyAgentInput = {
  thread_id: string
  type?: string
  title?: string | null
  archived?: boolean
  created_at?: Date | string
  updated_at?: Date | string
}

export type ThreadMetadataUpdateWithoutAgentInput = {
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ThreadMetadataUncheckedUpdateWithoutAgentInput = {
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ThreadMetadataUncheckedUpdateManyWithoutAgentInput = {
  thread_id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ThreadMetadataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  thread_id?: boolean
  agent_id?: boolean
  type?: boolean
  title?: boolean
  archived?: boolean
  created_at?: boolean
  updated_at?: boolean
  agent?: boolean | Prisma.ThreadMetadata$agentArgs<ExtArgs>
}, ExtArgs["result"]["threadMetadata"]>

export type ThreadMetadataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  thread_id?: boolean
  agent_id?: boolean
  type?: boolean
  title?: boolean
  archived?: boolean
  created_at?: boolean
  updated_at?: boolean
  agent?: boolean | Prisma.ThreadMetadata$agentArgs<ExtArgs>
}, ExtArgs["result"]["threadMetadata"]>

export type ThreadMetadataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  thread_id?: boolean
  agent_id?: boolean
  type?: boolean
  title?: boolean
  archived?: boolean
  created_at?: boolean
  updated_at?: boolean
  agent?: boolean | Prisma.ThreadMetadata$agentArgs<ExtArgs>
}, ExtArgs["result"]["threadMetadata"]>

export type ThreadMetadataSelectScalar = {
  thread_id?: boolean
  agent_id?: boolean
  type?: boolean
  title?: boolean
  archived?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type ThreadMetadataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"thread_id" | "agent_id" | "type" | "title" | "archived" | "created_at" | "updated_at", ExtArgs["result"]["threadMetadata"]>
export type ThreadMetadataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agent?: boolean | Prisma.ThreadMetadata$agentArgs<ExtArgs>
}
export type ThreadMetadataIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agent?: boolean | Prisma.ThreadMetadata$agentArgs<ExtArgs>
}
export type ThreadMetadataIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agent?: boolean | Prisma.ThreadMetadata$agentArgs<ExtArgs>
}

export type $ThreadMetadataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ThreadMetadata"
  objects: {
    agent: Prisma.$AgentPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    thread_id: string
    agent_id: number | null
    type: string
    title: string | null
    archived: boolean
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["threadMetadata"]>
  composites: {}
}

export type ThreadMetadataGetPayload<S extends boolean | null | undefined | ThreadMetadataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload, S>

export type ThreadMetadataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ThreadMetadataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ThreadMetadataCountAggregateInputType | true
  }

export interface ThreadMetadataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ThreadMetadata'], meta: { name: 'ThreadMetadata' } }
  /**
   * Find zero or one ThreadMetadata that matches the filter.
   * @param {ThreadMetadataFindUniqueArgs} args - Arguments to find a ThreadMetadata
   * @example
   * // Get one ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ThreadMetadataFindUniqueArgs>(args: Prisma.SelectSubset<T, ThreadMetadataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ThreadMetadataClient<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ThreadMetadata that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ThreadMetadataFindUniqueOrThrowArgs} args - Arguments to find a ThreadMetadata
   * @example
   * // Get one ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ThreadMetadataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ThreadMetadataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ThreadMetadataClient<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ThreadMetadata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadMetadataFindFirstArgs} args - Arguments to find a ThreadMetadata
   * @example
   * // Get one ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ThreadMetadataFindFirstArgs>(args?: Prisma.SelectSubset<T, ThreadMetadataFindFirstArgs<ExtArgs>>): Prisma.Prisma__ThreadMetadataClient<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ThreadMetadata that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadMetadataFindFirstOrThrowArgs} args - Arguments to find a ThreadMetadata
   * @example
   * // Get one ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ThreadMetadataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ThreadMetadataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ThreadMetadataClient<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ThreadMetadata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadMetadataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.findMany()
   * 
   * // Get first 10 ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.findMany({ take: 10 })
   * 
   * // Only select the `thread_id`
   * const threadMetadataWithThread_idOnly = await prisma.threadMetadata.findMany({ select: { thread_id: true } })
   * 
   */
  findMany<T extends ThreadMetadataFindManyArgs>(args?: Prisma.SelectSubset<T, ThreadMetadataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ThreadMetadata.
   * @param {ThreadMetadataCreateArgs} args - Arguments to create a ThreadMetadata.
   * @example
   * // Create one ThreadMetadata
   * const ThreadMetadata = await prisma.threadMetadata.create({
   *   data: {
   *     // ... data to create a ThreadMetadata
   *   }
   * })
   * 
   */
  create<T extends ThreadMetadataCreateArgs>(args: Prisma.SelectSubset<T, ThreadMetadataCreateArgs<ExtArgs>>): Prisma.Prisma__ThreadMetadataClient<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ThreadMetadata.
   * @param {ThreadMetadataCreateManyArgs} args - Arguments to create many ThreadMetadata.
   * @example
   * // Create many ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ThreadMetadataCreateManyArgs>(args?: Prisma.SelectSubset<T, ThreadMetadataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ThreadMetadata and returns the data saved in the database.
   * @param {ThreadMetadataCreateManyAndReturnArgs} args - Arguments to create many ThreadMetadata.
   * @example
   * // Create many ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ThreadMetadata and only return the `thread_id`
   * const threadMetadataWithThread_idOnly = await prisma.threadMetadata.createManyAndReturn({
   *   select: { thread_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ThreadMetadataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ThreadMetadataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ThreadMetadata.
   * @param {ThreadMetadataDeleteArgs} args - Arguments to delete one ThreadMetadata.
   * @example
   * // Delete one ThreadMetadata
   * const ThreadMetadata = await prisma.threadMetadata.delete({
   *   where: {
   *     // ... filter to delete one ThreadMetadata
   *   }
   * })
   * 
   */
  delete<T extends ThreadMetadataDeleteArgs>(args: Prisma.SelectSubset<T, ThreadMetadataDeleteArgs<ExtArgs>>): Prisma.Prisma__ThreadMetadataClient<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ThreadMetadata.
   * @param {ThreadMetadataUpdateArgs} args - Arguments to update one ThreadMetadata.
   * @example
   * // Update one ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ThreadMetadataUpdateArgs>(args: Prisma.SelectSubset<T, ThreadMetadataUpdateArgs<ExtArgs>>): Prisma.Prisma__ThreadMetadataClient<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ThreadMetadata.
   * @param {ThreadMetadataDeleteManyArgs} args - Arguments to filter ThreadMetadata to delete.
   * @example
   * // Delete a few ThreadMetadata
   * const { count } = await prisma.threadMetadata.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ThreadMetadataDeleteManyArgs>(args?: Prisma.SelectSubset<T, ThreadMetadataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ThreadMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadMetadataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ThreadMetadataUpdateManyArgs>(args: Prisma.SelectSubset<T, ThreadMetadataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ThreadMetadata and returns the data updated in the database.
   * @param {ThreadMetadataUpdateManyAndReturnArgs} args - Arguments to update many ThreadMetadata.
   * @example
   * // Update many ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ThreadMetadata and only return the `thread_id`
   * const threadMetadataWithThread_idOnly = await prisma.threadMetadata.updateManyAndReturn({
   *   select: { thread_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ThreadMetadataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ThreadMetadataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ThreadMetadata.
   * @param {ThreadMetadataUpsertArgs} args - Arguments to update or create a ThreadMetadata.
   * @example
   * // Update or create a ThreadMetadata
   * const threadMetadata = await prisma.threadMetadata.upsert({
   *   create: {
   *     // ... data to create a ThreadMetadata
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ThreadMetadata we want to update
   *   }
   * })
   */
  upsert<T extends ThreadMetadataUpsertArgs>(args: Prisma.SelectSubset<T, ThreadMetadataUpsertArgs<ExtArgs>>): Prisma.Prisma__ThreadMetadataClient<runtime.Types.Result.GetResult<Prisma.$ThreadMetadataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ThreadMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadMetadataCountArgs} args - Arguments to filter ThreadMetadata to count.
   * @example
   * // Count the number of ThreadMetadata
   * const count = await prisma.threadMetadata.count({
   *   where: {
   *     // ... the filter for the ThreadMetadata we want to count
   *   }
   * })
  **/
  count<T extends ThreadMetadataCountArgs>(
    args?: Prisma.Subset<T, ThreadMetadataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ThreadMetadataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ThreadMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadMetadataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ThreadMetadataAggregateArgs>(args: Prisma.Subset<T, ThreadMetadataAggregateArgs>): Prisma.PrismaPromise<GetThreadMetadataAggregateType<T>>

  /**
   * Group by ThreadMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadMetadataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ThreadMetadataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ThreadMetadataGroupByArgs['orderBy'] }
      : { orderBy?: ThreadMetadataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ThreadMetadataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetThreadMetadataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ThreadMetadata model
 */
readonly fields: ThreadMetadataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ThreadMetadata.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ThreadMetadataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  agent<T extends Prisma.ThreadMetadata$agentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ThreadMetadata$agentArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ThreadMetadata model
 */
export interface ThreadMetadataFieldRefs {
  readonly thread_id: Prisma.FieldRef<"ThreadMetadata", 'String'>
  readonly agent_id: Prisma.FieldRef<"ThreadMetadata", 'Int'>
  readonly type: Prisma.FieldRef<"ThreadMetadata", 'String'>
  readonly title: Prisma.FieldRef<"ThreadMetadata", 'String'>
  readonly archived: Prisma.FieldRef<"ThreadMetadata", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"ThreadMetadata", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"ThreadMetadata", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ThreadMetadata findUnique
 */
export type ThreadMetadataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * Filter, which ThreadMetadata to fetch.
   */
  where: Prisma.ThreadMetadataWhereUniqueInput
}

/**
 * ThreadMetadata findUniqueOrThrow
 */
export type ThreadMetadataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * Filter, which ThreadMetadata to fetch.
   */
  where: Prisma.ThreadMetadataWhereUniqueInput
}

/**
 * ThreadMetadata findFirst
 */
export type ThreadMetadataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * Filter, which ThreadMetadata to fetch.
   */
  where?: Prisma.ThreadMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ThreadMetadata to fetch.
   */
  orderBy?: Prisma.ThreadMetadataOrderByWithRelationInput | Prisma.ThreadMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ThreadMetadata.
   */
  cursor?: Prisma.ThreadMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ThreadMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ThreadMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ThreadMetadata.
   */
  distinct?: Prisma.ThreadMetadataScalarFieldEnum | Prisma.ThreadMetadataScalarFieldEnum[]
}

/**
 * ThreadMetadata findFirstOrThrow
 */
export type ThreadMetadataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * Filter, which ThreadMetadata to fetch.
   */
  where?: Prisma.ThreadMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ThreadMetadata to fetch.
   */
  orderBy?: Prisma.ThreadMetadataOrderByWithRelationInput | Prisma.ThreadMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ThreadMetadata.
   */
  cursor?: Prisma.ThreadMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ThreadMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ThreadMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ThreadMetadata.
   */
  distinct?: Prisma.ThreadMetadataScalarFieldEnum | Prisma.ThreadMetadataScalarFieldEnum[]
}

/**
 * ThreadMetadata findMany
 */
export type ThreadMetadataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * Filter, which ThreadMetadata to fetch.
   */
  where?: Prisma.ThreadMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ThreadMetadata to fetch.
   */
  orderBy?: Prisma.ThreadMetadataOrderByWithRelationInput | Prisma.ThreadMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ThreadMetadata.
   */
  cursor?: Prisma.ThreadMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ThreadMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ThreadMetadata.
   */
  skip?: number
  distinct?: Prisma.ThreadMetadataScalarFieldEnum | Prisma.ThreadMetadataScalarFieldEnum[]
}

/**
 * ThreadMetadata create
 */
export type ThreadMetadataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * The data needed to create a ThreadMetadata.
   */
  data: Prisma.XOR<Prisma.ThreadMetadataCreateInput, Prisma.ThreadMetadataUncheckedCreateInput>
}

/**
 * ThreadMetadata createMany
 */
export type ThreadMetadataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ThreadMetadata.
   */
  data: Prisma.ThreadMetadataCreateManyInput | Prisma.ThreadMetadataCreateManyInput[]
}

/**
 * ThreadMetadata createManyAndReturn
 */
export type ThreadMetadataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * The data used to create many ThreadMetadata.
   */
  data: Prisma.ThreadMetadataCreateManyInput | Prisma.ThreadMetadataCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ThreadMetadata update
 */
export type ThreadMetadataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * The data needed to update a ThreadMetadata.
   */
  data: Prisma.XOR<Prisma.ThreadMetadataUpdateInput, Prisma.ThreadMetadataUncheckedUpdateInput>
  /**
   * Choose, which ThreadMetadata to update.
   */
  where: Prisma.ThreadMetadataWhereUniqueInput
}

/**
 * ThreadMetadata updateMany
 */
export type ThreadMetadataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ThreadMetadata.
   */
  data: Prisma.XOR<Prisma.ThreadMetadataUpdateManyMutationInput, Prisma.ThreadMetadataUncheckedUpdateManyInput>
  /**
   * Filter which ThreadMetadata to update
   */
  where?: Prisma.ThreadMetadataWhereInput
  /**
   * Limit how many ThreadMetadata to update.
   */
  limit?: number
}

/**
 * ThreadMetadata updateManyAndReturn
 */
export type ThreadMetadataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * The data used to update ThreadMetadata.
   */
  data: Prisma.XOR<Prisma.ThreadMetadataUpdateManyMutationInput, Prisma.ThreadMetadataUncheckedUpdateManyInput>
  /**
   * Filter which ThreadMetadata to update
   */
  where?: Prisma.ThreadMetadataWhereInput
  /**
   * Limit how many ThreadMetadata to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ThreadMetadata upsert
 */
export type ThreadMetadataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * The filter to search for the ThreadMetadata to update in case it exists.
   */
  where: Prisma.ThreadMetadataWhereUniqueInput
  /**
   * In case the ThreadMetadata found by the `where` argument doesn't exist, create a new ThreadMetadata with this data.
   */
  create: Prisma.XOR<Prisma.ThreadMetadataCreateInput, Prisma.ThreadMetadataUncheckedCreateInput>
  /**
   * In case the ThreadMetadata was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ThreadMetadataUpdateInput, Prisma.ThreadMetadataUncheckedUpdateInput>
}

/**
 * ThreadMetadata delete
 */
export type ThreadMetadataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
  /**
   * Filter which ThreadMetadata to delete.
   */
  where: Prisma.ThreadMetadataWhereUniqueInput
}

/**
 * ThreadMetadata deleteMany
 */
export type ThreadMetadataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ThreadMetadata to delete
   */
  where?: Prisma.ThreadMetadataWhereInput
  /**
   * Limit how many ThreadMetadata to delete.
   */
  limit?: number
}

/**
 * ThreadMetadata.agent
 */
export type ThreadMetadata$agentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Agent
   */
  select?: Prisma.AgentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Agent
   */
  omit?: Prisma.AgentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentInclude<ExtArgs> | null
  where?: Prisma.AgentWhereInput
}

/**
 * ThreadMetadata without action
 */
export type ThreadMetadataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ThreadMetadata
   */
  select?: Prisma.ThreadMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ThreadMetadata
   */
  omit?: Prisma.ThreadMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadMetadataInclude<ExtArgs> | null
}
