
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tool` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Tool
 * 
 */
export type ToolModel = runtime.Types.Result.DefaultSelection<Prisma.$ToolPayload>

export type AggregateTool = {
  _count: ToolCountAggregateOutputType | null
  _avg: ToolAvgAggregateOutputType | null
  _sum: ToolSumAggregateOutputType | null
  _min: ToolMinAggregateOutputType | null
  _max: ToolMaxAggregateOutputType | null
}

export type ToolAvgAggregateOutputType = {
  tool_id: number | null
  mcp_server_id: number | null
  locked_tier: number | null
}

export type ToolSumAggregateOutputType = {
  tool_id: number | null
  mcp_server_id: number | null
  locked_tier: number | null
}

export type ToolMinAggregateOutputType = {
  tool_id: number | null
  id: string | null
  name: string | null
  description: string | null
  source: string | null
  mcp_server_id: number | null
  locked_tier: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type ToolMaxAggregateOutputType = {
  tool_id: number | null
  id: string | null
  name: string | null
  description: string | null
  source: string | null
  mcp_server_id: number | null
  locked_tier: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type ToolCountAggregateOutputType = {
  tool_id: number
  id: number
  name: number
  description: number
  source: number
  mcp_server_id: number
  locked_tier: number
  input_schema: number
  output_schema: number
  created_at: number
  updated_at: number
  _all: number
}


export type ToolAvgAggregateInputType = {
  tool_id?: true
  mcp_server_id?: true
  locked_tier?: true
}

export type ToolSumAggregateInputType = {
  tool_id?: true
  mcp_server_id?: true
  locked_tier?: true
}

export type ToolMinAggregateInputType = {
  tool_id?: true
  id?: true
  name?: true
  description?: true
  source?: true
  mcp_server_id?: true
  locked_tier?: true
  created_at?: true
  updated_at?: true
}

export type ToolMaxAggregateInputType = {
  tool_id?: true
  id?: true
  name?: true
  description?: true
  source?: true
  mcp_server_id?: true
  locked_tier?: true
  created_at?: true
  updated_at?: true
}

export type ToolCountAggregateInputType = {
  tool_id?: true
  id?: true
  name?: true
  description?: true
  source?: true
  mcp_server_id?: true
  locked_tier?: true
  input_schema?: true
  output_schema?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type ToolAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tool to aggregate.
   */
  where?: Prisma.ToolWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tools to fetch.
   */
  orderBy?: Prisma.ToolOrderByWithRelationInput | Prisma.ToolOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ToolWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tools from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tools.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tools
  **/
  _count?: true | ToolCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ToolAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ToolSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ToolMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ToolMaxAggregateInputType
}

export type GetToolAggregateType<T extends ToolAggregateArgs> = {
      [P in keyof T & keyof AggregateTool]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTool[P]>
    : Prisma.GetScalarType<T[P], AggregateTool[P]>
}




export type ToolGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ToolWhereInput
  orderBy?: Prisma.ToolOrderByWithAggregationInput | Prisma.ToolOrderByWithAggregationInput[]
  by: Prisma.ToolScalarFieldEnum[] | Prisma.ToolScalarFieldEnum
  having?: Prisma.ToolScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ToolCountAggregateInputType | true
  _avg?: ToolAvgAggregateInputType
  _sum?: ToolSumAggregateInputType
  _min?: ToolMinAggregateInputType
  _max?: ToolMaxAggregateInputType
}

export type ToolGroupByOutputType = {
  tool_id: number
  id: string
  name: string
  description: string
  source: string
  mcp_server_id: number | null
  locked_tier: number | null
  input_schema: runtime.JsonValue
  output_schema: runtime.JsonValue | null
  created_at: Date
  updated_at: Date
  _count: ToolCountAggregateOutputType | null
  _avg: ToolAvgAggregateOutputType | null
  _sum: ToolSumAggregateOutputType | null
  _min: ToolMinAggregateOutputType | null
  _max: ToolMaxAggregateOutputType | null
}

type GetToolGroupByPayload<T extends ToolGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ToolGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ToolGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ToolGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ToolGroupByOutputType[P]>
      }
    >
  >



export type ToolWhereInput = {
  AND?: Prisma.ToolWhereInput | Prisma.ToolWhereInput[]
  OR?: Prisma.ToolWhereInput[]
  NOT?: Prisma.ToolWhereInput | Prisma.ToolWhereInput[]
  tool_id?: Prisma.IntFilter<"Tool"> | number
  id?: Prisma.StringFilter<"Tool"> | string
  name?: Prisma.StringFilter<"Tool"> | string
  description?: Prisma.StringFilter<"Tool"> | string
  source?: Prisma.StringFilter<"Tool"> | string
  mcp_server_id?: Prisma.IntNullableFilter<"Tool"> | number | null
  locked_tier?: Prisma.IntNullableFilter<"Tool"> | number | null
  input_schema?: Prisma.JsonFilter<"Tool">
  output_schema?: Prisma.JsonNullableFilter<"Tool">
  created_at?: Prisma.DateTimeFilter<"Tool"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Tool"> | Date | string
  mcp_server?: Prisma.XOR<Prisma.McpServerNullableScalarRelationFilter, Prisma.McpServerWhereInput> | null
  agent_tools?: Prisma.AgentToolListRelationFilter
  evaluation_tools?: Prisma.EvaluationToolListRelationFilter
}

export type ToolOrderByWithRelationInput = {
  tool_id?: Prisma.SortOrder
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  source?: Prisma.SortOrder
  mcp_server_id?: Prisma.SortOrderInput | Prisma.SortOrder
  locked_tier?: Prisma.SortOrderInput | Prisma.SortOrder
  input_schema?: Prisma.SortOrder
  output_schema?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  mcp_server?: Prisma.McpServerOrderByWithRelationInput
  agent_tools?: Prisma.AgentToolOrderByRelationAggregateInput
  evaluation_tools?: Prisma.EvaluationToolOrderByRelationAggregateInput
}

export type ToolWhereUniqueInput = Prisma.AtLeast<{
  tool_id?: number
  id?: string
  AND?: Prisma.ToolWhereInput | Prisma.ToolWhereInput[]
  OR?: Prisma.ToolWhereInput[]
  NOT?: Prisma.ToolWhereInput | Prisma.ToolWhereInput[]
  name?: Prisma.StringFilter<"Tool"> | string
  description?: Prisma.StringFilter<"Tool"> | string
  source?: Prisma.StringFilter<"Tool"> | string
  mcp_server_id?: Prisma.IntNullableFilter<"Tool"> | number | null
  locked_tier?: Prisma.IntNullableFilter<"Tool"> | number | null
  input_schema?: Prisma.JsonFilter<"Tool">
  output_schema?: Prisma.JsonNullableFilter<"Tool">
  created_at?: Prisma.DateTimeFilter<"Tool"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Tool"> | Date | string
  mcp_server?: Prisma.XOR<Prisma.McpServerNullableScalarRelationFilter, Prisma.McpServerWhereInput> | null
  agent_tools?: Prisma.AgentToolListRelationFilter
  evaluation_tools?: Prisma.EvaluationToolListRelationFilter
}, "tool_id" | "id">

export type ToolOrderByWithAggregationInput = {
  tool_id?: Prisma.SortOrder
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  source?: Prisma.SortOrder
  mcp_server_id?: Prisma.SortOrderInput | Prisma.SortOrder
  locked_tier?: Prisma.SortOrderInput | Prisma.SortOrder
  input_schema?: Prisma.SortOrder
  output_schema?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.ToolCountOrderByAggregateInput
  _avg?: Prisma.ToolAvgOrderByAggregateInput
  _max?: Prisma.ToolMaxOrderByAggregateInput
  _min?: Prisma.ToolMinOrderByAggregateInput
  _sum?: Prisma.ToolSumOrderByAggregateInput
}

export type ToolScalarWhereWithAggregatesInput = {
  AND?: Prisma.ToolScalarWhereWithAggregatesInput | Prisma.ToolScalarWhereWithAggregatesInput[]
  OR?: Prisma.ToolScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ToolScalarWhereWithAggregatesInput | Prisma.ToolScalarWhereWithAggregatesInput[]
  tool_id?: Prisma.IntWithAggregatesFilter<"Tool"> | number
  id?: Prisma.StringWithAggregatesFilter<"Tool"> | string
  name?: Prisma.StringWithAggregatesFilter<"Tool"> | string
  description?: Prisma.StringWithAggregatesFilter<"Tool"> | string
  source?: Prisma.StringWithAggregatesFilter<"Tool"> | string
  mcp_server_id?: Prisma.IntNullableWithAggregatesFilter<"Tool"> | number | null
  locked_tier?: Prisma.IntNullableWithAggregatesFilter<"Tool"> | number | null
  input_schema?: Prisma.JsonWithAggregatesFilter<"Tool">
  output_schema?: Prisma.JsonNullableWithAggregatesFilter<"Tool">
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Tool"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Tool"> | Date | string
}

export type ToolCreateInput = {
  id: string
  name: string
  description: string
  source: string
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  mcp_server?: Prisma.McpServerCreateNestedOneWithoutToolsInput
  agent_tools?: Prisma.AgentToolCreateNestedManyWithoutToolInput
  evaluation_tools?: Prisma.EvaluationToolCreateNestedManyWithoutToolInput
}

export type ToolUncheckedCreateInput = {
  tool_id?: number
  id: string
  name: string
  description: string
  source: string
  mcp_server_id?: number | null
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  agent_tools?: Prisma.AgentToolUncheckedCreateNestedManyWithoutToolInput
  evaluation_tools?: Prisma.EvaluationToolUncheckedCreateNestedManyWithoutToolInput
}

export type ToolUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mcp_server?: Prisma.McpServerUpdateOneWithoutToolsNestedInput
  agent_tools?: Prisma.AgentToolUpdateManyWithoutToolNestedInput
  evaluation_tools?: Prisma.EvaluationToolUpdateManyWithoutToolNestedInput
}

export type ToolUncheckedUpdateInput = {
  tool_id?: Prisma.IntFieldUpdateOperationsInput | number
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  mcp_server_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agent_tools?: Prisma.AgentToolUncheckedUpdateManyWithoutToolNestedInput
  evaluation_tools?: Prisma.EvaluationToolUncheckedUpdateManyWithoutToolNestedInput
}

export type ToolCreateManyInput = {
  tool_id?: number
  id: string
  name: string
  description: string
  source: string
  mcp_server_id?: number | null
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
}

export type ToolUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolUncheckedUpdateManyInput = {
  tool_id?: Prisma.IntFieldUpdateOperationsInput | number
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  mcp_server_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolListRelationFilter = {
  every?: Prisma.ToolWhereInput
  some?: Prisma.ToolWhereInput
  none?: Prisma.ToolWhereInput
}

export type ToolOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ToolCountOrderByAggregateInput = {
  tool_id?: Prisma.SortOrder
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  source?: Prisma.SortOrder
  mcp_server_id?: Prisma.SortOrder
  locked_tier?: Prisma.SortOrder
  input_schema?: Prisma.SortOrder
  output_schema?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ToolAvgOrderByAggregateInput = {
  tool_id?: Prisma.SortOrder
  mcp_server_id?: Prisma.SortOrder
  locked_tier?: Prisma.SortOrder
}

export type ToolMaxOrderByAggregateInput = {
  tool_id?: Prisma.SortOrder
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  source?: Prisma.SortOrder
  mcp_server_id?: Prisma.SortOrder
  locked_tier?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ToolMinOrderByAggregateInput = {
  tool_id?: Prisma.SortOrder
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  source?: Prisma.SortOrder
  mcp_server_id?: Prisma.SortOrder
  locked_tier?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ToolSumOrderByAggregateInput = {
  tool_id?: Prisma.SortOrder
  mcp_server_id?: Prisma.SortOrder
  locked_tier?: Prisma.SortOrder
}

export type ToolScalarRelationFilter = {
  is?: Prisma.ToolWhereInput
  isNot?: Prisma.ToolWhereInput
}

export type ToolCreateNestedManyWithoutMcp_serverInput = {
  create?: Prisma.XOR<Prisma.ToolCreateWithoutMcp_serverInput, Prisma.ToolUncheckedCreateWithoutMcp_serverInput> | Prisma.ToolCreateWithoutMcp_serverInput[] | Prisma.ToolUncheckedCreateWithoutMcp_serverInput[]
  connectOrCreate?: Prisma.ToolCreateOrConnectWithoutMcp_serverInput | Prisma.ToolCreateOrConnectWithoutMcp_serverInput[]
  createMany?: Prisma.ToolCreateManyMcp_serverInputEnvelope
  connect?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
}

export type ToolUncheckedCreateNestedManyWithoutMcp_serverInput = {
  create?: Prisma.XOR<Prisma.ToolCreateWithoutMcp_serverInput, Prisma.ToolUncheckedCreateWithoutMcp_serverInput> | Prisma.ToolCreateWithoutMcp_serverInput[] | Prisma.ToolUncheckedCreateWithoutMcp_serverInput[]
  connectOrCreate?: Prisma.ToolCreateOrConnectWithoutMcp_serverInput | Prisma.ToolCreateOrConnectWithoutMcp_serverInput[]
  createMany?: Prisma.ToolCreateManyMcp_serverInputEnvelope
  connect?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
}

export type ToolUpdateManyWithoutMcp_serverNestedInput = {
  create?: Prisma.XOR<Prisma.ToolCreateWithoutMcp_serverInput, Prisma.ToolUncheckedCreateWithoutMcp_serverInput> | Prisma.ToolCreateWithoutMcp_serverInput[] | Prisma.ToolUncheckedCreateWithoutMcp_serverInput[]
  connectOrCreate?: Prisma.ToolCreateOrConnectWithoutMcp_serverInput | Prisma.ToolCreateOrConnectWithoutMcp_serverInput[]
  upsert?: Prisma.ToolUpsertWithWhereUniqueWithoutMcp_serverInput | Prisma.ToolUpsertWithWhereUniqueWithoutMcp_serverInput[]
  createMany?: Prisma.ToolCreateManyMcp_serverInputEnvelope
  set?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
  disconnect?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
  delete?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
  connect?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
  update?: Prisma.ToolUpdateWithWhereUniqueWithoutMcp_serverInput | Prisma.ToolUpdateWithWhereUniqueWithoutMcp_serverInput[]
  updateMany?: Prisma.ToolUpdateManyWithWhereWithoutMcp_serverInput | Prisma.ToolUpdateManyWithWhereWithoutMcp_serverInput[]
  deleteMany?: Prisma.ToolScalarWhereInput | Prisma.ToolScalarWhereInput[]
}

export type ToolUncheckedUpdateManyWithoutMcp_serverNestedInput = {
  create?: Prisma.XOR<Prisma.ToolCreateWithoutMcp_serverInput, Prisma.ToolUncheckedCreateWithoutMcp_serverInput> | Prisma.ToolCreateWithoutMcp_serverInput[] | Prisma.ToolUncheckedCreateWithoutMcp_serverInput[]
  connectOrCreate?: Prisma.ToolCreateOrConnectWithoutMcp_serverInput | Prisma.ToolCreateOrConnectWithoutMcp_serverInput[]
  upsert?: Prisma.ToolUpsertWithWhereUniqueWithoutMcp_serverInput | Prisma.ToolUpsertWithWhereUniqueWithoutMcp_serverInput[]
  createMany?: Prisma.ToolCreateManyMcp_serverInputEnvelope
  set?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
  disconnect?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
  delete?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
  connect?: Prisma.ToolWhereUniqueInput | Prisma.ToolWhereUniqueInput[]
  update?: Prisma.ToolUpdateWithWhereUniqueWithoutMcp_serverInput | Prisma.ToolUpdateWithWhereUniqueWithoutMcp_serverInput[]
  updateMany?: Prisma.ToolUpdateManyWithWhereWithoutMcp_serverInput | Prisma.ToolUpdateManyWithWhereWithoutMcp_serverInput[]
  deleteMany?: Prisma.ToolScalarWhereInput | Prisma.ToolScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ToolCreateNestedOneWithoutAgent_toolsInput = {
  create?: Prisma.XOR<Prisma.ToolCreateWithoutAgent_toolsInput, Prisma.ToolUncheckedCreateWithoutAgent_toolsInput>
  connectOrCreate?: Prisma.ToolCreateOrConnectWithoutAgent_toolsInput
  connect?: Prisma.ToolWhereUniqueInput
}

export type ToolUpdateOneRequiredWithoutAgent_toolsNestedInput = {
  create?: Prisma.XOR<Prisma.ToolCreateWithoutAgent_toolsInput, Prisma.ToolUncheckedCreateWithoutAgent_toolsInput>
  connectOrCreate?: Prisma.ToolCreateOrConnectWithoutAgent_toolsInput
  upsert?: Prisma.ToolUpsertWithoutAgent_toolsInput
  connect?: Prisma.ToolWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ToolUpdateToOneWithWhereWithoutAgent_toolsInput, Prisma.ToolUpdateWithoutAgent_toolsInput>, Prisma.ToolUncheckedUpdateWithoutAgent_toolsInput>
}

export type ToolCreateNestedOneWithoutEvaluation_toolsInput = {
  create?: Prisma.XOR<Prisma.ToolCreateWithoutEvaluation_toolsInput, Prisma.ToolUncheckedCreateWithoutEvaluation_toolsInput>
  connectOrCreate?: Prisma.ToolCreateOrConnectWithoutEvaluation_toolsInput
  connect?: Prisma.ToolWhereUniqueInput
}

export type ToolUpdateOneRequiredWithoutEvaluation_toolsNestedInput = {
  create?: Prisma.XOR<Prisma.ToolCreateWithoutEvaluation_toolsInput, Prisma.ToolUncheckedCreateWithoutEvaluation_toolsInput>
  connectOrCreate?: Prisma.ToolCreateOrConnectWithoutEvaluation_toolsInput
  upsert?: Prisma.ToolUpsertWithoutEvaluation_toolsInput
  connect?: Prisma.ToolWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ToolUpdateToOneWithWhereWithoutEvaluation_toolsInput, Prisma.ToolUpdateWithoutEvaluation_toolsInput>, Prisma.ToolUncheckedUpdateWithoutEvaluation_toolsInput>
}

export type ToolCreateWithoutMcp_serverInput = {
  id: string
  name: string
  description: string
  source: string
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  agent_tools?: Prisma.AgentToolCreateNestedManyWithoutToolInput
  evaluation_tools?: Prisma.EvaluationToolCreateNestedManyWithoutToolInput
}

export type ToolUncheckedCreateWithoutMcp_serverInput = {
  tool_id?: number
  id: string
  name: string
  description: string
  source: string
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  agent_tools?: Prisma.AgentToolUncheckedCreateNestedManyWithoutToolInput
  evaluation_tools?: Prisma.EvaluationToolUncheckedCreateNestedManyWithoutToolInput
}

export type ToolCreateOrConnectWithoutMcp_serverInput = {
  where: Prisma.ToolWhereUniqueInput
  create: Prisma.XOR<Prisma.ToolCreateWithoutMcp_serverInput, Prisma.ToolUncheckedCreateWithoutMcp_serverInput>
}

export type ToolCreateManyMcp_serverInputEnvelope = {
  data: Prisma.ToolCreateManyMcp_serverInput | Prisma.ToolCreateManyMcp_serverInput[]
}

export type ToolUpsertWithWhereUniqueWithoutMcp_serverInput = {
  where: Prisma.ToolWhereUniqueInput
  update: Prisma.XOR<Prisma.ToolUpdateWithoutMcp_serverInput, Prisma.ToolUncheckedUpdateWithoutMcp_serverInput>
  create: Prisma.XOR<Prisma.ToolCreateWithoutMcp_serverInput, Prisma.ToolUncheckedCreateWithoutMcp_serverInput>
}

export type ToolUpdateWithWhereUniqueWithoutMcp_serverInput = {
  where: Prisma.ToolWhereUniqueInput
  data: Prisma.XOR<Prisma.ToolUpdateWithoutMcp_serverInput, Prisma.ToolUncheckedUpdateWithoutMcp_serverInput>
}

export type ToolUpdateManyWithWhereWithoutMcp_serverInput = {
  where: Prisma.ToolScalarWhereInput
  data: Prisma.XOR<Prisma.ToolUpdateManyMutationInput, Prisma.ToolUncheckedUpdateManyWithoutMcp_serverInput>
}

export type ToolScalarWhereInput = {
  AND?: Prisma.ToolScalarWhereInput | Prisma.ToolScalarWhereInput[]
  OR?: Prisma.ToolScalarWhereInput[]
  NOT?: Prisma.ToolScalarWhereInput | Prisma.ToolScalarWhereInput[]
  tool_id?: Prisma.IntFilter<"Tool"> | number
  id?: Prisma.StringFilter<"Tool"> | string
  name?: Prisma.StringFilter<"Tool"> | string
  description?: Prisma.StringFilter<"Tool"> | string
  source?: Prisma.StringFilter<"Tool"> | string
  mcp_server_id?: Prisma.IntNullableFilter<"Tool"> | number | null
  locked_tier?: Prisma.IntNullableFilter<"Tool"> | number | null
  input_schema?: Prisma.JsonFilter<"Tool">
  output_schema?: Prisma.JsonNullableFilter<"Tool">
  created_at?: Prisma.DateTimeFilter<"Tool"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Tool"> | Date | string
}

export type ToolCreateWithoutAgent_toolsInput = {
  id: string
  name: string
  description: string
  source: string
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  mcp_server?: Prisma.McpServerCreateNestedOneWithoutToolsInput
  evaluation_tools?: Prisma.EvaluationToolCreateNestedManyWithoutToolInput
}

export type ToolUncheckedCreateWithoutAgent_toolsInput = {
  tool_id?: number
  id: string
  name: string
  description: string
  source: string
  mcp_server_id?: number | null
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  evaluation_tools?: Prisma.EvaluationToolUncheckedCreateNestedManyWithoutToolInput
}

export type ToolCreateOrConnectWithoutAgent_toolsInput = {
  where: Prisma.ToolWhereUniqueInput
  create: Prisma.XOR<Prisma.ToolCreateWithoutAgent_toolsInput, Prisma.ToolUncheckedCreateWithoutAgent_toolsInput>
}

export type ToolUpsertWithoutAgent_toolsInput = {
  update: Prisma.XOR<Prisma.ToolUpdateWithoutAgent_toolsInput, Prisma.ToolUncheckedUpdateWithoutAgent_toolsInput>
  create: Prisma.XOR<Prisma.ToolCreateWithoutAgent_toolsInput, Prisma.ToolUncheckedCreateWithoutAgent_toolsInput>
  where?: Prisma.ToolWhereInput
}

export type ToolUpdateToOneWithWhereWithoutAgent_toolsInput = {
  where?: Prisma.ToolWhereInput
  data: Prisma.XOR<Prisma.ToolUpdateWithoutAgent_toolsInput, Prisma.ToolUncheckedUpdateWithoutAgent_toolsInput>
}

export type ToolUpdateWithoutAgent_toolsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mcp_server?: Prisma.McpServerUpdateOneWithoutToolsNestedInput
  evaluation_tools?: Prisma.EvaluationToolUpdateManyWithoutToolNestedInput
}

export type ToolUncheckedUpdateWithoutAgent_toolsInput = {
  tool_id?: Prisma.IntFieldUpdateOperationsInput | number
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  mcp_server_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  evaluation_tools?: Prisma.EvaluationToolUncheckedUpdateManyWithoutToolNestedInput
}

export type ToolCreateWithoutEvaluation_toolsInput = {
  id: string
  name: string
  description: string
  source: string
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  mcp_server?: Prisma.McpServerCreateNestedOneWithoutToolsInput
  agent_tools?: Prisma.AgentToolCreateNestedManyWithoutToolInput
}

export type ToolUncheckedCreateWithoutEvaluation_toolsInput = {
  tool_id?: number
  id: string
  name: string
  description: string
  source: string
  mcp_server_id?: number | null
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
  agent_tools?: Prisma.AgentToolUncheckedCreateNestedManyWithoutToolInput
}

export type ToolCreateOrConnectWithoutEvaluation_toolsInput = {
  where: Prisma.ToolWhereUniqueInput
  create: Prisma.XOR<Prisma.ToolCreateWithoutEvaluation_toolsInput, Prisma.ToolUncheckedCreateWithoutEvaluation_toolsInput>
}

export type ToolUpsertWithoutEvaluation_toolsInput = {
  update: Prisma.XOR<Prisma.ToolUpdateWithoutEvaluation_toolsInput, Prisma.ToolUncheckedUpdateWithoutEvaluation_toolsInput>
  create: Prisma.XOR<Prisma.ToolCreateWithoutEvaluation_toolsInput, Prisma.ToolUncheckedCreateWithoutEvaluation_toolsInput>
  where?: Prisma.ToolWhereInput
}

export type ToolUpdateToOneWithWhereWithoutEvaluation_toolsInput = {
  where?: Prisma.ToolWhereInput
  data: Prisma.XOR<Prisma.ToolUpdateWithoutEvaluation_toolsInput, Prisma.ToolUncheckedUpdateWithoutEvaluation_toolsInput>
}

export type ToolUpdateWithoutEvaluation_toolsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mcp_server?: Prisma.McpServerUpdateOneWithoutToolsNestedInput
  agent_tools?: Prisma.AgentToolUpdateManyWithoutToolNestedInput
}

export type ToolUncheckedUpdateWithoutEvaluation_toolsInput = {
  tool_id?: Prisma.IntFieldUpdateOperationsInput | number
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  mcp_server_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agent_tools?: Prisma.AgentToolUncheckedUpdateManyWithoutToolNestedInput
}

export type ToolCreateManyMcp_serverInput = {
  tool_id?: number
  id: string
  name: string
  description: string
  source: string
  locked_tier?: number | null
  input_schema: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
}

export type ToolUpdateWithoutMcp_serverInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agent_tools?: Prisma.AgentToolUpdateManyWithoutToolNestedInput
  evaluation_tools?: Prisma.EvaluationToolUpdateManyWithoutToolNestedInput
}

export type ToolUncheckedUpdateWithoutMcp_serverInput = {
  tool_id?: Prisma.IntFieldUpdateOperationsInput | number
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agent_tools?: Prisma.AgentToolUncheckedUpdateManyWithoutToolNestedInput
  evaluation_tools?: Prisma.EvaluationToolUncheckedUpdateManyWithoutToolNestedInput
}

export type ToolUncheckedUpdateManyWithoutMcp_serverInput = {
  tool_id?: Prisma.IntFieldUpdateOperationsInput | number
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  locked_tier?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  input_schema?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  output_schema?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ToolCountOutputType
 */

export type ToolCountOutputType = {
  agent_tools: number
  evaluation_tools: number
}

export type ToolCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agent_tools?: boolean | ToolCountOutputTypeCountAgent_toolsArgs
  evaluation_tools?: boolean | ToolCountOutputTypeCountEvaluation_toolsArgs
}

/**
 * ToolCountOutputType without action
 */
export type ToolCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolCountOutputType
   */
  select?: Prisma.ToolCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ToolCountOutputType without action
 */
export type ToolCountOutputTypeCountAgent_toolsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentToolWhereInput
}

/**
 * ToolCountOutputType without action
 */
export type ToolCountOutputTypeCountEvaluation_toolsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EvaluationToolWhereInput
}


export type ToolSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tool_id?: boolean
  id?: boolean
  name?: boolean
  description?: boolean
  source?: boolean
  mcp_server_id?: boolean
  locked_tier?: boolean
  input_schema?: boolean
  output_schema?: boolean
  created_at?: boolean
  updated_at?: boolean
  mcp_server?: boolean | Prisma.Tool$mcp_serverArgs<ExtArgs>
  agent_tools?: boolean | Prisma.Tool$agent_toolsArgs<ExtArgs>
  evaluation_tools?: boolean | Prisma.Tool$evaluation_toolsArgs<ExtArgs>
  _count?: boolean | Prisma.ToolCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tool"]>

export type ToolSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tool_id?: boolean
  id?: boolean
  name?: boolean
  description?: boolean
  source?: boolean
  mcp_server_id?: boolean
  locked_tier?: boolean
  input_schema?: boolean
  output_schema?: boolean
  created_at?: boolean
  updated_at?: boolean
  mcp_server?: boolean | Prisma.Tool$mcp_serverArgs<ExtArgs>
}, ExtArgs["result"]["tool"]>

export type ToolSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tool_id?: boolean
  id?: boolean
  name?: boolean
  description?: boolean
  source?: boolean
  mcp_server_id?: boolean
  locked_tier?: boolean
  input_schema?: boolean
  output_schema?: boolean
  created_at?: boolean
  updated_at?: boolean
  mcp_server?: boolean | Prisma.Tool$mcp_serverArgs<ExtArgs>
}, ExtArgs["result"]["tool"]>

export type ToolSelectScalar = {
  tool_id?: boolean
  id?: boolean
  name?: boolean
  description?: boolean
  source?: boolean
  mcp_server_id?: boolean
  locked_tier?: boolean
  input_schema?: boolean
  output_schema?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type ToolOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"tool_id" | "id" | "name" | "description" | "source" | "mcp_server_id" | "locked_tier" | "input_schema" | "output_schema" | "created_at" | "updated_at", ExtArgs["result"]["tool"]>
export type ToolInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mcp_server?: boolean | Prisma.Tool$mcp_serverArgs<ExtArgs>
  agent_tools?: boolean | Prisma.Tool$agent_toolsArgs<ExtArgs>
  evaluation_tools?: boolean | Prisma.Tool$evaluation_toolsArgs<ExtArgs>
  _count?: boolean | Prisma.ToolCountOutputTypeDefaultArgs<ExtArgs>
}
export type ToolIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mcp_server?: boolean | Prisma.Tool$mcp_serverArgs<ExtArgs>
}
export type ToolIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mcp_server?: boolean | Prisma.Tool$mcp_serverArgs<ExtArgs>
}

export type $ToolPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tool"
  objects: {
    mcp_server: Prisma.$McpServerPayload<ExtArgs> | null
    agent_tools: Prisma.$AgentToolPayload<ExtArgs>[]
    evaluation_tools: Prisma.$EvaluationToolPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    tool_id: number
    id: string
    name: string
    description: string
    source: string
    mcp_server_id: number | null
    locked_tier: number | null
    input_schema: runtime.JsonValue
    output_schema: runtime.JsonValue | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["tool"]>
  composites: {}
}

export type ToolGetPayload<S extends boolean | null | undefined | ToolDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ToolPayload, S>

export type ToolCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ToolFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ToolCountAggregateInputType | true
  }

export interface ToolDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tool'], meta: { name: 'Tool' } }
  /**
   * Find zero or one Tool that matches the filter.
   * @param {ToolFindUniqueArgs} args - Arguments to find a Tool
   * @example
   * // Get one Tool
   * const tool = await prisma.tool.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ToolFindUniqueArgs>(args: Prisma.SelectSubset<T, ToolFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tool that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ToolFindUniqueOrThrowArgs} args - Arguments to find a Tool
   * @example
   * // Get one Tool
   * const tool = await prisma.tool.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ToolFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ToolFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tool that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolFindFirstArgs} args - Arguments to find a Tool
   * @example
   * // Get one Tool
   * const tool = await prisma.tool.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ToolFindFirstArgs>(args?: Prisma.SelectSubset<T, ToolFindFirstArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tool that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolFindFirstOrThrowArgs} args - Arguments to find a Tool
   * @example
   * // Get one Tool
   * const tool = await prisma.tool.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ToolFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ToolFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tools that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tools
   * const tools = await prisma.tool.findMany()
   * 
   * // Get first 10 Tools
   * const tools = await prisma.tool.findMany({ take: 10 })
   * 
   * // Only select the `tool_id`
   * const toolWithTool_idOnly = await prisma.tool.findMany({ select: { tool_id: true } })
   * 
   */
  findMany<T extends ToolFindManyArgs>(args?: Prisma.SelectSubset<T, ToolFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tool.
   * @param {ToolCreateArgs} args - Arguments to create a Tool.
   * @example
   * // Create one Tool
   * const Tool = await prisma.tool.create({
   *   data: {
   *     // ... data to create a Tool
   *   }
   * })
   * 
   */
  create<T extends ToolCreateArgs>(args: Prisma.SelectSubset<T, ToolCreateArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tools.
   * @param {ToolCreateManyArgs} args - Arguments to create many Tools.
   * @example
   * // Create many Tools
   * const tool = await prisma.tool.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ToolCreateManyArgs>(args?: Prisma.SelectSubset<T, ToolCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tools and returns the data saved in the database.
   * @param {ToolCreateManyAndReturnArgs} args - Arguments to create many Tools.
   * @example
   * // Create many Tools
   * const tool = await prisma.tool.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tools and only return the `tool_id`
   * const toolWithTool_idOnly = await prisma.tool.createManyAndReturn({
   *   select: { tool_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ToolCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ToolCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tool.
   * @param {ToolDeleteArgs} args - Arguments to delete one Tool.
   * @example
   * // Delete one Tool
   * const Tool = await prisma.tool.delete({
   *   where: {
   *     // ... filter to delete one Tool
   *   }
   * })
   * 
   */
  delete<T extends ToolDeleteArgs>(args: Prisma.SelectSubset<T, ToolDeleteArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tool.
   * @param {ToolUpdateArgs} args - Arguments to update one Tool.
   * @example
   * // Update one Tool
   * const tool = await prisma.tool.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ToolUpdateArgs>(args: Prisma.SelectSubset<T, ToolUpdateArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tools.
   * @param {ToolDeleteManyArgs} args - Arguments to filter Tools to delete.
   * @example
   * // Delete a few Tools
   * const { count } = await prisma.tool.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ToolDeleteManyArgs>(args?: Prisma.SelectSubset<T, ToolDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tools.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tools
   * const tool = await prisma.tool.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ToolUpdateManyArgs>(args: Prisma.SelectSubset<T, ToolUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tools and returns the data updated in the database.
   * @param {ToolUpdateManyAndReturnArgs} args - Arguments to update many Tools.
   * @example
   * // Update many Tools
   * const tool = await prisma.tool.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tools and only return the `tool_id`
   * const toolWithTool_idOnly = await prisma.tool.updateManyAndReturn({
   *   select: { tool_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ToolUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ToolUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tool.
   * @param {ToolUpsertArgs} args - Arguments to update or create a Tool.
   * @example
   * // Update or create a Tool
   * const tool = await prisma.tool.upsert({
   *   create: {
   *     // ... data to create a Tool
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tool we want to update
   *   }
   * })
   */
  upsert<T extends ToolUpsertArgs>(args: Prisma.SelectSubset<T, ToolUpsertArgs<ExtArgs>>): Prisma.Prisma__ToolClient<runtime.Types.Result.GetResult<Prisma.$ToolPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tools.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolCountArgs} args - Arguments to filter Tools to count.
   * @example
   * // Count the number of Tools
   * const count = await prisma.tool.count({
   *   where: {
   *     // ... the filter for the Tools we want to count
   *   }
   * })
  **/
  count<T extends ToolCountArgs>(
    args?: Prisma.Subset<T, ToolCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ToolCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tool.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ToolAggregateArgs>(args: Prisma.Subset<T, ToolAggregateArgs>): Prisma.PrismaPromise<GetToolAggregateType<T>>

  /**
   * Group by Tool.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ToolGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ToolGroupByArgs['orderBy'] }
      : { orderBy?: ToolGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ToolGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetToolGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tool model
 */
readonly fields: ToolFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tool.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ToolClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mcp_server<T extends Prisma.Tool$mcp_serverArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tool$mcp_serverArgs<ExtArgs>>): Prisma.Prisma__McpServerClient<runtime.Types.Result.GetResult<Prisma.$McpServerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  agent_tools<T extends Prisma.Tool$agent_toolsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tool$agent_toolsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentToolPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  evaluation_tools<T extends Prisma.Tool$evaluation_toolsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tool$evaluation_toolsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EvaluationToolPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tool model
 */
export interface ToolFieldRefs {
  readonly tool_id: Prisma.FieldRef<"Tool", 'Int'>
  readonly id: Prisma.FieldRef<"Tool", 'String'>
  readonly name: Prisma.FieldRef<"Tool", 'String'>
  readonly description: Prisma.FieldRef<"Tool", 'String'>
  readonly source: Prisma.FieldRef<"Tool", 'String'>
  readonly mcp_server_id: Prisma.FieldRef<"Tool", 'Int'>
  readonly locked_tier: Prisma.FieldRef<"Tool", 'Int'>
  readonly input_schema: Prisma.FieldRef<"Tool", 'Json'>
  readonly output_schema: Prisma.FieldRef<"Tool", 'Json'>
  readonly created_at: Prisma.FieldRef<"Tool", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Tool", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Tool findUnique
 */
export type ToolFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * Filter, which Tool to fetch.
   */
  where: Prisma.ToolWhereUniqueInput
}

/**
 * Tool findUniqueOrThrow
 */
export type ToolFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * Filter, which Tool to fetch.
   */
  where: Prisma.ToolWhereUniqueInput
}

/**
 * Tool findFirst
 */
export type ToolFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * Filter, which Tool to fetch.
   */
  where?: Prisma.ToolWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tools to fetch.
   */
  orderBy?: Prisma.ToolOrderByWithRelationInput | Prisma.ToolOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tools.
   */
  cursor?: Prisma.ToolWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tools from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tools.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tools.
   */
  distinct?: Prisma.ToolScalarFieldEnum | Prisma.ToolScalarFieldEnum[]
}

/**
 * Tool findFirstOrThrow
 */
export type ToolFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * Filter, which Tool to fetch.
   */
  where?: Prisma.ToolWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tools to fetch.
   */
  orderBy?: Prisma.ToolOrderByWithRelationInput | Prisma.ToolOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tools.
   */
  cursor?: Prisma.ToolWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tools from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tools.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tools.
   */
  distinct?: Prisma.ToolScalarFieldEnum | Prisma.ToolScalarFieldEnum[]
}

/**
 * Tool findMany
 */
export type ToolFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * Filter, which Tools to fetch.
   */
  where?: Prisma.ToolWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tools to fetch.
   */
  orderBy?: Prisma.ToolOrderByWithRelationInput | Prisma.ToolOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tools.
   */
  cursor?: Prisma.ToolWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tools from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tools.
   */
  skip?: number
  distinct?: Prisma.ToolScalarFieldEnum | Prisma.ToolScalarFieldEnum[]
}

/**
 * Tool create
 */
export type ToolCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * The data needed to create a Tool.
   */
  data: Prisma.XOR<Prisma.ToolCreateInput, Prisma.ToolUncheckedCreateInput>
}

/**
 * Tool createMany
 */
export type ToolCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tools.
   */
  data: Prisma.ToolCreateManyInput | Prisma.ToolCreateManyInput[]
}

/**
 * Tool createManyAndReturn
 */
export type ToolCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * The data used to create many Tools.
   */
  data: Prisma.ToolCreateManyInput | Prisma.ToolCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Tool update
 */
export type ToolUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * The data needed to update a Tool.
   */
  data: Prisma.XOR<Prisma.ToolUpdateInput, Prisma.ToolUncheckedUpdateInput>
  /**
   * Choose, which Tool to update.
   */
  where: Prisma.ToolWhereUniqueInput
}

/**
 * Tool updateMany
 */
export type ToolUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tools.
   */
  data: Prisma.XOR<Prisma.ToolUpdateManyMutationInput, Prisma.ToolUncheckedUpdateManyInput>
  /**
   * Filter which Tools to update
   */
  where?: Prisma.ToolWhereInput
  /**
   * Limit how many Tools to update.
   */
  limit?: number
}

/**
 * Tool updateManyAndReturn
 */
export type ToolUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * The data used to update Tools.
   */
  data: Prisma.XOR<Prisma.ToolUpdateManyMutationInput, Prisma.ToolUncheckedUpdateManyInput>
  /**
   * Filter which Tools to update
   */
  where?: Prisma.ToolWhereInput
  /**
   * Limit how many Tools to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Tool upsert
 */
export type ToolUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * The filter to search for the Tool to update in case it exists.
   */
  where: Prisma.ToolWhereUniqueInput
  /**
   * In case the Tool found by the `where` argument doesn't exist, create a new Tool with this data.
   */
  create: Prisma.XOR<Prisma.ToolCreateInput, Prisma.ToolUncheckedCreateInput>
  /**
   * In case the Tool was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ToolUpdateInput, Prisma.ToolUncheckedUpdateInput>
}

/**
 * Tool delete
 */
export type ToolDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
  /**
   * Filter which Tool to delete.
   */
  where: Prisma.ToolWhereUniqueInput
}

/**
 * Tool deleteMany
 */
export type ToolDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tools to delete
   */
  where?: Prisma.ToolWhereInput
  /**
   * Limit how many Tools to delete.
   */
  limit?: number
}

/**
 * Tool.mcp_server
 */
export type Tool$mcp_serverArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the McpServer
   */
  select?: Prisma.McpServerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the McpServer
   */
  omit?: Prisma.McpServerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McpServerInclude<ExtArgs> | null
  where?: Prisma.McpServerWhereInput
}

/**
 * Tool.agent_tools
 */
export type Tool$agent_toolsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentTool
   */
  select?: Prisma.AgentToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentTool
   */
  omit?: Prisma.AgentToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentToolInclude<ExtArgs> | null
  where?: Prisma.AgentToolWhereInput
  orderBy?: Prisma.AgentToolOrderByWithRelationInput | Prisma.AgentToolOrderByWithRelationInput[]
  cursor?: Prisma.AgentToolWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AgentToolScalarFieldEnum | Prisma.AgentToolScalarFieldEnum[]
}

/**
 * Tool.evaluation_tools
 */
export type Tool$evaluation_toolsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EvaluationTool
   */
  select?: Prisma.EvaluationToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EvaluationTool
   */
  omit?: Prisma.EvaluationToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvaluationToolInclude<ExtArgs> | null
  where?: Prisma.EvaluationToolWhereInput
  orderBy?: Prisma.EvaluationToolOrderByWithRelationInput | Prisma.EvaluationToolOrderByWithRelationInput[]
  cursor?: Prisma.EvaluationToolWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EvaluationToolScalarFieldEnum | Prisma.EvaluationToolScalarFieldEnum[]
}

/**
 * Tool without action
 */
export type ToolDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tool
   */
  select?: Prisma.ToolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tool
   */
  omit?: Prisma.ToolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ToolInclude<ExtArgs> | null
}
