import { ToolNode } from '@langchain/langgraph/prebuilt';
import { BaseMessage, HumanMessage, ToolMessage, isToolMessage } from '@langchain/core/messages';
import type { BaseChatModel } from '@langchain/core/language_models/chat_models';
import type { RunnableConfig, RunnableToolLike } from '@langchain/core/runnables';
import type { StructuredToolInterface, DynamicTool } from '@langchain/core/tools';

/**
 * Generates a human-friendly summary of a tool result using the provided LLM.
 * Falls back to a deterministic summary if the LLM call fails.
 */
export async function generateToolSummary(msg: ToolMessage, llm: BaseChatModel): Promise<string> {
  try {
    const prompt = `You called the tool "${msg.name}". Here is the result:\n\n${msg.content}\n\nSummarize this tool result in one concise sentence suitable for display in a chat UI. Be specific about what was returned. Do not include any preamble, just the summary sentence.`;
    
    const response = await llm.invoke([new HumanMessage(prompt)]);
    
    const text = typeof response.content === 'string'
      ? response.content.trim()
      : String(response.content).trim();
    
      return text || deterministicSummary(msg);
  } catch {
    return deterministicSummary(msg);
  }
}

/**
 * Deterministic fallback summary derived by parsing the tool message content.
 */
function deterministicSummary(msg: ToolMessage): string {
  const contentStr = typeof msg.content === 'string'
    ? msg.content
    : JSON.stringify(msg.content);

  try {
    const parsed = JSON.parse(contentStr);
    if (Array.isArray(parsed)) {
      return `Called ${msg.name} → returned ${parsed.length} item${parsed.length !== 1 ? 's' : ''}`;
    }
    const readableKeys = ['title', 'name', 'message', 'success'];
    const found = readableKeys.map(k => parsed[k]).find(v => v !== undefined && v !== null);
    if (found !== undefined) {
      return `Called ${msg.name} → ${found}`;
    }
    return `Called ${msg.name}`;
  } catch {
    return `Called ${msg.name ?? 'unknown tool'}`;
  }
}

/**
 * Creates a copy of a ToolMessage with tool_summary added to additional_kwargs.
 */
function withSummary(msg: ToolMessage, summary: string): ToolMessage {
  const artifactText = msg.artifact && msg.artifact.length > 0
    ? msg.artifact[0].resource.text
    : '';

  return new ToolMessage({
    content: [artifactText, summary].filter(Boolean).join('\n\n'),
    tool_call_id: msg.tool_call_id,
    name: msg.name,
    id: msg.id,
    status: msg.status,
    additional_kwargs: { ...msg.additional_kwargs, artifact: msg.artifact, tool_summary: summary },
    response_metadata: msg.response_metadata,
  });
}

async function enrichMessage(msg: BaseMessage, llm: BaseChatModel): Promise<BaseMessage> {
  if (!isToolMessage(msg)) return msg;
  const summary = await generateToolSummary(msg, llm);
  return withSummary(msg, summary);
}

async function enrichResult(result: unknown, llm: BaseChatModel): Promise<unknown> {
  if (Array.isArray(result)) {
    return Promise.all(result.map(msg => enrichMessage(msg, llm)));
  }
  if (result && typeof result === 'object' && 'messages' in result) {
    const r = result as { messages: BaseMessage[] };
    return {
      ...r,
      messages: await Promise.all(r.messages.map(msg => enrichMessage(msg, llm))),
    };
  }
  return result;
}

/**
 * A ToolNode subclass that enriches each ToolMessage with a `tool_summary`
 * string in `additional_kwargs` after execution. The summary is generated by
 * the provided LLM; falls back to a deterministic string on failure.
 */
export class SummarizingToolNode extends ToolNode {
  private readonly llm: BaseChatModel;

  constructor(
    tools: (StructuredToolInterface | DynamicTool | RunnableToolLike)[],
    llm: BaseChatModel,
    readonly isMCP: boolean = false, // for potential future use in MCP-specific logic
  ) {
    super(tools);
    this.llm = llm;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  async invoke(input: any, config?: RunnableConfig): Promise<any> {
    const result = await super.invoke(input, config);

    return enrichResult(result, this.llm);
  }
}
