
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Node
 * 
 */
export type Node = Prisma.NodeModel
/**
 * Model Edge
 * 
 */
export type Edge = Prisma.EdgeModel
/**
 * Model Asset
 * 
 */
export type Asset = Prisma.AssetModel
/**
 * Model Agent
 * 
 */
export type Agent = Prisma.AgentModel
/**
 * Model McpServer
 * 
 */
export type McpServer = Prisma.McpServerModel
/**
 * Model Tool
 * 
 */
export type Tool = Prisma.ToolModel
/**
 * Model AgentTool
 * 
 */
export type AgentTool = Prisma.AgentToolModel
/**
 * Model AgentAction
 * 
 */
export type AgentAction = Prisma.AgentActionModel
/**
 * Model checkpoints
 * 
 */
export type checkpoints = Prisma.checkpointsModel
/**
 * Model writes
 * 
 */
export type writes = Prisma.writesModel
